#!/bin/bash

STAGED_GO_FILES=$(git diff --cached --name-only | grep ".go$")

if [[ "$STAGED_GO_FILES" = "" ]]; then
  exit 0
fi

for FILE in $STAGED_GO_FILES
do
  echo $FILE
  gci write $FILE -s standard -s default -s "prefix(github.com/anyproto/anytype-heart)" -s blank -s dot
done

exit 0
