// Code generated by mockery. DO NOT EDIT.

package mock_apicore

import (
	context "context"

	domain "github.com/anyproto/anytype-heart/core/domain"
	files "github.com/anyproto/anytype-heart/core/files"

	mock "github.com/stretchr/testify/mock"
)

// MockFileObjectService is an autogenerated mock type for the FileObjectService type
type MockFileObjectService struct {
	mock.Mock
}

type MockFileObjectService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileObjectService) EXPECT() *MockFileObjectService_Expecter {
	return &MockFileObjectService_Expecter{mock: &_m.Mock}
}

// GetFileData provides a mock function with given fields: ctx, objectId
func (_m *MockFileObjectService) GetFileData(ctx context.Context, objectId string) (files.File, error) {
	ret := _m.Called(ctx, objectId)

	if len(ret) == 0 {
		panic("no return value specified for GetFileData")
	}

	var r0 files.File
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (files.File, error)); ok {
		return rf(ctx, objectId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) files.File); ok {
		r0 = rf(ctx, objectId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(files.File)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, objectId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFileObjectService_GetFileData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileData'
type MockFileObjectService_GetFileData_Call struct {
	*mock.Call
}

// GetFileData is a helper method to define mock.On call
//   - ctx context.Context
//   - objectId string
func (_e *MockFileObjectService_Expecter) GetFileData(ctx interface{}, objectId interface{}) *MockFileObjectService_GetFileData_Call {
	return &MockFileObjectService_GetFileData_Call{Call: _e.mock.On("GetFileData", ctx, objectId)}
}

func (_c *MockFileObjectService_GetFileData_Call) Run(run func(ctx context.Context, objectId string)) *MockFileObjectService_GetFileData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockFileObjectService_GetFileData_Call) Return(_a0 files.File, _a1 error) *MockFileObjectService_GetFileData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFileObjectService_GetFileData_Call) RunAndReturn(run func(context.Context, string) (files.File, error)) *MockFileObjectService_GetFileData_Call {
	_c.Call.Return(run)
	return _c
}

// GetImageData provides a mock function with given fields: ctx, objectId
func (_m *MockFileObjectService) GetImageData(ctx context.Context, objectId string) (files.Image, error) {
	ret := _m.Called(ctx, objectId)

	if len(ret) == 0 {
		panic("no return value specified for GetImageData")
	}

	var r0 files.Image
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (files.Image, error)); ok {
		return rf(ctx, objectId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) files.Image); ok {
		r0 = rf(ctx, objectId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(files.Image)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, objectId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFileObjectService_GetImageData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImageData'
type MockFileObjectService_GetImageData_Call struct {
	*mock.Call
}

// GetImageData is a helper method to define mock.On call
//   - ctx context.Context
//   - objectId string
func (_e *MockFileObjectService_Expecter) GetImageData(ctx interface{}, objectId interface{}) *MockFileObjectService_GetImageData_Call {
	return &MockFileObjectService_GetImageData_Call{Call: _e.mock.On("GetImageData", ctx, objectId)}
}

func (_c *MockFileObjectService_GetImageData_Call) Run(run func(ctx context.Context, objectId string)) *MockFileObjectService_GetImageData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockFileObjectService_GetImageData_Call) Return(_a0 files.Image, _a1 error) *MockFileObjectService_GetImageData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFileObjectService_GetImageData_Call) RunAndReturn(run func(context.Context, string) (files.Image, error)) *MockFileObjectService_GetImageData_Call {
	_c.Call.Return(run)
	return _c
}

// GetImageDataFromRawId provides a mock function with given fields: ctx, fileId
func (_m *MockFileObjectService) GetImageDataFromRawId(ctx context.Context, fileId domain.FileId) (files.Image, error) {
	ret := _m.Called(ctx, fileId)

	if len(ret) == 0 {
		panic("no return value specified for GetImageDataFromRawId")
	}

	var r0 files.Image
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.FileId) (files.Image, error)); ok {
		return rf(ctx, fileId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.FileId) files.Image); ok {
		r0 = rf(ctx, fileId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(files.Image)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.FileId) error); ok {
		r1 = rf(ctx, fileId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFileObjectService_GetImageDataFromRawId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImageDataFromRawId'
type MockFileObjectService_GetImageDataFromRawId_Call struct {
	*mock.Call
}

// GetImageDataFromRawId is a helper method to define mock.On call
//   - ctx context.Context
//   - fileId domain.FileId
func (_e *MockFileObjectService_Expecter) GetImageDataFromRawId(ctx interface{}, fileId interface{}) *MockFileObjectService_GetImageDataFromRawId_Call {
	return &MockFileObjectService_GetImageDataFromRawId_Call{Call: _e.mock.On("GetImageDataFromRawId", ctx, fileId)}
}

func (_c *MockFileObjectService_GetImageDataFromRawId_Call) Run(run func(ctx context.Context, fileId domain.FileId)) *MockFileObjectService_GetImageDataFromRawId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.FileId))
	})
	return _c
}

func (_c *MockFileObjectService_GetImageDataFromRawId_Call) Return(_a0 files.Image, _a1 error) *MockFileObjectService_GetImageDataFromRawId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFileObjectService_GetImageDataFromRawId_Call) RunAndReturn(run func(context.Context, domain.FileId) (files.Image, error)) *MockFileObjectService_GetImageDataFromRawId_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFileObjectService creates a new instance of MockFileObjectService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileObjectService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileObjectService {
	mock := &MockFileObjectService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
