version: "2"
run:
  go: "1.23"
  tests: false
linters:
  default: none
  enable:
    - errcheck
    - errorlint
    - funlen
    - gocritic
    - gosec
    - govet
    - importas
    - ineffassign
    - misspell
    - nestif
    - prealloc
    - revive
    - staticcheck
    - tagliatelle
    - unconvert
    - unused
  settings:
    errcheck:
      check-blank: true
    errchkjson:
      report-no-exported: true
    errorlint:
      errorf: true
      errorf-multi: true
      asserts: false
      comparison: true
    funlen:
      lines: 120
      statements: 100
    gocritic:
      disabled-checks:
        - ifElseChain
    gosec:
      excludes:
        - G602
        - G108
    misspell:
      locale: US
      ignore-rules:
        - commonspace
    revive:
      rules:
        - name: var-naming
          severity: warning
          disabled: true
    tagliatelle:
      case:
        rules:
          json: snake
        use-field-name: true
    unused:
      field-writes-are-uses: false
  exclusions:
    rules:
      - path-except: core/api
        linters:
          - tagliatelle
    generated: disable
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .*_test.go
      - mock*
      - testMock/*
      - clientlibrary/service/service.pb.go
      - pkg/lib/pb
      - pb
      - third_party$
      - builtin$
      - examples$
severity:
  default: error
  rules:
    - linters:
        - errcheck
        - staticcheck
      severity: warning
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/anyproto/anytype-heart
  exclusions:
    generated: disable
    paths:
      - .*_test.go
      - mock*
      - testMock/*
      - clientlibrary/service/service.pb.go
      - pkg/lib/pb
      - pb
      - third_party$
      - builtin$
      - examples$