run:
  timeout:  15m
  # didn't run linter on tests
  tests: false
  # don't check generated protobuf files
  go: '1.23'

issues:
  exclude-generated: disable
  exclude-dirs:
    - pkg/lib/pb
    - pb
  exclude-files:
    - '.*_test.go'
    - 'mock*'
    - 'testMock/*'
    - 'clientlibrary/service/service.pb.go'

linters-settings:
  unused:
    field-writes-are-uses: false
  errcheck:
    check-blank: true
  errchkjson:
    report-no-exported: true
  goimports:
    local-prefixes: github.com/anyproto/anytype-heart
  funlen:
    lines: 120
    statements: 100
  gocritic:
    disabled-checks:
      - ifElseChain
  misspell:
    locale: US
    ignore-words:
      - commonspace
  errorlint:
    errorf: true
    errorf-multi: true
    asserts: false
    comparison: true
  revive:
    rules:
      - name: var-naming
        severity: warning
        disabled: true
  gosec:
    excludes:
      - G602
      - G108
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake

linters:
  disable-all: true
  enable:
    - gocritic
    - gofmt
    - goimports
    - gosec
    - importas
    - ineffassign
    - misspell
    - nestif
    - prealloc
    - revive
    - unused
    - errcheck
    - funlen
    - gosimple
    - govet
    - unconvert
    - errorlint
    - tagliatelle

severity:
  default-severity: error
  rules:
      - severity: warning
        linters:
          - errcheck
          - gosimple
