run:
  deadline: 15m
  timeout:  15m
  # didn't run linter on tests
  tests: false
  # don't check generated protobuf files
  skip-dirs:
    - pkg/lib/pb
  go: '1.22'

linters-settings:
  errcheck:
    check-blank: true
  errchkjson:
    report-no-exported: true
  goimports:
    local-prefixes: github.com/anyproto/anytype-heart
  govet:
    check-shadowing: false
  funlen:
    lines: 120
    statements: 100
  gocritic:
    disabled-checks:
      - ifElseChain
  misspell:
    locale: US
    ignore-words:
      - commonspace
  errorlint:
    errorf: true
    errorf-multi: true
    asserts: false
    comparison: true
  revive:
    rules:
      - name: var-naming
        severity: warning
        disabled: true
  gosec:
    excludes:
      - G602
      - G108

linters:
  disable-all: true
  enable:
    - gocritic
    - gofmt
    - goimports
    - gosec
    - importas
    - ineffassign
    - misspell
    - nestif
    - prealloc
    - revive
    - unused
    - errcheck
    - funlen
    - gosimple
    - govet
    - unconvert
    - errorlint
  max-issues-per-linter: 0
  max-same-issues: 0

severity:
  default-severity: error
  rules:
      - severity: warning
        linters:
          - errcheck
          - gosimple
