dir: "{{.InterfaceDir}}/mock_{{.PackageName}}"
with-expecter: True
disable-version-string: True
all: False
outpkg: "mock_{{.PackageName}}"
packages:
  github.com/anyproto/anytype-heart/space/spacecore/typeprovider:
    interfaces:
      SmartBlockTypeProvider:
  github.com/anyproto/anytype-heart/core/wallet:
    interfaces:
      Wallet:
  github.com/anyproto/anytype-heart/core/event:
    interfaces:
      Sender:
  github.com/anyproto/anytype-heart/core/block/getblock:
    interfaces:
      ObjectGetter:
  github.com/anyproto/anytype-heart/pkg/lib/core:
    interfaces:
      Service:
  github.com/anyproto/anytype-heart/core/block/import/common:
    interfaces:
      Converter:
  github.com/anyproto/anytype-heart/pkg/lib/database:
    interfaces:
      ObjectStore:
        config:
          dir: "{{.InterfaceDir}}"
          outpkg: "{{.PackageName}}"
          inpackage: true
  github.com/anyproto/anytype-heart/pkg/lib/localstore/objectstore:
    interfaces:
      ObjectStore:
  github.com/anyproto/anytype-heart/core/block/restriction:
    interfaces:
      Service:
  github.com/anyproto/anytype-heart/core/filestorage/filesync:
    interfaces:
      FileSync:
  github.com/anyproto/anytype-heart/core/block/import/common/objectid:
    interfaces:
      IdGetterProvider:
  github.com/anyproto/anytype-heart/core/block/import/common/objectcreator:
    interfaces:
      Service:
  github.com/anyproto/anytype-heart/core/subscription:
    interfaces:
      CollectionService:
  github.com/anyproto/anytype-heart/core/block/object/objectcache:
    interfaces:
      Cache:
  github.com/anyproto/anytype-heart/metrics/amplitude:
    interfaces:
      Service:
  github.com/anyproto/anytype-heart/core/indexer:
    interfaces:
      Indexer:
  github.com/anyproto/anytype-heart/space/spacecore:
    interfaces:
      SpaceCoreService:
  github.com/anyproto/anytype-heart/space/internal/techspace:
    interfaces:
      TechSpace:
  github.com/anyproto/anytype-heart/space/spacefactory:
    interfaces:
      SpaceFactory:
  github.com/anyproto/anytype-heart/space/internal/spacecontroller:
    interfaces:
      SpaceController:
      DeleteController:
  github.com/anyproto/anytype-heart/space:
    interfaces:
      Service:
  github.com/anyproto/anytype-heart/space/clientspace:
    interfaces:
      Space:

