dir: "{{.InterfaceDir}}/mock_{{.PackageName}}"
with-expecter: True
disable-version-string: True
all: False
outpkg: "mock_{{.PackageName}}"
packages:
  github.com/anyproto/anytype-heart/space/spacecore/typeprovider:
    interfaces:
      SmartBlockTypeProvider:
  github.com/anyproto/anytype-heart/core/wallet:
    interfaces:
      Wallet:
  github.com/anyproto/anytype-heart/core/nameservice:
    interfaces:
      Service:
  github.com/anyproto/anytype-heart/core/event:
    interfaces:
      Sender:
  github.com/anyproto/anytype-heart/core/block/cache:
    interfaces:
      ObjectGetter:
      ObjectWaitGetter:
      CachedObjectGetter:
      ObjectGetterComponent:
      ObjectWaitGetterComponent:
  github.com/anyproto/anytype-heart/pkg/lib/core:
    interfaces:
      Service:
  github.com/anyproto/anytype-heart/core/block/editor/file:
    interfaces:
      File:
        config:
          dir: "{{.InterfaceDir}}"
          outpkg: "{{.PackageName}}"
          inpackage: true
  github.com/anyproto/anytype-heart/core/block/editor/fileobject:
    interfaces:
      FileObject:
  github.com/anyproto/anytype-heart/core/block/editor/smartblock:
    interfaces:
      Indexer:
        config:
          dir: "{{.InterfaceDir}}"
          outpkg: "{{.PackageName}}"
          inpackage: true
      Space:
        config:
          dir: "{{.InterfaceDir}}"
          outpkg: "{{.PackageName}}"
          inpackage: true
  github.com/anyproto/anytype-heart/core/block/import/common:
    interfaces:
      Converter:
  github.com/anyproto/anytype-heart/core/block/import/web/parsers:
    interfaces:
      Parser:
  github.com/anyproto/anytype-heart/core/block/restriction:
    interfaces:
      Service:
  github.com/anyproto/anytype-heart/core/files/filesync:
    interfaces:
      FileSync:
  github.com/anyproto/anytype-heart/core/files/fileuploader:
    interfaces:
      Service:
      Uploader:
  github.com/anyproto/anytype-heart/core/acl:
    interfaces:
      participantRemover:
  github.com/anyproto/anytype-heart/core/files/filestorage/rpcstore:
    interfaces:
      Service:
      RpcStore:
  github.com/anyproto/anytype-heart/core/block/import/common/objectid:
    interfaces:
      IdAndKeyProvider:
  github.com/anyproto/anytype-heart/core/block/import/common/objectcreator:
    interfaces:
      Service:
  github.com/anyproto/anytype-heart/core/block/import/common/syncer:
    interfaces:
      BlockService:
  github.com/anyproto/anytype-heart/core/subscription:
    interfaces:
      CollectionService:
        config:
          dir: "{{.InterfaceDir}}"
          outpkg: "{{.PackageName}}"
          inpackage: true
      Service:
  github.com/anyproto/anytype-heart/core/block/object/objectcache:
    interfaces:
      Cache:
  github.com/anyproto/anytype-heart/core/block/object/objectcreator:
    interfaces:
      Service:
  github.com/anyproto/anytype-heart/metrics/anymetry:
    interfaces:
      Service:
  github.com/anyproto/anytype-heart/core/invitestore:
    interfaces:
      Service:
  github.com/anyproto/anytype-heart/core/indexer:
    interfaces:
      Indexer:
  github.com/anyproto/anytype-heart/space/spacecore:
    interfaces:
      SpaceCoreService:
  github.com/anyproto/anytype-heart/space/spacecore/storage:
    interfaces:
      ClientStorage:
  github.com/anyproto/anytype-heart/space/spacecore/storage/anystorage:
    interfaces:
      ClientSpaceStorage:
  github.com/anyproto/anytype-heart/space/techspace:
    interfaces:
      TechSpace:
      SpaceView:
      AccountObject:
  github.com/anyproto/anytype-heart/space/spacefactory:
    interfaces:
      SpaceFactory:
  github.com/anyproto/anytype-heart/space/internal/spacecontroller:
    interfaces:
      SpaceController:
      DeleteController:
  github.com/anyproto/anytype-heart/space/internal/components/spaceloader:
    interfaces:
      SpaceLoader:
  github.com/anyproto/anytype-heart/space/internal/components/personalmigration:
    interfaces:
      fileObjectGetter:
  github.com/anyproto/anytype-heart/space/internal/components/participantwatcher:
    interfaces:
      ParticipantWatcher:
  github.com/anyproto/anytype-heart/space/internal/components/aclnotifications:
    interfaces:
      AclNotification:
      NotificationSender:
  github.com/anyproto/anytype-heart/space/internal/components/dependencies:
    interfaces:
      SpaceIndexer:
      IdentityService:
  github.com/anyproto/anytype-heart/space/internal/components/spacestatus:
    interfaces:
      SpaceStatus:
  github.com/anyproto/anytype-heart/space:
    interfaces:
      Service:
      coordinatorStatusUpdater:
      NotificationSender:
  github.com/anyproto/anytype-heart/space/clientspace:
    interfaces:
      Space:
  github.com/anyproto/anytype-heart/core/anytype/account:
    interfaces:
      Service:
  github.com/anyproto/anytype-heart/core/files/fileobject:
    interfaces:
      Service:
  github.com/anyproto/anytype-heart/core/files/filedownloader:
    interfaces:
      Service:
  github.com/anyproto/anytype-heart/core/files:
    interfaces:
      Service:
      File:
      Image:
  github.com/anyproto/anytype-heart/core/files/fileacl:
    interfaces:
      Service:
  github.com/anyproto/anytype-heart/space/deletioncontroller:
    interfaces:
      SpaceManager:
      DeletionController:
  github.com/anyproto/anytype-heart/core/domain:
    interfaces:
      InviteObject:
  github.com/anyproto/anytype-heart/core/payments/cache:
    interfaces:
      CacheService:
  github.com/anyproto/anytype-heart/core/payments/emailcollector:
    interfaces:
      EmailCollector:
  github.com/anyproto/anytype-heart/core/block:
    interfaces:
      ObjectGetter:
  github.com/anyproto/anytype-heart/core/block/source:
    interfaces:
      Service:
      Store:
  github.com/anyproto/anytype-heart/core/block/object/idresolver:
    interfaces:
      Resolver:
  github.com/anyproto/anytype-heart/core/files/filestorage:
    interfaces:
      FileStorage:
  github.com/anyproto/anytype-heart/util/linkpreview:
    interfaces:
      LinkPreview:
  github.com/anyproto/anytype-heart/space/spacecore/clientserver:
    interfaces:
      ClientServer:
  github.com/anyproto/anytype-heart/core/peerstatus:
    interfaces:
      LocalDiscoveryHook:
  github.com/anyproto/anytype-heart/core/device:
    interfaces:
      NetworkState:
      openedObjectRefresher:
  github.com/anyproto/anytype-heart/space/spacecore/localdiscovery:
    interfaces:
      Notifier:
        config:
          dir: "{{.InterfaceDir}}"
          outpkg: "{{.PackageName}}"
          inpackage: true
  github.com/anyproto/anytype-heart/core/block/object/treesyncer:
    interfaces:
      PeerStatusChecker:
      SyncDetailsUpdater:
  github.com/anyproto/anytype-heart/core/syncstatus/nodestatus:
    interfaces:
      NodeStatus:
  github.com/anyproto/anytype-heart/core/syncstatus/objectsyncstatus:
    interfaces:
      Updater:
  github.com/anyproto/anytype-heart/space/spacecore/peermanager:
    interfaces:
      Updater:
      PeerToPeerStatus:
  github.com/anyproto/anytype-heart/core/syncstatus/detailsupdater:
    interfaces:
      SpaceStatusUpdater:
  github.com/anyproto/anytype-heart/core/syncstatus/spacesyncstatus:
    interfaces:
      SpaceIdGetter:
      NodeUsage:
      NetworkConfig:
      Updater:
  github.com/anyproto/anytype-heart/core/block/import/notion/api/files:
    interfaces:
      Downloader:
  github.com/anyproto/anytype-heart/core/block/detailservice:
    interfaces:
      Service:
  github.com/anyproto/anytype-heart/core/kanban:
    interfaces:
      Service:
  github.com/anyproto/anytype-heart/core/inviteservice:
    interfaces:
      InviteService:
  github.com/anyproto/anytype-heart/core/identity:
    interfaces:
      Service:
  github.com/anyproto/anytype-heart/core/api/core:
    interfaces:
      AccountService:
      EventService:
      CrossSpaceSubscriptionService:
      ClientCommands:
  github.com/anyproto/anytype-heart/core/api/filter:
    interfaces:
      ApiService:
  github.com/anyproto/anytype-heart/core/block/template:
    interfaces:
      Service:
  github.com/anyproto/anytype-heart/core/subscription/crossspacesub:
    interfaces:
      Service:
  github.com/anyproto/anytype-heart/core/block/editor/chatobject:
    interfaces:
      StoreObject:
  github.com/anyproto/anytype-heart/core/block/chats/chatsubscription:
    interfaces:
      Service:
      Manager:
  github.com/anyproto/anytype-heart/core/relationutils:
    interfaces:
      RelationFormatFetcher:
  github.com/anyproto/anytype-heart/core/onetoone:
    interfaces:
      Service:
