dir: "{{.InterfaceDir}}/mock_{{.PackageName}}"
testonly: True
with-expecter: True
all: False
outpkg: "mock_{{.PackageName}}"
packages:
  github.com/anyproto/anytype-heart/space/typeprovider:
    interfaces:
      SmartBlockTypeProvider:
  github.com/anyproto/anytype-heart/core/wallet:
    interfaces:
      Wallet:
