package notion

import (
	"strings"

	"github.com/anyproto/anytype-heart/core/domain"
	"github.com/anyproto/anytype-heart/pkg/lib/bundle"
)

// Notion's built-in icon picker (API 2025-09-03) reports a NAMED icon:
//
//	"icon": {"type": "icon", "icon": {"name": "rocket", "color": "blue"}}
//
// which is the same kind of thing an Anytype type carries — a name from a
// closed vocabulary plus a color — so the two map straight across. The
// vocabularies differ: Notion's names are its own, Anytype's are the 390
// core/api/model.IconName constants the client ships a `type/<name>` sprite
// for. notionIconNames bridges them.
//
// Getting this wrong is not cosmetic. A database whose icon we cannot
// represent used to lose the planner's icon as well and render as the default
// glyph — in one real workspace 293 of 303 icons were named ones, so nearly
// every imported type came out blank.
//
// Notion publishes no enumeration of its icon names — the API reference gives
// examples only, and the picker's catalogue lives in a chunk the login bundle
// never loads — so the set was inventoried against Notion's own icon files,
// which are public and named after the icon:
//
//	https://www.notion.so/icons/<name>_<color>.svg   200 = real, 404 = not
//
// testdata/notion-icons.txt holds the result: 474 names, gathered from
// Anytype's own vocabulary, the Material Symbols and Lucide vocabularies, a
// real workspace's export and Notion's shipped UI chunks, then two rounds of
// variants until a round returned nothing new. Every one of them maps here,
// and TestEveryNotionIconResolves fails if that stops being true.
//
// A name Notion adds later is not lost either: resolveNotionIconName
// normalizes and shortens it, and failing that the planner's icon stands.
var notionIconNames = map[string]string{
	"123":                 "keypad",
	"accessibility":       "accessibility",
	"activity":            "pulse",
	"add":                 "add-circle",
	"airplane":            "airplane",
	"alarm":               "alarm",
	"alert":               "alert-circle",
	"alien":               "planet",
	"ambulance":           "medkit",
	"anchor":              "boat",
	"apple":               "nutrition",
	"archive":             "archive",
	"arrow-circle-down":   "arrow-down-circle",
	"arrow-down":          "arrow-down-circle",
	"arrow-down-line":     "arrow-down-circle",
	"arrow-left":          "arrow-back-circle",
	"arrow-left-line":     "arrow-back-circle",
	"arrow-right":         "arrow-forward-circle",
	"arrow-right-line":    "arrow-forward-circle",
	"arrow-up":            "arrow-up-circle",
	"arrow-up-line":       "arrow-up-circle",
	"art":                 "color-palette",
	"asterisk":            "star",
	"atm":                 "cash",
	"attachment":          "attach",
	"baby":                "person",
	"backpack":            "bag",
	"badge":               "ribbon",
	"bag":                 "bag",
	"baggage-claim":       "bag-handle",
	"balloon":             "balloon",
	"banana":              "nutrition",
	"barcode":             "barcode",
	"baseball":            "baseball",
	"basketball":          "basketball",
	"bathtub":             "water",
	"battery":             "battery-full",
	"battery-charging":    "battery-charging",
	"bed":                 "bed",
	"bee":                 "bug",
	"beer":                "beer",
	"bell":                "notifications",
	"bell-off":            "notifications-off",
	"bicycle":             "bicycle",
	"binoculars":          "binoculars",
	"blood-pressure":      "medical",
	"bluetooth":           "bluetooth",
	"boat":                "boat",
	"bomb":                "nuclear",
	"bone":                "paw",
	"book":                "book",
	"book-closed":         "book",
	"bookmark":            "bookmark",
	"bookmark-outline":    "bookmark",
	"boot":                "footsteps",
	"bowl":                "restaurant",
	"bowling":             "bowling-ball",
	"brain":               "bulb",
	"branch":              "git-branch",
	"bread":               "nutrition",
	"briefcase":           "briefcase",
	"brightness-high":     "sunny",
	"broccoli":            "nutrition",
	"broom":               "brush",
	"bug":                 "bug",
	"bullseye":            "locate",
	"burger":              "fast-food",
	"bus":                 "bus",
	"butterfly":           "flower",
	"button":              "radio-button-on",
	"cafe":                "cafe",
	"cake":                "nutrition",
	"calculator":          "calculator",
	"calendar":            "calendar",
	"calendar-month":      "calendar",
	"camera":              "camera",
	"camera-off":          "camera",
	"camera-roll":         "film",
	"candy":               "nutrition",
	"car":                 "car",
	"card":                "card",
	"cards":               "dice",
	"carrot":              "nutrition",
	"cash":                "cash",
	"cassette":            "disc",
	"castle":              "home",
	"cat":                 "paw",
	"cellular":            "cellular",
	"chair":               "bed",
	"champagne":           "wine",
	"chart":               "bar-chart",
	"chart-alternate":     "bar-chart",
	"chart-area":          "stats-chart",
	"chart-line":          "trending-up",
	"chart-pie":           "pie-chart",
	"chat":                "chatbubble",
	"check":               "checkmark-circle",
	"checklist":           "list",
	"checkmark":           "checkmark-circle",
	"checkmark-line":      "checkmark-circle",
	"checkmark-square":    "checkbox",
	"chemistry":           "flask",
	"chess-bishop":        "dice",
	"chess-king":          "dice",
	"chess-knight":        "dice",
	"chess-pawn":          "dice",
	"chess-queen":         "dice",
	"chess-rook":          "dice",
	"chicken":             "nutrition",
	"child":               "person",
	"church":              "business",
	"cigarette":           "flame",
	"circle":              "ellipse",
	"circle-alternate":    "ellipse",
	"circle-dashed":       "ellipse",
	"circle-dot":          "radio-button-on",
	"circle-remove":       "remove-circle",
	"city":                "business",
	"clear":               "close-circle",
	"clipping":            "cut",
	"clock":               "time",
	"clock-alternate":     "time",
	"close":               "close-circle",
	"cloud":               "cloud",
	"cloud-off":           "cloud-offline",
	"cloudy":              "cloudy",
	"clover":              "leaf",
	"coat":                "shirt",
	"code":                "code",
	"coffee":              "cafe",
	"coffee-maker":        "cafe",
	"color-palette":       "color-palette",
	"column":              "grid",
	"command-line":        "terminal",
	"comment":             "chatbubble",
	"compass":             "compass",
	"compose":             "create",
	"computer":            "desktop",
	"construction-crane":  "construct",
	"contrast":            "contrast",
	"conversation":        "chatbubbles",
	"copy":                "copy",
	"corn":                "nutrition",
	"cow":                 "paw",
	"create":              "create",
	"credit-card":         "card",
	"crop":                "crop",
	"currency":            "cash",
	"cursor":              "navigate",
	"customs":             "shield",
	"cut":                 "cut",
	"dashboard":           "speedometer",
	"database":            "server",
	"delete":              "trash",
	"dental":              "medical",
	"description":         "document-text",
	"dining":              "restaurant",
	"directions":          "navigate",
	"dna":                 "medical",
	"do-not-disturb":      "ban",
	"document":            "document",
	"dog":                 "paw",
	"download":            "download",
	"drafts":              "file-tray",
	"dress":               "shirt",
	"drink":               "pint",
	"duck":                "paw",
	"ear":                 "ear",
	"earthquake":          "warning",
	"egg":                 "egg",
	"eject":               "exit",
	"elephant":            "paw",
	"elevator":            "swap-vertical",
	"emoji":               "happy",
	"error":               "close-circle",
	"escalator":           "trending-up",
	"exit":                "exit",
	"expand":              "expand",
	"extension":           "extension-puzzle",
	"factory":             "business",
	"feather":             "leaf",
	"feed":                "reader",
	"fire":                "flame",
	"fire-extinguisher":   "flame",
	"fire-truck":          "car",
	"fireworks":           "sparkles",
	"fish":                "fish",
	"flag":                "flag",
	"flash":               "flash",
	"flashlight":          "flashlight",
	"flatware":            "restaurant",
	"flood":               "water",
	"folder":              "folder",
	"football":            "football",
	"formula":             "calculator",
	"forward":             "arrow-redo",
	"friends":             "people",
	"fuel":                "car",
	"gavel":               "hammer",
	"gear":                "cog",
	"gears":               "cog",
	"gem":                 "diamond",
	"ghost":               "skull",
	"gift":                "gift",
	"git":                 "git-branch",
	"glasses":             "glasses",
	"globe":               "globe",
	"golf":                "golf",
	"government":          "business",
	"grid":                "grid",
	"grocery":             "cart",
	"group":               "people",
	"groups":              "people",
	"guitar":              "musical-notes",
	"gym":                 "barbell",
	"hail":                "rainy",
	"hammer":              "hammer",
	"hand":                "hand-right",
	"handbag":             "bag-handle",
	"hanger":              "shirt",
	"hashtag":             "pricetag",
	"headphones":          "headset",
	"headset":             "headset",
	"heart":               "heart",
	"heart-outline":       "heart",
	"helicopter":          "airplane",
	"hexagon":             "shapes",
	"hexagon-alternate":   "shapes",
	"history":             "time",
	"home":                "home",
	"hourglass":           "hourglass",
	"inbox":               "file-tray-full",
	"infinity":            "infinite",
	"info":                "information-circle",
	"jar":                 "beaker",
	"key":                 "key",
	"keyboard":            "keypad",
	"keyboard-alternate":  "keypad",
	"keypad":              "keypad",
	"kite":                "balloon",
	"knife":               "restaurant",
	"language":            "language",
	"laptop":              "laptop",
	"layers":              "layers",
	"leaf":                "leaf",
	"lemon":               "nutrition",
	"library":             "library",
	"link":                "link",
	"list":                "list",
	"litter-disposal":     "trash-bin",
	"location":            "location",
	"lock":                "lock-closed",
	"lock-keyhole":        "lock-closed",
	"log-in":              "log-in",
	"log-out":             "log-out",
	"luggage":             "bag-handle",
	"magic-wand":          "color-wand",
	"magnet":              "magnet",
	"mail":                "mail",
	"map":                 "map",
	"map-pin":             "location",
	"map-pin-alternate":   "location",
	"meat":                "nutrition",
	"medication":          "medical",
	"meeting":             "people",
	"megaphone":           "megaphone",
	"merge":               "git-merge",
	"metronome":           "musical-notes",
	"microphone":          "mic",
	"microphone-off":      "mic-off",
	"microscope":          "flask",
	"microwave":           "restaurant",
	"mirror":              "aperture",
	"mobile":              "phone-portrait",
	"monorail":            "train",
	"moon":                "moon",
	"mop":                 "brush",
	"more":                "options",
	"mosque":              "business",
	"motorcycle":          "bicycle",
	"mouth":               "happy",
	"move":                "move",
	"movie":               "film",
	"mushroom":            "nutrition",
	"music":               "musical-notes",
	"navigation":          "navigate",
	"network":             "git-network",
	"news":                "newspaper",
	"notification":        "notifications",
	"notion":              "document",
	"nut":                 "nutrition",
	"octagon":             "shapes",
	"onion":               "nutrition",
	"orange":              "nutrition",
	"orbit":               "planet",
	"oven":                "restaurant",
	"package":             "cube",
	"paint-bucket":        "color-fill",
	"paint-roller":        "brush",
	"parking":             "car",
	"partly-cloudy-day":   "partly-sunny",
	"partly-cloudy-night": "cloudy-night",
	"passport":            "id-card",
	"paste":               "clipboard",
	"pen":                 "pencil",
	"pencil":              "pencil",
	"pentagon":            "shapes",
	"pentagon-alternate":  "shapes",
	"people":              "people",
	"perfume":             "rose",
	"phone":               "call",
	"phone-call":          "call",
	"piano":               "musical-notes",
	"pig":                 "paw",
	"pill":                "medical",
	"pin":                 "pin",
	"pizza":               "pizza",
	"playlist":            "musical-notes",
	"plus":                "add-circle",
	"potted-plant":        "flower",
	"power":               "power",
	"preview":             "eye",
	"print":               "print",
	"priority-high":       "alert-circle",
	"profile":             "person-circle",
	"public":              "earth",
	"pull-request":        "git-pull-request",
	"pump":                "water",
	"push-pin":            "pin",
	"puzzle":              "extension-puzzle",
	"question-mark":       "help-circle",
	"radio":               "radio",
	"rain":                "rainy",
	"rainbow":             "color-palette",
	"receipt":             "receipt",
	"redo":                "arrow-redo",
	"refresh":             "refresh",
	"refrigerator":        "snow",
	"remove":              "remove-circle",
	"rename":              "create",
	"reorder":             "swap-vertical",
	"repeat":              "repeat",
	"reply":               "arrow-undo",
	"reply-all":           "arrow-undo",
	"report":              "document-text",
	"robot":               "hardware-chip",
	"rocket":              "rocket",
	"row":                 "list",
	"ruler":               "resize",
	"run":                 "walk",
	"sailboat":            "boat",
	"sandwich":            "fast-food",
	"save":                "save",
	"school":              "school",
	"science":             "flask",
	"scooter":             "bicycle",
	"script":              "code-slash",
	"search":              "search",
	"seed":                "leaf",
	"send":                "send",
	"server":              "server",
	"share":               "share",
	"shell":               "fish",
	"shield":              "shield",
	"shirt":               "shirt",
	"shoe":                "footsteps",
	"shop":                "storefront",
	"shopping-bag":        "bag-handle",
	"shopping-basket":     "basket",
	"shopping-cart":       "cart",
	"shower":              "water",
	"shuffle":             "shuffle",
	"sink":                "water",
	"skateboard":          "bicycle",
	"skip-forward":        "play-skip-forward",
	"skull":               "skull",
	"sliders-horizontal":  "options",
	"sliders-vertical":    "options",
	"slideshow":           "easel",
	"snake":               "paw",
	"snippet":             "document-text",
	"snowflake":           "snow",
	"soap":                "water",
	"soccer":              "football",
	"sock":                "shirt",
	"spider":              "bug",
	"spoon":               "restaurant",
	"square":              "square",
	"square-alternate":    "square",
	"square-circle":       "shapes",
	"square-dashed":       "square",
	"stairs":              "footsteps",
	"star":                "star",
	"star-half":           "star-half",
	"star-outline":        "star",
	"stars":               "sparkles",
	"stethoscope":         "medical",
	"sticker":             "pricetag",
	"stopwatch":           "stopwatch",
	"storm":               "thunderstorm",
	"strawberry":          "nutrition",
	"stroller":            "person",
	"subtitles":           "text",
	"suit":                "shirt",
	"suitcase":            "briefcase",
	"sun":                 "sunny",
	"sunglasses":          "glasses",
	"sunrise":             "partly-sunny",
	"sunset":              "partly-sunny",
	"sword":               "cut",
	"symbol":              "shapes",
	"synagogue":           "business",
	"sync":                "sync",
	"syringe":             "medical",
	"table":               "grid",
	"tablet":              "tablet-portrait",
	"tabs":                "browsers",
	"tag":                 "pricetag",
	"target":              "locate",
	"taxi":                "car",
	"teapot":              "cafe",
	"telephone":           "call",
	"telescope":           "telescope",
	"thought":             "chatbubble-ellipses",
	"thought-alert":       "chatbubble-ellipses",
	"thought-dialogue":    "chatbubbles",
	"thumbs-down":         "thumbs-down",
	"thumbs-up":           "thumbs-up",
	"ticket":              "ticket",
	"timeline":            "time",
	"toilet":              "water",
	"token":               "cash",
	"tooth":               "medical",
	"tornado":             "thunderstorm",
	"traffic-cone":        "construct",
	"train":               "train",
	"translate":           "language",
	"tree":                "leaf",
	"triangle":            "triangle",
	"triangle-alternate":  "triangle",
	"triangle-dashed":     "triangle",
	"trophy":              "trophy",
	"truck":               "bus",
	"trumpet":             "musical-notes",
	"tshirt":              "shirt",
	"tv":                  "tv",
	"umbrella":            "umbrella",
	"undo":                "arrow-undo",
	"unlock":              "lock-open",
	"upload":              "cloud-upload",
	"user":                "person",
	"user-circle":         "person-circle",
	"user-circle-filled":  "person-circle",
	"verified":            "shield-checkmark",
	"videotape":           "videocam",
	"view":                "eye",
	"view-off":            "eye-off",
	"violin":              "musical-notes",
	"voicemail":           "call",
	"volcano":             "flame",
	"volume-high":         "volume-high",
	"volume-off":          "volume-off",
	"walk":                "walk",
	"warning":             "warning",
	"water":               "water",
	"whale":               "fish",
	"wheat":               "leaf",
	"wheelchair":          "accessibility",
	"whistle":             "megaphone",
	"wifi":                "wifi",
	"wind":                "cloudy",
	"window":              "browsers",
	"wine":                "wine",
	"wrench":              "construct",
	"zoom-in":             "search",
	"zoom-out":            "search",
}

// notionEmoji is what a page or callout wears when Notion's icon says more
// than an Anytype icon can. The two channels are not the same vocabulary:
// types carry a named icon from Anytype's 390, while everything else carries
// an emoji, and emoji is the richer set — sixteen of Notion's food icons all
// map to the one "nutrition" icon, but a banana can simply be a banana.
//
// Only names where a distinct emoji beats the composed one are listed; the
// rest fall through to notionIconEmoji, which keeps a page and its type
// agreeing wherever they can. Keyed by the name Notion sent (after the same
// normalization the icon lookup does), not by the Anytype icon, because that
// mapping is exactly the one being bypassed.
var notionEmoji = map[string]string{
	"123":               "🔢",
	"alien":             "👽",
	"anchor":            "⚓",
	"apple":             "🍎",
	"asterisk":          "✳️",
	"atm":               "🏧",
	"baby":              "👶",
	"backpack":          "🎒",
	"baggage-claim":     "🧳",
	"banana":            "🍌",
	"bathtub":           "🛁",
	"bee":               "🐝",
	"blood-pressure":    "🩸",
	"bone":              "🦴",
	"boot":              "🥾",
	"bowl":              "🥣",
	"bread":             "🍞",
	"broccoli":          "🥦",
	"broom":             "🧹",
	"butterfly":         "🦋",
	"cake":              "🍰",
	"candy":             "🍬",
	"cards":             "🃏",
	"carrot":            "🥕",
	"castle":            "🏰",
	"cat":               "🐈",
	"chair":             "🪑",
	"champagne":         "🍾",
	"chess-bishop":      "♟️",
	"chess-king":        "♟️",
	"chess-knight":      "♟️",
	"chess-pawn":        "♟️",
	"chess-queen":       "♟️",
	"chess-rook":        "♟️",
	"chicken":           "🍗",
	"child":             "🧒",
	"church":            "⛪",
	"cigarette":         "🚬",
	"city":              "🏙️",
	"clover":            "🍀",
	"coat":              "🧥",
	"coffee":            "☕",
	"corn":              "🌽",
	"cow":               "🐄",
	"currency":          "💱",
	"customs":           "🛃",
	"dental":            "🦷",
	"dna":               "🧬",
	"dog":               "🐕",
	"dress":             "👗",
	"duck":              "🦆",
	"eject":             "⏏️",
	"elephant":          "🐘",
	"elevator":          "🛗",
	"factory":           "🏭",
	"feather":           "🪶",
	"fire-extinguisher": "🧯",
	"fire-truck":        "🚒",
	"fireworks":         "🎆",
	"flatware":          "🍴",
	"flood":             "🌊",
	"friends":           "👫",
	"fuel":              "⛽",
	"gavel":             "⚖️",
	"ghost":             "👻",
	"government":        "🏛️",
	"guitar":            "🎸",
	"hail":              "🌨️",
	"handbag":           "👜",
	"hashtag":           "#️⃣",
	"helicopter":        "🚁",
	"history":           "🕰️",
	"kite":              "🪁",
	"knife":             "🔪",
	"lemon":             "🍋",
	"luggage":           "🧳",
	"meat":              "🥩",
	"medication":        "💊",
	"metronome":         "🎼",
	"microscope":        "🔬",
	"monorail":          "🚝",
	"mosque":            "🕌",
	"motorcycle":        "🏍️",
	"mouth":             "👄",
	"movie":             "🎬",
	"mushroom":          "🍄",
	"nut":               "🥜",
	"octagon":           "🛑",
	"onion":             "🧅",
	"orange":            "🍊",
	"orbit":             "🪐",
	"parking":           "🅿️",
	"pen":               "🖊️",
	"piano":             "🎹",
	"pig":               "🐷",
	"pill":              "💊",
	"playlist":          "🎶",
	"potted-plant":      "🪴",
	"rainbow":           "🌈",
	"run":               "🏃",
	"sailboat":          "⛵",
	"sandwich":          "🥪",
	"scooter":           "🛵",
	"seed":              "🌱",
	"shell":             "🐚",
	"shoe":              "👟",
	"shopping-bag":      "🛍️",
	"shower":            "🚿",
	"sink":              "🚰",
	"skateboard":        "🛹",
	"snake":             "🐍",
	"soap":              "🧼",
	"soccer":            "⚽",
	"sock":              "🧦",
	"spider":            "🕷️",
	"spoon":             "🥄",
	"strawberry":        "🍓",
	"stroller":          "🍼",
	"suit":              "👔",
	"sunglasses":        "🕶️",
	"sunrise":           "🌅",
	"sunset":            "🌇",
	"sword":             "⚔️",
	"synagogue":         "🕍",
	"syringe":           "💉",
	"tabs":              "🗂️",
	"taxi":              "🚕",
	"teapot":            "🫖",
	"thought":           "💭",
	"thought-alert":     "💭",
	"thought-dialogue":  "💭",
	"toilet":            "🚽",
	"token":             "🪙",
	"tooth":             "🦷",
	"tornado":           "🌪️",
	"traffic-cone":      "🚧",
	"tree":              "🌳",
	"truck":             "🚚",
	"trumpet":           "🎺",
	"violin":            "🎻",
	"volcano":           "🌋",
	"whale":             "🐋",
	"wheat":             "🌾",
	"wind":              "🌬️",
	"wrench":            "🔧",
	"zoom-out":          "🔎",
}

// notionIconEmoji renders a named icon as an emoji, for the objects that
// cannot wear one. Anytype's named icons are a TYPE-only feature — the API
// refuses them for anything else, and the client renders iconName only for
// the object-type layout — so a page or a callout whose Notion icon is a
// built-in one has exactly one channel left: an emoji.
//
// This is why it is keyed by the ANYTYPE name rather than Notion's: the two
// tables compose (Notion name → Anytype icon → emoji), so a Notion name only
// has to be classified once and the emoji can never disagree with the icon a
// type gets for the same source.
//
// Icons with no fair emoji are simply absent; a page with no icon is better
// than a page wearing the wrong one.
var notionIconEmoji = map[string]string{
	"accessibility":        "♿",
	"add-circle":           "➕",
	"airplane":             "✈️",
	"alarm":                "⏰",
	"alert-circle":         "⚠️",
	"aperture":             "📷",
	"archive":              "🗄️",
	"arrow-back-circle":    "⬅️",
	"arrow-down-circle":    "⬇️",
	"arrow-forward-circle": "➡️",
	"arrow-redo":           "↪️",
	"arrow-undo":           "↩️",
	"arrow-up-circle":      "⬆️",
	"attach":               "📎",
	"bag":                  "👜",
	"bag-handle":           "🛍️",
	"balloon":              "🎈",
	"ban":                  "🚫",
	"bar-chart":            "📊",
	"barbell":              "🏋️",
	"barcode":              "📊",
	"baseball":             "⚾",
	"basket":               "🧺",
	"basketball":           "🏀",
	"battery-charging":     "🔋",
	"battery-full":         "🔋",
	"beaker":               "⚗️",
	"bed":                  "🛏️",
	"beer":                 "🍺",
	"bicycle":              "🚲",
	"binoculars":           "🔭",
	"bluetooth":            "📶",
	"boat":                 "⛵",
	"book":                 "📖",
	"bookmark":             "🔖",
	"bowling-ball":         "🎳",
	"briefcase":            "💼",
	"browsers":             "🪟",
	"brush":                "🖌️",
	"bug":                  "🐛",
	"bulb":                 "💡",
	"bus":                  "🚌",
	"business":             "🏢",
	"cafe":                 "☕",
	"calculator":           "🧮",
	"calendar":             "📅",
	"call":                 "📞",
	"camera":               "📷",
	"car":                  "🚗",
	"card":                 "💳",
	"cart":                 "🛒",
	"cash":                 "💵",
	"cellular":             "📶",
	"chatbubble":           "💬",
	"chatbubble-ellipses":  "💬",
	"chatbubbles":          "💬",
	"checkbox":             "☑️",
	"checkmark-circle":     "✅",
	"clipboard":            "📋",
	"close-circle":         "❌",
	"cloud":                "☁️",
	"cloud-offline":        "☁️",
	"cloud-upload":         "☁️",
	"cloudy":               "☁️",
	"cloudy-night":         "☁️",
	"code":                 "💻",
	"code-slash":           "💻",
	"cog":                  "⚙️",
	"color-fill":           "🎨",
	"color-palette":        "🎨",
	"color-wand":           "🪄",
	"compass":              "🧭",
	"construct":            "🏗️",
	"contrast":             "🌗",
	"copy":                 "📋",
	"create":               "✏️",
	"crop":                 "✂️",
	"cube":                 "📦",
	"cut":                  "✂️",
	"desktop":              "🖥️",
	"diamond":              "💎",
	"dice":                 "🎲",
	"disc":                 "💿",
	"document":             "📄",
	"document-text":        "📝",
	"download":             "⬇️",
	"ear":                  "👂",
	"earth":                "🌍",
	"easel":                "🖼️",
	"egg":                  "🥚",
	"ellipse":              "⚪",
	"exit":                 "🚪",
	"expand":               "↔️",
	"extension-puzzle":     "🧩",
	"eye":                  "👁️",
	"eye-off":              "🙈",
	"fast-food":            "🍔",
	"file-tray":            "📥",
	"file-tray-full":       "📥",
	"film":                 "🎞️",
	"fish":                 "🐟",
	"flag":                 "🚩",
	"flame":                "🔥",
	"flash":                "⚡",
	"flashlight":           "🔦",
	"flask":                "⚗️",
	"flower":               "🌸",
	"folder":               "📁",
	"football":             "🏈",
	"footsteps":            "👣",
	"gift":                 "🎁",
	"git-branch":           "🌿",
	"git-merge":            "🔀",
	"git-network":          "🕸️",
	"git-pull-request":     "🔀",
	"glasses":              "👓",
	"globe":                "🌐",
	"golf":                 "⛳",
	"grid":                 "🔲",
	"hammer":               "🔨",
	"hand-right":           "👉",
	"happy":                "🙂",
	"hardware-chip":        "🤖",
	"headset":              "🎧",
	"heart":                "❤️",
	"help-circle":          "❓",
	"home":                 "🏠",
	"hourglass":            "⏳",
	"id-card":              "🪪",
	"infinite":             "♾️",
	"information-circle":   "ℹ️",
	"key":                  "🔑",
	"keypad":               "⌨️",
	"language":             "🌐",
	"laptop":               "💻",
	"layers":               "🗂️",
	"leaf":                 "🌿",
	"library":              "📚",
	"link":                 "🔗",
	"list":                 "📋",
	"locate":               "🎯",
	"location":             "📍",
	"lock-closed":          "🔒",
	"lock-open":            "🔓",
	"log-in":               "➡️",
	"log-out":              "⬅️",
	"magnet":               "🧲",
	"mail":                 "✉️",
	"map":                  "🗺️",
	"medical":              "🩺",
	"medkit":               "🧰",
	"megaphone":            "📣",
	"mic":                  "🎤",
	"mic-off":              "🔇",
	"moon":                 "🌙",
	"move":                 "↔️",
	"musical-notes":        "🎵",
	"navigate":             "🧭",
	"newspaper":            "📰",
	"notifications":        "🔔",
	"notifications-off":    "🔕",
	"nuclear":              "☢️",
	"nutrition":            "🥗",
	"options":              "🎛️",
	"partly-sunny":         "⛅",
	"paw":                  "🐾",
	"pencil":               "✏️",
	"people":               "👥",
	"person":               "👤",
	"person-circle":        "👤",
	"phone-portrait":       "📱",
	"pie-chart":            "📊",
	"pin":                  "📌",
	"pint":                 "🍺",
	"pizza":                "🍕",
	"planet":               "🪐",
	"play-skip-forward":    "⏭️",
	"power":                "🔌",
	"pricetag":             "🏷️",
	"print":                "🖨️",
	"pulse":                "📈",
	"radio":                "📻",
	"radio-button-on":      "🔘",
	"rainy":                "🌧️",
	"reader":               "📰",
	"receipt":              "🧾",
	"refresh":              "🔄",
	"remove-circle":        "➖",
	"repeat":               "🔁",
	"resize":               "📐",
	"restaurant":           "🍽️",
	"ribbon":               "🎗️",
	"rocket":               "🚀",
	"rose":                 "🌹",
	"save":                 "💾",
	"school":               "🎓",
	"search":               "🔍",
	"send":                 "📤",
	"server":               "🗄️",
	"shapes":               "🔷",
	"share":                "🔗",
	"shield":               "🛡️",
	"shield-checkmark":     "🛡️",
	"shirt":                "👕",
	"shuffle":              "🔀",
	"skull":                "💀",
	"snow":                 "❄️",
	"sparkles":             "✨",
	"speedometer":          "📊",
	"square":               "⬜",
	"star":                 "⭐",
	"star-half":            "⭐",
	"stats-chart":          "📈",
	"stopwatch":            "⏱️",
	"storefront":           "🏪",
	"sunny":                "☀️",
	"swap-vertical":        "↕️",
	"sync":                 "🔄",
	"tablet-portrait":      "📱",
	"telescope":            "🔭",
	"terminal":             "💻",
	"text":                 "📝",
	"thumbs-down":          "👎",
	"thumbs-up":            "👍",
	"thunderstorm":         "⛈️",
	"ticket":               "🎫",
	"time":                 "🕐",
	"train":                "🚆",
	"trash":                "🗑️",
	"trash-bin":            "🗑️",
	"trending-up":          "📈",
	"triangle":             "🔺",
	"trophy":               "🏆",
	"tv":                   "📺",
	"umbrella":             "☂️",
	"videocam":             "📹",
	"volume-high":          "🔊",
	"volume-off":           "🔇",
	"walk":                 "🚶",
	"warning":              "⚠️",
	"water":                "💧",
	"wifi":                 "📶",
	"wine":                 "🍷",
}

// emojiForNotionIcon renders a Notion built-in icon as an emoji, for objects
// that cannot carry a named icon.
func emojiForNotionIcon(icon *iconValue) string {
	if icon == nil || icon.Type != "icon" || icon.Icon == nil {
		return ""
	}
	name, matched, ok := resolveNotionIconName(icon.Icon.Name)
	if !ok {
		return ""
	}
	if emoji := notionEmoji[matched]; emoji != "" {
		return emoji
	}
	return notionIconEmoji[name]
}

// notionIconVariants are Notion's variant suffixes ("clock-alternate" is the
// same clock, drawn differently). Stripping one and retrying covers variants
// of names already in the table without listing each one.
var notionIconVariants = []string{
	"-alternate", "-alternative", "-line", "-filled", "-outline",
	"-heavy", "-light", "-solid", "-square", "-circle",
}

// resolveNotionIconName maps one Notion icon name onto an Anytype icon.
//
// The table is the first answer and covers Notion's set as inventoried; the
// steps after it are for names added since. Notion documents its names as
// case-insensitive with spaces, underscores and hyphens equivalent, so that
// normalization comes first. Then variant suffixes, then progressively
// dropping trailing words — "chart-bar-stacked" is a chart, "book-open" is a
// book. Whatever is left has no counterpart, and the caller keeps the icon it
// already had.
func resolveNotionIconName(raw string) (name, matched string, ok bool) {
	normalized := strings.ToLower(strings.TrimSpace(raw))
	normalized = strings.Map(func(r rune) rune {
		if r == ' ' || r == '_' {
			return '-'
		}
		return r
	}, normalized)

	lookup := func(candidate string) (string, string, bool) {
		if resolved, ok := notionIconNames[candidate]; ok {
			return resolved, candidate, true
		}
		// Every suffix is tried, not just the first that matches: "-line" also
		// ends "book-outline", and giving up there would skip "-outline".
		for _, suffix := range notionIconVariants {
			stem := strings.TrimSuffix(candidate, suffix)
			if stem == candidate {
				continue
			}
			if resolved, ok := notionIconNames[stem]; ok {
				return resolved, stem, true
			}
		}
		return "", "", false
	}

	for candidate := normalized; candidate != ""; {
		if resolved, key, ok := lookup(candidate); ok {
			return resolved, key, true
		}
		cut := strings.LastIndex(candidate, "-")
		if cut < 0 {
			break
		}
		candidate = candidate[:cut]
	}
	return "", "", false
}

// notionIconColors maps Notion's icon palette onto Anytype's ten icon options.
// Anytype has no plain green or brown, so those take the nearest neighbour.
// An unknown color must never cost the icon: grey is the fallback.
var notionIconColors = map[string]int64{
	"gray":       1,
	"grey":       1,
	"lightgray":  1,
	"light_gray": 1,
	"lightgrey":  1,
	"default":    1,
	"yellow":     2,
	"orange":     3,
	"brown":      3,
	"red":        4,
	"pink":       5,
	"purple":     6,
	"blue":       7,
	"green":      10,
}

const defaultIconOption int64 = 1

func notionIconOption(color string) int64 {
	if option, ok := notionIconColors[strings.ToLower(strings.TrimSpace(color))]; ok {
		return option
	}
	return defaultIconOption
}

// namedIcon resolves a Notion built-in icon to an Anytype icon name and color.
// Not-ok means "no named icon to apply": a different icon kind, or a name with
// no Anytype counterpart.
func (i *iconValue) namedIcon() (string, int64, bool) {
	if i == nil || i.Type != "icon" || i.Icon == nil || i.Icon.Name == "" {
		return "", 0, false
	}
	resolved, _, ok := resolveNotionIconName(i.Icon.Name)
	if !ok {
		return "", 0, false
	}
	return resolved, notionIconOption(i.Icon.Color), true
}

// applyDatabaseTypeIcon gives a database-backed type the database's own icon
// and returns whatever applyIcon must still materialize (nil when there is
// nothing left to do).
//
// The planner's icon is the fallback throughout: it is cleared only when
// something a type can actually show takes its place. The client renders a
// type's icon as image, then name, then emoji — so a planned name left in
// place would hide the database's own emoji, and clearing it for an icon we
// then fail to set leaves the type blank.
func applyDatabaseTypeIcon(details *domain.Details, icon *iconValue) *iconValue {
	if name, option, ok := icon.namedIcon(); ok {
		details.SetString(bundle.RelationKeyIconName, name)
		details.SetInt64(bundle.RelationKeyIconOption, option)
		return nil
	}
	if (icon.isEmoji() && icon.Emoji != "") || icon.fileUrl() != "" {
		details.Delete(bundle.RelationKeyIconName)
		details.Delete(bundle.RelationKeyIconOption)
		return icon
	}
	return nil
}
