/*
Code generated by pkg/lib/bundle/generator. DO NOT EDIT.
source: pkg/lib/bundle/internalRelations.json
*/
package bundle

import domain "github.com/anyproto/anytype-heart/core/domain"

const InternalRelationsChecksum = "fc0437ee1340e675cfa84a27a1f384592cd4996b404b41e1e20b3831a8238248"

// RequiredInternalRelations contains internal relations that will be added to EVERY new or existing object
// if this relation only needs SPECIFIC objects(e.g. of some type) add it to the SystemRelations
var RequiredInternalRelations = []domain.RelationKey{
	RelationKeyId,
	RelationKeyName,
	RelationKeyDescription,
	RelationKeyIconEmoji,
	RelationKeyIconImage,
	RelationKeyType,
	RelationKeyCreatedDate,
	RelationKeyCreator,
	RelationKeyLastModifiedDate,
	RelationKeyLastModifiedBy,
	RelationKeyLastOpenedDate,
	RelationKeyIsFavorite,
	RelationKeyIsArchived,
	RelationKeyWorkspaceId,
	RelationKeySpaceId,
	RelationKeyInternalFlags,
	RelationKeyRestrictions,
	RelationKeySyncDate,
	RelationKeySyncStatus,
	RelationKeyMyParticipantStatus,
	RelationKeySyncError,
}
