/*
Code generated by pkg/lib/bundle/generator. DO NOT EDIT.
source: pkg/lib/bundle/systemTypes.json
*/
package bundle

const SystemTypesChecksum = "30640d58789142cb9390541ea467bc706dad8ca23a2c03a3a402f6fb512d3f49"

// SystemTypes contains types that have some special biz logic depends on them in some objects
// they shouldn't be removed or edited in any way
var SystemTypes = append(InternalTypes, []TypeKey{
	TypeKeyPage,
	TypeKeyNote,
	TypeKeyTask,
	TypeKeyCollection,
	TypeKeyProfile,
	TypeKeyBookmark,
}...)
