// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new types API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new types API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new types API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for types API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetSpacesSpaceIDTypes(params *GetSpacesSpaceIDTypesParams, opts ...ClientOption) (*GetSpacesSpaceIDTypesOK, error)

	GetSpacesSpaceIDTypesTypeID(params *GetSpacesSpaceIDTypesTypeIDParams, opts ...ClientOption) (*GetSpacesSpaceIDTypesTypeIDOK, error)

	GetSpacesSpaceIDTypesTypeIDTemplates(params *GetSpacesSpaceIDTypesTypeIDTemplatesParams, opts ...ClientOption) (*GetSpacesSpaceIDTypesTypeIDTemplatesOK, error)

	GetSpacesSpaceIDTypesTypeIDTemplatesTemplateID(params *GetSpacesSpaceIDTypesTypeIDTemplatesTemplateIDParams, opts ...ClientOption) (*GetSpacesSpaceIDTypesTypeIDTemplatesTemplateIDOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GetSpacesSpaceIDTypes lists types
*/
func (a *Client) GetSpacesSpaceIDTypes(params *GetSpacesSpaceIDTypesParams, opts ...ClientOption) (*GetSpacesSpaceIDTypesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetSpacesSpaceIDTypesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetSpacesSpaceIDTypes",
		Method:             "GET",
		PathPattern:        "/spaces/{space_id}/types",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetSpacesSpaceIDTypesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetSpacesSpaceIDTypesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetSpacesSpaceIDTypes: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetSpacesSpaceIDTypesTypeID gets type
*/
func (a *Client) GetSpacesSpaceIDTypesTypeID(params *GetSpacesSpaceIDTypesTypeIDParams, opts ...ClientOption) (*GetSpacesSpaceIDTypesTypeIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetSpacesSpaceIDTypesTypeIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetSpacesSpaceIDTypesTypeID",
		Method:             "GET",
		PathPattern:        "/spaces/{space_id}/types/{type_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetSpacesSpaceIDTypesTypeIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetSpacesSpaceIDTypesTypeIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetSpacesSpaceIDTypesTypeID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetSpacesSpaceIDTypesTypeIDTemplates lists templates
*/
func (a *Client) GetSpacesSpaceIDTypesTypeIDTemplates(params *GetSpacesSpaceIDTypesTypeIDTemplatesParams, opts ...ClientOption) (*GetSpacesSpaceIDTypesTypeIDTemplatesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetSpacesSpaceIDTypesTypeIDTemplatesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetSpacesSpaceIDTypesTypeIDTemplates",
		Method:             "GET",
		PathPattern:        "/spaces/{space_id}/types/{type_id}/templates",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetSpacesSpaceIDTypesTypeIDTemplatesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetSpacesSpaceIDTypesTypeIDTemplatesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetSpacesSpaceIDTypesTypeIDTemplates: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetSpacesSpaceIDTypesTypeIDTemplatesTemplateID gets template
*/
func (a *Client) GetSpacesSpaceIDTypesTypeIDTemplatesTemplateID(params *GetSpacesSpaceIDTypesTypeIDTemplatesTemplateIDParams, opts ...ClientOption) (*GetSpacesSpaceIDTypesTypeIDTemplatesTemplateIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetSpacesSpaceIDTypesTypeIDTemplatesTemplateIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetSpacesSpaceIDTypesTypeIDTemplatesTemplateID",
		Method:             "GET",
		PathPattern:        "/spaces/{space_id}/types/{type_id}/templates/{template_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetSpacesSpaceIDTypesTypeIDTemplatesTemplateIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetSpacesSpaceIDTypesTypeIDTemplatesTemplateIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetSpacesSpaceIDTypesTypeIDTemplatesTemplateID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
