// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UtilUnauthorizedError util unauthorized error
//
// swagger:model util.UnauthorizedError
type UtilUnauthorizedError struct {

	// error
	Error *UtilUnauthorizedErrorError `json:"error,omitempty"`
}

// Validate validates this util unauthorized error
func (m *UtilUnauthorizedError) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UtilUnauthorizedError) validateError(formats strfmt.Registry) error {
	if swag.IsZero(m.Error) { // not required
		return nil
	}

	if m.Error != nil {
		if err := m.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("error")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this util unauthorized error based on the context it is used
func (m *UtilUnauthorizedError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateError(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UtilUnauthorizedError) contextValidateError(ctx context.Context, formats strfmt.Registry) error {

	if m.Error != nil {

		if swag.IsZero(m.Error) { // not required
			return nil
		}

		if err := m.Error.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("error")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UtilUnauthorizedError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UtilUnauthorizedError) UnmarshalBinary(b []byte) error {
	var res UtilUnauthorizedError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// UtilUnauthorizedErrorError util unauthorized error error
//
// swagger:model UtilUnauthorizedErrorError
type UtilUnauthorizedErrorError struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this util unauthorized error error
func (m *UtilUnauthorizedErrorError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this util unauthorized error error based on context it is used
func (m *UtilUnauthorizedErrorError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UtilUnauthorizedErrorError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UtilUnauthorizedErrorError) UnmarshalBinary(b []byte) error {
	var res UtilUnauthorizedErrorError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
