FROM alpine:3.13

RUN apk add --no-cache \
        wget \
        openssl \
        ca-certificates \
        libc6-compat \
        libstdc++

COPY ./dist/server /bin/server
COPY .circleci/testdata /testdata

ENTRYPOINT ["/bin/server"]