package time

var Abbreviations = map[string]string {
	"GMT": "Etc/GMT",
	"ECT": "Europe/Budapest",
	//"EET": "",
	//"EAT": "",
	//"MET": "",
	//"NET": "",
	//"PLT": "",
	//"IST": "",
	//"BST": "",
	//"VST": "",
	//"CTT": "",
	//"JST": "",
	//"ACT": "",
	//"AET": "",
	//"SST": "",
	//"NST": "",
	//"MIT": "",
	//"HST": "",
	//"AST": "",
	//"PST": "",
	//"MST": "",
	//"CST": "",
	//"IET": "",
	//"PRT": "",
	//"CNT": "",
	//"BET": "",
	//"BRT": "",
	//"CAT": "",
}
