// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pkg/lib/pb/model/protos/localstore.proto

package model

import (
	fmt "fmt"
	relation "github.com/anytypeio/go-anytype-middleware/pkg/lib/pb/relation"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ObjectInfo struct {
	Id              string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ObjectTypeUrls  []string            `protobuf:"bytes,2,rep,name=objectTypeUrls,proto3" json:"objectTypeUrls,omitempty"`
	Details         *types.Struct       `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	Relations       *relation.Relations `protobuf:"bytes,4,opt,name=relations,proto3" json:"relations,omitempty"`
	Snippet         string              `protobuf:"bytes,5,opt,name=snippet,proto3" json:"snippet,omitempty"`
	HasInboundLinks bool                `protobuf:"varint,6,opt,name=hasInboundLinks,proto3" json:"hasInboundLinks,omitempty"`
	ObjectType      SmartBlockType      `protobuf:"varint,7,opt,name=objectType,proto3,enum=anytype.model.SmartBlockType" json:"objectType,omitempty"`
}

func (m *ObjectInfo) Reset()         { *m = ObjectInfo{} }
func (m *ObjectInfo) String() string { return proto.CompactTextString(m) }
func (*ObjectInfo) ProtoMessage()    {}
func (*ObjectInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c35df71910469a5, []int{0}
}
func (m *ObjectInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ObjectInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ObjectInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ObjectInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectInfo.Merge(m, src)
}
func (m *ObjectInfo) XXX_Size() int {
	return m.Size()
}
func (m *ObjectInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectInfo proto.InternalMessageInfo

func (m *ObjectInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ObjectInfo) GetObjectTypeUrls() []string {
	if m != nil {
		return m.ObjectTypeUrls
	}
	return nil
}

func (m *ObjectInfo) GetDetails() *types.Struct {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *ObjectInfo) GetRelations() *relation.Relations {
	if m != nil {
		return m.Relations
	}
	return nil
}

func (m *ObjectInfo) GetSnippet() string {
	if m != nil {
		return m.Snippet
	}
	return ""
}

func (m *ObjectInfo) GetHasInboundLinks() bool {
	if m != nil {
		return m.HasInboundLinks
	}
	return false
}

func (m *ObjectInfo) GetObjectType() SmartBlockType {
	if m != nil {
		return m.ObjectType
	}
	return SmartBlockType_Breadcrumbs
}

type ObjectDetails struct {
	Details *types.Struct `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
}

func (m *ObjectDetails) Reset()         { *m = ObjectDetails{} }
func (m *ObjectDetails) String() string { return proto.CompactTextString(m) }
func (*ObjectDetails) ProtoMessage()    {}
func (*ObjectDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c35df71910469a5, []int{1}
}
func (m *ObjectDetails) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ObjectDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ObjectDetails.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ObjectDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectDetails.Merge(m, src)
}
func (m *ObjectDetails) XXX_Size() int {
	return m.Size()
}
func (m *ObjectDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectDetails.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectDetails proto.InternalMessageInfo

func (m *ObjectDetails) GetDetails() *types.Struct {
	if m != nil {
		return m.Details
	}
	return nil
}

type ObjectLinks struct {
	InboundIDs  []string `protobuf:"bytes,1,rep,name=inboundIDs,proto3" json:"inboundIDs,omitempty"`
	OutboundIDs []string `protobuf:"bytes,2,rep,name=outboundIDs,proto3" json:"outboundIDs,omitempty"`
}

func (m *ObjectLinks) Reset()         { *m = ObjectLinks{} }
func (m *ObjectLinks) String() string { return proto.CompactTextString(m) }
func (*ObjectLinks) ProtoMessage()    {}
func (*ObjectLinks) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c35df71910469a5, []int{2}
}
func (m *ObjectLinks) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ObjectLinks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ObjectLinks.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ObjectLinks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectLinks.Merge(m, src)
}
func (m *ObjectLinks) XXX_Size() int {
	return m.Size()
}
func (m *ObjectLinks) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectLinks.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectLinks proto.InternalMessageInfo

func (m *ObjectLinks) GetInboundIDs() []string {
	if m != nil {
		return m.InboundIDs
	}
	return nil
}

func (m *ObjectLinks) GetOutboundIDs() []string {
	if m != nil {
		return m.OutboundIDs
	}
	return nil
}

type ObjectLinksInfo struct {
	Inbound  []*ObjectInfo `protobuf:"bytes,1,rep,name=inbound,proto3" json:"inbound,omitempty"`
	Outbound []*ObjectInfo `protobuf:"bytes,2,rep,name=outbound,proto3" json:"outbound,omitempty"`
}

func (m *ObjectLinksInfo) Reset()         { *m = ObjectLinksInfo{} }
func (m *ObjectLinksInfo) String() string { return proto.CompactTextString(m) }
func (*ObjectLinksInfo) ProtoMessage()    {}
func (*ObjectLinksInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c35df71910469a5, []int{3}
}
func (m *ObjectLinksInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ObjectLinksInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ObjectLinksInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ObjectLinksInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectLinksInfo.Merge(m, src)
}
func (m *ObjectLinksInfo) XXX_Size() int {
	return m.Size()
}
func (m *ObjectLinksInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectLinksInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectLinksInfo proto.InternalMessageInfo

func (m *ObjectLinksInfo) GetInbound() []*ObjectInfo {
	if m != nil {
		return m.Inbound
	}
	return nil
}

func (m *ObjectLinksInfo) GetOutbound() []*ObjectInfo {
	if m != nil {
		return m.Outbound
	}
	return nil
}

type ObjectInfoWithLinks struct {
	Id    string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Info  *ObjectInfo      `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Links *ObjectLinksInfo `protobuf:"bytes,3,opt,name=links,proto3" json:"links,omitempty"`
}

func (m *ObjectInfoWithLinks) Reset()         { *m = ObjectInfoWithLinks{} }
func (m *ObjectInfoWithLinks) String() string { return proto.CompactTextString(m) }
func (*ObjectInfoWithLinks) ProtoMessage()    {}
func (*ObjectInfoWithLinks) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c35df71910469a5, []int{4}
}
func (m *ObjectInfoWithLinks) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ObjectInfoWithLinks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ObjectInfoWithLinks.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ObjectInfoWithLinks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectInfoWithLinks.Merge(m, src)
}
func (m *ObjectInfoWithLinks) XXX_Size() int {
	return m.Size()
}
func (m *ObjectInfoWithLinks) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectInfoWithLinks.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectInfoWithLinks proto.InternalMessageInfo

func (m *ObjectInfoWithLinks) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ObjectInfoWithLinks) GetInfo() *ObjectInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ObjectInfoWithLinks) GetLinks() *ObjectLinksInfo {
	if m != nil {
		return m.Links
	}
	return nil
}

type ObjectInfoWithOutboundLinks struct {
	Id            string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Info          *ObjectInfo   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	OutboundLinks []*ObjectInfo `protobuf:"bytes,3,rep,name=outboundLinks,proto3" json:"outboundLinks,omitempty"`
}

func (m *ObjectInfoWithOutboundLinks) Reset()         { *m = ObjectInfoWithOutboundLinks{} }
func (m *ObjectInfoWithOutboundLinks) String() string { return proto.CompactTextString(m) }
func (*ObjectInfoWithOutboundLinks) ProtoMessage()    {}
func (*ObjectInfoWithOutboundLinks) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c35df71910469a5, []int{5}
}
func (m *ObjectInfoWithOutboundLinks) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ObjectInfoWithOutboundLinks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ObjectInfoWithOutboundLinks.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ObjectInfoWithOutboundLinks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectInfoWithOutboundLinks.Merge(m, src)
}
func (m *ObjectInfoWithOutboundLinks) XXX_Size() int {
	return m.Size()
}
func (m *ObjectInfoWithOutboundLinks) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectInfoWithOutboundLinks.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectInfoWithOutboundLinks proto.InternalMessageInfo

func (m *ObjectInfoWithOutboundLinks) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ObjectInfoWithOutboundLinks) GetInfo() *ObjectInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ObjectInfoWithOutboundLinks) GetOutboundLinks() []*ObjectInfo {
	if m != nil {
		return m.OutboundLinks
	}
	return nil
}

type ObjectInfoWithOutboundLinksIDs struct {
	Id            string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Info          *ObjectInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	OutboundLinks []string    `protobuf:"bytes,3,rep,name=outboundLinks,proto3" json:"outboundLinks,omitempty"`
}

func (m *ObjectInfoWithOutboundLinksIDs) Reset()         { *m = ObjectInfoWithOutboundLinksIDs{} }
func (m *ObjectInfoWithOutboundLinksIDs) String() string { return proto.CompactTextString(m) }
func (*ObjectInfoWithOutboundLinksIDs) ProtoMessage()    {}
func (*ObjectInfoWithOutboundLinksIDs) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c35df71910469a5, []int{6}
}
func (m *ObjectInfoWithOutboundLinksIDs) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ObjectInfoWithOutboundLinksIDs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ObjectInfoWithOutboundLinksIDs.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ObjectInfoWithOutboundLinksIDs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectInfoWithOutboundLinksIDs.Merge(m, src)
}
func (m *ObjectInfoWithOutboundLinksIDs) XXX_Size() int {
	return m.Size()
}
func (m *ObjectInfoWithOutboundLinksIDs) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectInfoWithOutboundLinksIDs.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectInfoWithOutboundLinksIDs proto.InternalMessageInfo

func (m *ObjectInfoWithOutboundLinksIDs) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ObjectInfoWithOutboundLinksIDs) GetInfo() *ObjectInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ObjectInfoWithOutboundLinksIDs) GetOutboundLinks() []string {
	if m != nil {
		return m.OutboundLinks
	}
	return nil
}

type ObjectStoreChecksums struct {
	BundledObjectTypes         string `protobuf:"bytes,1,opt,name=bundledObjectTypes,proto3" json:"bundledObjectTypes,omitempty"`
	BundledRelations           string `protobuf:"bytes,2,opt,name=bundledRelations,proto3" json:"bundledRelations,omitempty"`
	BundledLayouts             string `protobuf:"bytes,3,opt,name=bundledLayouts,proto3" json:"bundledLayouts,omitempty"`
	ObjectsForceReindexCounter int32  `protobuf:"varint,4,opt,name=objectsForceReindexCounter,proto3" json:"objectsForceReindexCounter,omitempty"`
	FilesForceReindexCounter   int32  `protobuf:"varint,5,opt,name=filesForceReindexCounter,proto3" json:"filesForceReindexCounter,omitempty"`
	IdxRebuildCounter          int32  `protobuf:"varint,6,opt,name=idxRebuildCounter,proto3" json:"idxRebuildCounter,omitempty"`
	FulltextRebuild            int32  `protobuf:"varint,7,opt,name=fulltextRebuild,proto3" json:"fulltextRebuild,omitempty"`
}

func (m *ObjectStoreChecksums) Reset()         { *m = ObjectStoreChecksums{} }
func (m *ObjectStoreChecksums) String() string { return proto.CompactTextString(m) }
func (*ObjectStoreChecksums) ProtoMessage()    {}
func (*ObjectStoreChecksums) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c35df71910469a5, []int{7}
}
func (m *ObjectStoreChecksums) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ObjectStoreChecksums) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ObjectStoreChecksums.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ObjectStoreChecksums) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectStoreChecksums.Merge(m, src)
}
func (m *ObjectStoreChecksums) XXX_Size() int {
	return m.Size()
}
func (m *ObjectStoreChecksums) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectStoreChecksums.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectStoreChecksums proto.InternalMessageInfo

func (m *ObjectStoreChecksums) GetBundledObjectTypes() string {
	if m != nil {
		return m.BundledObjectTypes
	}
	return ""
}

func (m *ObjectStoreChecksums) GetBundledRelations() string {
	if m != nil {
		return m.BundledRelations
	}
	return ""
}

func (m *ObjectStoreChecksums) GetBundledLayouts() string {
	if m != nil {
		return m.BundledLayouts
	}
	return ""
}

func (m *ObjectStoreChecksums) GetObjectsForceReindexCounter() int32 {
	if m != nil {
		return m.ObjectsForceReindexCounter
	}
	return 0
}

func (m *ObjectStoreChecksums) GetFilesForceReindexCounter() int32 {
	if m != nil {
		return m.FilesForceReindexCounter
	}
	return 0
}

func (m *ObjectStoreChecksums) GetIdxRebuildCounter() int32 {
	if m != nil {
		return m.IdxRebuildCounter
	}
	return 0
}

func (m *ObjectStoreChecksums) GetFulltextRebuild() int32 {
	if m != nil {
		return m.FulltextRebuild
	}
	return 0
}

func init() {
	proto.RegisterType((*ObjectInfo)(nil), "anytype.model.ObjectInfo")
	proto.RegisterType((*ObjectDetails)(nil), "anytype.model.ObjectDetails")
	proto.RegisterType((*ObjectLinks)(nil), "anytype.model.ObjectLinks")
	proto.RegisterType((*ObjectLinksInfo)(nil), "anytype.model.ObjectLinksInfo")
	proto.RegisterType((*ObjectInfoWithLinks)(nil), "anytype.model.ObjectInfoWithLinks")
	proto.RegisterType((*ObjectInfoWithOutboundLinks)(nil), "anytype.model.ObjectInfoWithOutboundLinks")
	proto.RegisterType((*ObjectInfoWithOutboundLinksIDs)(nil), "anytype.model.ObjectInfoWithOutboundLinksIDs")
	proto.RegisterType((*ObjectStoreChecksums)(nil), "anytype.model.ObjectStoreChecksums")
}

func init() {
	proto.RegisterFile("pkg/lib/pb/model/protos/localstore.proto", fileDescriptor_9c35df71910469a5)
}

var fileDescriptor_9c35df71910469a5 = []byte{
	// 652 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xed, 0xa6, 0x4d, 0xd3, 0x4c, 0xd4, 0x0f, 0x16, 0x24, 0x4c, 0x0b, 0x56, 0x64, 0x55, 0xc8,
	0x54, 0xe0, 0x88, 0x16, 0x0e, 0x20, 0x01, 0x52, 0x5b, 0x21, 0x55, 0xaa, 0x14, 0x69, 0x0b, 0x42,
	0xe2, 0x66, 0xc7, 0x9b, 0x76, 0xc9, 0xd6, 0x6b, 0x79, 0xd7, 0x52, 0x73, 0xe0, 0xc8, 0x85, 0x13,
	0x7f, 0x80, 0x9f, 0xc1, 0x7f, 0xe0, 0xd8, 0x23, 0x47, 0xd4, 0xde, 0xf9, 0x0d, 0xc8, 0xbb, 0x76,
	0xe2, 0xb8, 0x69, 0x40, 0x82, 0xa3, 0xdf, 0xbc, 0x79, 0x79, 0x6f, 0x66, 0x33, 0xe0, 0xc6, 0x83,
	0xe3, 0x0e, 0x67, 0x41, 0x27, 0x0e, 0x3a, 0xa7, 0x22, 0xa4, 0xbc, 0x13, 0x27, 0x42, 0x09, 0xd9,
	0xe1, 0xa2, 0xe7, 0x73, 0xa9, 0x44, 0x42, 0x3d, 0x8d, 0xe0, 0x65, 0x3f, 0x1a, 0xaa, 0x61, 0x4c,
	0x3d, 0x4d, 0x5b, 0xbf, 0x7b, 0x2c, 0xc4, 0x31, 0xa7, 0x86, 0x1e, 0xa4, 0xfd, 0x8e, 0x54, 0x49,
	0xda, 0x53, 0x86, 0xbc, 0xfe, 0xa0, 0x24, 0x9b, 0x50, 0xee, 0x2b, 0x26, 0xa2, 0x42, 0xb9, 0xf8,
	0xce, 0xa9, 0x9b, 0xd7, 0x39, 0xd0, 0x1f, 0xd2, 0xb0, 0x9c, 0x6f, 0x35, 0x80, 0x6e, 0xf0, 0x81,
	0xf6, 0xd4, 0x41, 0xd4, 0x17, 0x78, 0x05, 0x6a, 0x2c, 0xb4, 0x50, 0x1b, 0xb9, 0x4d, 0x52, 0x63,
	0x21, 0xbe, 0x0f, 0x2b, 0x42, 0x57, 0xdf, 0x0c, 0x63, 0xfa, 0x36, 0xe1, 0xd2, 0xaa, 0xb5, 0xe7,
	0xdd, 0x26, 0xa9, 0xa0, 0xf8, 0x31, 0x34, 0x42, 0xaa, 0x7c, 0xc6, 0xa5, 0x35, 0xdf, 0x46, 0x6e,
	0x6b, 0xfb, 0xb6, 0x67, 0x72, 0x78, 0x45, 0x0e, 0xef, 0x48, 0xe7, 0x20, 0x05, 0x0f, 0x3f, 0x83,
	0x66, 0xe1, 0x58, 0x5a, 0x0b, 0xba, 0x69, 0xc3, 0x2b, 0x66, 0x31, 0xca, 0x42, 0x0a, 0x0a, 0x19,
	0xb3, 0xb1, 0x05, 0x0d, 0x19, 0xb1, 0x38, 0xa6, 0xca, 0xaa, 0x6b, 0xab, 0xc5, 0x27, 0x76, 0x61,
	0xf5, 0xc4, 0x97, 0x07, 0x51, 0x20, 0xd2, 0x28, 0x3c, 0x64, 0xd1, 0x40, 0x5a, 0x8b, 0x6d, 0xe4,
	0x2e, 0x91, 0x2a, 0x8c, 0x5f, 0x00, 0x8c, 0x33, 0x58, 0x8d, 0x36, 0x72, 0x57, 0xb6, 0xef, 0x79,
	0x13, 0xbb, 0xf0, 0x8e, 0x4e, 0xfd, 0x44, 0xed, 0x72, 0xd1, 0x1b, 0x64, 0x24, 0x52, 0x6a, 0x70,
	0x76, 0x61, 0xd9, 0x8c, 0x6d, 0x3f, 0x8f, 0x53, 0x9a, 0x00, 0xfa, 0xbb, 0x09, 0x38, 0x5d, 0x68,
	0x19, 0x0d, 0xe3, 0xc8, 0x06, 0x60, 0xc6, 0xe1, 0xc1, 0x7e, 0x26, 0x92, 0xcd, 0xb9, 0x84, 0xe0,
	0x36, 0xb4, 0x44, 0xaa, 0x46, 0x04, 0xb3, 0x88, 0x32, 0xe4, 0x7c, 0x84, 0xd5, 0x92, 0xa0, 0x5e,
	0xe8, 0x0e, 0x34, 0x72, 0x09, 0xad, 0xd8, 0xda, 0xbe, 0x53, 0xc9, 0x38, 0x5e, 0x3e, 0x29, 0x98,
	0xf8, 0x29, 0x2c, 0x15, 0xb2, 0xfa, 0x67, 0x66, 0x76, 0x8d, 0xa8, 0xce, 0x67, 0x04, 0x37, 0xc7,
	0x85, 0x77, 0x4c, 0x9d, 0x98, 0x60, 0xd5, 0x47, 0xf5, 0x08, 0x16, 0x58, 0xd4, 0x17, 0x56, 0x4d,
	0xcf, 0x69, 0x86, 0xb4, 0xa6, 0xe1, 0x27, 0x50, 0xe7, 0x7a, 0x93, 0xe6, 0x65, 0xd9, 0x53, 0xf9,
	0xa3, 0xc4, 0xc4, 0x90, 0x9d, 0xaf, 0x08, 0x36, 0x26, 0xcd, 0x74, 0x73, 0x9f, 0xff, 0xc5, 0xd4,
	0x2b, 0x58, 0x16, 0x65, 0x3d, 0x6b, 0xfe, 0x4f, 0x73, 0x9a, 0xe4, 0x3b, 0x9f, 0x10, 0xd8, 0x33,
	0xfc, 0x65, 0x0b, 0xff, 0x47, 0x8b, 0x9b, 0xd3, 0x2c, 0x36, 0xab, 0x3e, 0x7e, 0xd5, 0xe0, 0x96,
	0x69, 0x3d, 0xca, 0x8e, 0xd2, 0xde, 0x09, 0xed, 0x0d, 0x64, 0x7a, 0x2a, 0xb1, 0x07, 0x38, 0x48,
	0xa3, 0x90, 0xd3, 0xb0, 0x3b, 0x7a, 0xf6, 0x32, 0x77, 0x33, 0xa5, 0x82, 0xb7, 0x60, 0x2d, 0x47,
	0x47, 0xff, 0x59, 0xed, 0xb4, 0x49, 0xae, 0xe0, 0xd9, 0x59, 0xc9, 0xb1, 0x43, 0x7f, 0x28, 0x52,
	0x65, 0x76, 0xdb, 0x24, 0x15, 0x14, 0xbf, 0x84, 0x75, 0xf3, 0x9f, 0x93, 0xaf, 0x45, 0xd2, 0xa3,
	0x84, 0xb2, 0x28, 0xa4, 0x67, 0x7b, 0x22, 0x8d, 0x14, 0x4d, 0xf4, 0xd1, 0xa8, 0x93, 0x19, 0x0c,
	0xfc, 0x1c, 0xac, 0x3e, 0xe3, 0x74, 0x6a, 0x77, 0x5d, 0x77, 0x5f, 0x5b, 0xc7, 0x0f, 0xe1, 0x06,
	0x0b, 0xcf, 0x08, 0x0d, 0x52, 0xc6, 0xc3, 0xa2, 0x69, 0x51, 0x37, 0x5d, 0x2d, 0x64, 0x87, 0xa7,
	0x9f, 0x72, 0xae, 0xe8, 0x99, 0xca, 0x2b, 0xfa, 0xa6, 0xd4, 0x49, 0x15, 0xde, 0xdd, 0xfa, 0x7e,
	0x61, 0xa3, 0xf3, 0x0b, 0x1b, 0xfd, 0xbc, 0xb0, 0xd1, 0x97, 0x4b, 0x7b, 0xee, 0xfc, 0xd2, 0x9e,
	0xfb, 0x71, 0x69, 0xcf, 0xbd, 0x5f, 0xab, 0x5e, 0xec, 0x60, 0x51, 0xdf, 0x8e, 0x9d, 0xdf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xd6, 0xab, 0x1e, 0x2a, 0x4e, 0x06, 0x00, 0x00,
}

func (m *ObjectInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ObjectInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ObjectInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ObjectType != 0 {
		i = encodeVarintLocalstore(dAtA, i, uint64(m.ObjectType))
		i--
		dAtA[i] = 0x38
	}
	if m.HasInboundLinks {
		i--
		if m.HasInboundLinks {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if len(m.Snippet) > 0 {
		i -= len(m.Snippet)
		copy(dAtA[i:], m.Snippet)
		i = encodeVarintLocalstore(dAtA, i, uint64(len(m.Snippet)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Relations != nil {
		{
			size, err := m.Relations.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLocalstore(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.Details != nil {
		{
			size, err := m.Details.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLocalstore(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ObjectTypeUrls) > 0 {
		for iNdEx := len(m.ObjectTypeUrls) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ObjectTypeUrls[iNdEx])
			copy(dAtA[i:], m.ObjectTypeUrls[iNdEx])
			i = encodeVarintLocalstore(dAtA, i, uint64(len(m.ObjectTypeUrls[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintLocalstore(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ObjectDetails) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ObjectDetails) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ObjectDetails) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Details != nil {
		{
			size, err := m.Details.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLocalstore(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ObjectLinks) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ObjectLinks) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ObjectLinks) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OutboundIDs) > 0 {
		for iNdEx := len(m.OutboundIDs) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.OutboundIDs[iNdEx])
			copy(dAtA[i:], m.OutboundIDs[iNdEx])
			i = encodeVarintLocalstore(dAtA, i, uint64(len(m.OutboundIDs[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.InboundIDs) > 0 {
		for iNdEx := len(m.InboundIDs) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.InboundIDs[iNdEx])
			copy(dAtA[i:], m.InboundIDs[iNdEx])
			i = encodeVarintLocalstore(dAtA, i, uint64(len(m.InboundIDs[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ObjectLinksInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ObjectLinksInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ObjectLinksInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Outbound) > 0 {
		for iNdEx := len(m.Outbound) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Outbound[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintLocalstore(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Inbound) > 0 {
		for iNdEx := len(m.Inbound) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Inbound[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintLocalstore(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ObjectInfoWithLinks) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ObjectInfoWithLinks) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ObjectInfoWithLinks) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Links != nil {
		{
			size, err := m.Links.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLocalstore(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Info != nil {
		{
			size, err := m.Info.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLocalstore(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintLocalstore(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ObjectInfoWithOutboundLinks) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ObjectInfoWithOutboundLinks) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ObjectInfoWithOutboundLinks) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OutboundLinks) > 0 {
		for iNdEx := len(m.OutboundLinks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OutboundLinks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintLocalstore(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.Info != nil {
		{
			size, err := m.Info.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLocalstore(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintLocalstore(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ObjectInfoWithOutboundLinksIDs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ObjectInfoWithOutboundLinksIDs) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ObjectInfoWithOutboundLinksIDs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OutboundLinks) > 0 {
		for iNdEx := len(m.OutboundLinks) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.OutboundLinks[iNdEx])
			copy(dAtA[i:], m.OutboundLinks[iNdEx])
			i = encodeVarintLocalstore(dAtA, i, uint64(len(m.OutboundLinks[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.Info != nil {
		{
			size, err := m.Info.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLocalstore(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintLocalstore(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ObjectStoreChecksums) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ObjectStoreChecksums) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ObjectStoreChecksums) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FulltextRebuild != 0 {
		i = encodeVarintLocalstore(dAtA, i, uint64(m.FulltextRebuild))
		i--
		dAtA[i] = 0x38
	}
	if m.IdxRebuildCounter != 0 {
		i = encodeVarintLocalstore(dAtA, i, uint64(m.IdxRebuildCounter))
		i--
		dAtA[i] = 0x30
	}
	if m.FilesForceReindexCounter != 0 {
		i = encodeVarintLocalstore(dAtA, i, uint64(m.FilesForceReindexCounter))
		i--
		dAtA[i] = 0x28
	}
	if m.ObjectsForceReindexCounter != 0 {
		i = encodeVarintLocalstore(dAtA, i, uint64(m.ObjectsForceReindexCounter))
		i--
		dAtA[i] = 0x20
	}
	if len(m.BundledLayouts) > 0 {
		i -= len(m.BundledLayouts)
		copy(dAtA[i:], m.BundledLayouts)
		i = encodeVarintLocalstore(dAtA, i, uint64(len(m.BundledLayouts)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.BundledRelations) > 0 {
		i -= len(m.BundledRelations)
		copy(dAtA[i:], m.BundledRelations)
		i = encodeVarintLocalstore(dAtA, i, uint64(len(m.BundledRelations)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.BundledObjectTypes) > 0 {
		i -= len(m.BundledObjectTypes)
		copy(dAtA[i:], m.BundledObjectTypes)
		i = encodeVarintLocalstore(dAtA, i, uint64(len(m.BundledObjectTypes)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintLocalstore(dAtA []byte, offset int, v uint64) int {
	offset -= sovLocalstore(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ObjectInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovLocalstore(uint64(l))
	}
	if len(m.ObjectTypeUrls) > 0 {
		for _, s := range m.ObjectTypeUrls {
			l = len(s)
			n += 1 + l + sovLocalstore(uint64(l))
		}
	}
	if m.Details != nil {
		l = m.Details.Size()
		n += 1 + l + sovLocalstore(uint64(l))
	}
	if m.Relations != nil {
		l = m.Relations.Size()
		n += 1 + l + sovLocalstore(uint64(l))
	}
	l = len(m.Snippet)
	if l > 0 {
		n += 1 + l + sovLocalstore(uint64(l))
	}
	if m.HasInboundLinks {
		n += 2
	}
	if m.ObjectType != 0 {
		n += 1 + sovLocalstore(uint64(m.ObjectType))
	}
	return n
}

func (m *ObjectDetails) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Details != nil {
		l = m.Details.Size()
		n += 1 + l + sovLocalstore(uint64(l))
	}
	return n
}

func (m *ObjectLinks) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.InboundIDs) > 0 {
		for _, s := range m.InboundIDs {
			l = len(s)
			n += 1 + l + sovLocalstore(uint64(l))
		}
	}
	if len(m.OutboundIDs) > 0 {
		for _, s := range m.OutboundIDs {
			l = len(s)
			n += 1 + l + sovLocalstore(uint64(l))
		}
	}
	return n
}

func (m *ObjectLinksInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Inbound) > 0 {
		for _, e := range m.Inbound {
			l = e.Size()
			n += 1 + l + sovLocalstore(uint64(l))
		}
	}
	if len(m.Outbound) > 0 {
		for _, e := range m.Outbound {
			l = e.Size()
			n += 1 + l + sovLocalstore(uint64(l))
		}
	}
	return n
}

func (m *ObjectInfoWithLinks) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovLocalstore(uint64(l))
	}
	if m.Info != nil {
		l = m.Info.Size()
		n += 1 + l + sovLocalstore(uint64(l))
	}
	if m.Links != nil {
		l = m.Links.Size()
		n += 1 + l + sovLocalstore(uint64(l))
	}
	return n
}

func (m *ObjectInfoWithOutboundLinks) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovLocalstore(uint64(l))
	}
	if m.Info != nil {
		l = m.Info.Size()
		n += 1 + l + sovLocalstore(uint64(l))
	}
	if len(m.OutboundLinks) > 0 {
		for _, e := range m.OutboundLinks {
			l = e.Size()
			n += 1 + l + sovLocalstore(uint64(l))
		}
	}
	return n
}

func (m *ObjectInfoWithOutboundLinksIDs) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovLocalstore(uint64(l))
	}
	if m.Info != nil {
		l = m.Info.Size()
		n += 1 + l + sovLocalstore(uint64(l))
	}
	if len(m.OutboundLinks) > 0 {
		for _, s := range m.OutboundLinks {
			l = len(s)
			n += 1 + l + sovLocalstore(uint64(l))
		}
	}
	return n
}

func (m *ObjectStoreChecksums) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BundledObjectTypes)
	if l > 0 {
		n += 1 + l + sovLocalstore(uint64(l))
	}
	l = len(m.BundledRelations)
	if l > 0 {
		n += 1 + l + sovLocalstore(uint64(l))
	}
	l = len(m.BundledLayouts)
	if l > 0 {
		n += 1 + l + sovLocalstore(uint64(l))
	}
	if m.ObjectsForceReindexCounter != 0 {
		n += 1 + sovLocalstore(uint64(m.ObjectsForceReindexCounter))
	}
	if m.FilesForceReindexCounter != 0 {
		n += 1 + sovLocalstore(uint64(m.FilesForceReindexCounter))
	}
	if m.IdxRebuildCounter != 0 {
		n += 1 + sovLocalstore(uint64(m.IdxRebuildCounter))
	}
	if m.FulltextRebuild != 0 {
		n += 1 + sovLocalstore(uint64(m.FulltextRebuild))
	}
	return n
}

func sovLocalstore(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLocalstore(x uint64) (n int) {
	return sovLocalstore(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ObjectInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLocalstore
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ObjectInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ObjectInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocalstore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLocalstore
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLocalstore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectTypeUrls", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocalstore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLocalstore
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLocalstore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ObjectTypeUrls = append(m.ObjectTypeUrls, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Details", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocalstore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLocalstore
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLocalstore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Details == nil {
				m.Details = &types.Struct{}
			}
			if err := m.Details.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Relations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocalstore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLocalstore
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLocalstore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Relations == nil {
				m.Relations = &relation.Relations{}
			}
			if err := m.Relations.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Snippet", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocalstore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLocalstore
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLocalstore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Snippet = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HasInboundLinks", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocalstore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.HasInboundLinks = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectType", wireType)
			}
			m.ObjectType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocalstore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ObjectType |= SmartBlockType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLocalstore(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLocalstore
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ObjectDetails) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLocalstore
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ObjectDetails: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ObjectDetails: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Details", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocalstore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLocalstore
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLocalstore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Details == nil {
				m.Details = &types.Struct{}
			}
			if err := m.Details.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLocalstore(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLocalstore
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ObjectLinks) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLocalstore
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ObjectLinks: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ObjectLinks: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InboundIDs", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocalstore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLocalstore
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLocalstore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InboundIDs = append(m.InboundIDs, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutboundIDs", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocalstore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLocalstore
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLocalstore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OutboundIDs = append(m.OutboundIDs, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLocalstore(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLocalstore
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ObjectLinksInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLocalstore
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ObjectLinksInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ObjectLinksInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inbound", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocalstore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLocalstore
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLocalstore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Inbound = append(m.Inbound, &ObjectInfo{})
			if err := m.Inbound[len(m.Inbound)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Outbound", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocalstore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLocalstore
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLocalstore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Outbound = append(m.Outbound, &ObjectInfo{})
			if err := m.Outbound[len(m.Outbound)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLocalstore(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLocalstore
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ObjectInfoWithLinks) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLocalstore
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ObjectInfoWithLinks: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ObjectInfoWithLinks: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocalstore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLocalstore
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLocalstore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Info", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocalstore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLocalstore
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLocalstore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Info == nil {
				m.Info = &ObjectInfo{}
			}
			if err := m.Info.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Links", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocalstore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLocalstore
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLocalstore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Links == nil {
				m.Links = &ObjectLinksInfo{}
			}
			if err := m.Links.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLocalstore(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLocalstore
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ObjectInfoWithOutboundLinks) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLocalstore
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ObjectInfoWithOutboundLinks: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ObjectInfoWithOutboundLinks: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocalstore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLocalstore
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLocalstore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Info", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocalstore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLocalstore
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLocalstore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Info == nil {
				m.Info = &ObjectInfo{}
			}
			if err := m.Info.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutboundLinks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocalstore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLocalstore
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLocalstore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OutboundLinks = append(m.OutboundLinks, &ObjectInfo{})
			if err := m.OutboundLinks[len(m.OutboundLinks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLocalstore(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLocalstore
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ObjectInfoWithOutboundLinksIDs) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLocalstore
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ObjectInfoWithOutboundLinksIDs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ObjectInfoWithOutboundLinksIDs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocalstore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLocalstore
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLocalstore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Info", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocalstore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLocalstore
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLocalstore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Info == nil {
				m.Info = &ObjectInfo{}
			}
			if err := m.Info.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutboundLinks", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocalstore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLocalstore
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLocalstore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OutboundLinks = append(m.OutboundLinks, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLocalstore(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLocalstore
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ObjectStoreChecksums) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLocalstore
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ObjectStoreChecksums: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ObjectStoreChecksums: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BundledObjectTypes", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocalstore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLocalstore
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLocalstore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BundledObjectTypes = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BundledRelations", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocalstore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLocalstore
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLocalstore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BundledRelations = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BundledLayouts", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocalstore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLocalstore
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLocalstore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BundledLayouts = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectsForceReindexCounter", wireType)
			}
			m.ObjectsForceReindexCounter = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocalstore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ObjectsForceReindexCounter |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FilesForceReindexCounter", wireType)
			}
			m.FilesForceReindexCounter = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocalstore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FilesForceReindexCounter |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IdxRebuildCounter", wireType)
			}
			m.IdxRebuildCounter = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocalstore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IdxRebuildCounter |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FulltextRebuild", wireType)
			}
			m.FulltextRebuild = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocalstore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FulltextRebuild |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLocalstore(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLocalstore
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLocalstore(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLocalstore
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLocalstore
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLocalstore
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLocalstore
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLocalstore
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLocalstore
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLocalstore        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLocalstore          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLocalstore = fmt.Errorf("proto: unexpected end of group")
)
