// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pb/protos/service/service.proto

package lib

import (
	fmt "fmt"
	pb "github.com/anytypeio/go-anytype-middleware/pb"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("pb/protos/service/service.proto", fileDescriptor_93a29dc403579097) }

var fileDescriptor_93a29dc403579097 = []byte{
	// 1317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x98, 0x4f, 0x93, 0xd4, 0x44,
	0x18, 0xc6, 0xd9, 0xd2, 0x12, 0x6d, 0xd6, 0x55, 0x5a, 0xa5, 0x64, 0x2d, 0x86, 0xff, 0xca, 0x0e,
	0x10, 0x10, 0xce, 0x1e, 0x98, 0x61, 0x59, 0xb7, 0x5c, 0x70, 0x9d, 0x59, 0xd8, 0x2a, 0x4a, 0x4b,
	0xb3, 0xc9, 0xcb, 0x6c, 0x9c, 0x4c, 0x77, 0x48, 0x7a, 0x06, 0xe6, 0xea, 0xc1, 0x83, 0x27, 0x3f,
	0x96, 0x47, 0x8e, 0x1e, 0x2d, 0xf6, 0x8b, 0x58, 0xdd, 0x79, 0xd3, 0xf9, 0xd7, 0xdd, 0x13, 0x0e,
	0x40, 0x91, 0xe7, 0xf7, 0x3e, 0x4f, 0x77, 0xf2, 0x76, 0xa7, 0x33, 0xe4, 0x62, 0x72, 0x74, 0x27,
	0x49, 0xb9, 0xe0, 0xd9, 0x9d, 0x0c, 0xd2, 0x45, 0x14, 0x40, 0xf1, 0xaf, 0xa7, 0x2e, 0xd3, 0xd3,
	0x3e, 0x5b, 0x8a, 0x65, 0x02, 0x9b, 0x5f, 0x96, 0x64, 0xc0, 0x67, 0x33, 0x9f, 0x85, 0x59, 0x8e,
	0x6c, 0x9e, 0x2b, 0x15, 0x58, 0x00, 0x13, 0x78, 0xfd, 0xde, 0x5f, 0xb7, 0xc8, 0xc6, 0x30, 0x8e,
	0x80, 0x89, 0x21, 0x16, 0xd0, 0x43, 0xb2, 0x7e, 0xe8, 0xc7, 0x31, 0x88, 0x61, 0x0a, 0xbe, 0x00,
	0x7a, 0xc5, 0x43, 0x7b, 0x6f, 0x94, 0x04, 0x5e, 0x2e, 0x79, 0xb9, 0xe6, 0x8d, 0xe0, 0xe5, 0x1c,
	0x32, 0xb1, 0x79, 0xd5, 0xc9, 0x64, 0x09, 0x67, 0x19, 0xd0, 0xe7, 0xe4, 0xe3, 0x5c, 0x19, 0x41,
	0xc0, 0x17, 0x90, 0x52, 0x63, 0x15, 0x8a, 0xda, 0xfa, 0x9a, 0x1b, 0x42, 0xef, 0x5f, 0xc8, 0xc6,
	0x83, 0x20, 0xe0, 0x73, 0xa6, 0xcd, 0xeb, 0x75, 0x28, 0xb6, 0xdc, 0xaf, 0xaf, 0xa0, 0xca, 0xa1,
	0xa3, 0x86, 0x37, 0xe5, 0xaa, 0xb1, 0xae, 0x71, 0x57, 0xae, 0xb9, 0xa1, 0x96, 0xf7, 0x18, 0x62,
	0x08, 0x84, 0xc5, 0x3b, 0x17, 0x57, 0x78, 0x6b, 0x08, 0xbd, 0x0f, 0xc8, 0x99, 0xc2, 0x5b, 0xf0,
	0x84, 0x5e, 0x36, 0x17, 0x09, 0x9e, 0x68, 0xdf, 0x2b, 0x2e, 0x04, 0x5d, 0x03, 0xb2, 0xbe, 0x3b,
	0xf3, 0x27, 0xb0, 0x03, 0x62, 0x10, 0xf3, 0x23, 0x7a, 0xa3, 0x56, 0xb3, 0x9b, 0xbc, 0xc8, 0x3c,
	0xa5, 0x7b, 0x3b, 0x20, 0x3c, 0x49, 0x68, 0xf7, 0xad, 0x0e, 0x24, 0x86, 0xfc, 0x44, 0xc8, 0x33,
	0x48, 0xb3, 0x88, 0xb3, 0x1d, 0x10, 0xf4, 0x52, 0xad, 0x10, 0x05, 0x55, 0x55, 0x58, 0x5f, 0x76,
	0x10, 0x68, 0xf9, 0x3d, 0x39, 0xbd, 0xc7, 0x27, 0x63, 0x60, 0x21, 0xbd, 0x50, 0xa3, 0xf7, 0xf8,
	0xc4, 0x93, 0x97, 0xb5, 0x59, 0xcf, 0x26, 0xa3, 0xd3, 0x13, 0xf2, 0xd1, 0x90, 0xb3, 0x17, 0xd1,
	0x44, 0x8e, 0xed, 0x62, 0x0d, 0xce, 0xaf, 0xd7, 0x86, 0x76, 0xc9, 0x0e, 0xa0, 0xdf, 0x0b, 0x72,
	0x76, 0xfb, 0xb5, 0x80, 0x94, 0xf9, 0xf1, 0xc3, 0x94, 0x27, 0x8f, 0xa2, 0x18, 0x32, 0xfa, 0x4d,
	0xad, 0xac, 0xaa, 0x7b, 0x0a, 0xd0, 0xfe, 0x37, 0x56, 0x83, 0x98, 0x13, 0x93, 0xcf, 0xaa, 0xf2,
	0x90, 0x33, 0x01, 0x4c, 0xd0, 0x2d, 0xbb, 0x01, 0x22, 0x3a, 0xab, 0xdf, 0x05, 0xc5, 0xb4, 0x11,
	0x39, 0xb3, 0x17, 0xb1, 0xe9, 0x7e, 0x0a, 0x8b, 0x08, 0x5e, 0x35, 0x9e, 0x61, 0x45, 0xb1, 0x3c,
	0xc3, 0x3a, 0x51, 0x76, 0xf4, 0x20, 0xe6, 0xc1, 0xf4, 0x69, 0x12, 0x73, 0x3f, 0x6c, 0x74, 0xb4,
	0x52, 0xbc, 0x5c, 0xb2, 0x74, 0x74, 0x03, 0x41, 0xd7, 0x43, 0xb2, 0xae, 0x84, 0x11, 0x24, 0xb1,
	0x1f, 0x34, 0xf7, 0xbc, 0xbc, 0x06, 0x35, 0xcb, 0x9e, 0xd7, 0x64, 0xca, 0x46, 0x51, 0xca, 0x8f,
	0x09, 0xb0, 0x46, 0xa3, 0xe4, 0x15, 0x52, 0xb0, 0x34, 0x4a, 0x0d, 0x40, 0x3f, 0x4e, 0x3e, 0xd7,
	0x7e, 0x83, 0x14, 0xfc, 0x30, 0x48, 0xe7, 0xb3, 0xa3, 0x8c, 0xf6, 0x2d, 0x95, 0x15, 0x46, 0xa7,
	0xdc, 0xec, 0xc4, 0x96, 0x1d, 0xa3, 0x88, 0xe1, 0x5c, 0x54, 0xf3, 0xb6, 0x0c, 0x1e, 0x75, 0xc4,
	0xd2, 0x31, 0x16, 0xb4, 0xf1, 0x74, 0x71, 0x97, 0x35, 0x3d, 0xdd, 0xc6, 0x1e, 0x7b, 0xc5, 0x85,
	0xa0, 0xeb, 0x6f, 0xe4, 0x93, 0x8a, 0xeb, 0xbe, 0x3f, 0x01, 0x7a, 0xdd, 0x5a, 0x26, 0x65, 0xed,
	0xfe, 0xf5, 0x2a, 0xac, 0xd9, 0x95, 0x2c, 0x8e, 0xd8, 0xd4, 0xdc, 0x95, 0x4a, 0x72, 0x77, 0x65,
	0x81, 0x94, 0x5b, 0x60, 0x3e, 0xee, 0x98, 0x67, 0x40, 0x4d, 0xcd, 0xa1, 0x14, 0xcb, 0xf2, 0xa9,
	0x13, 0xe5, 0xcb, 0x46, 0x5d, 0x7f, 0xc8, 0x5f, 0x31, 0xb5, 0x80, 0x4c, 0x5d, 0x5c, 0x88, 0x96,
	0x97, 0x4d, 0x0b, 0x42, 0xef, 0x9f, 0xd1, 0x7b, 0x07, 0xc4, 0x63, 0x3f, 0x9d, 0x66, 0xd4, 0x54,
	0x26, 0xb7, 0x3d, 0xa5, 0x5a, 0x5e, 0xc1, 0x6d, 0xaa, 0xb1, 0x92, 0x9e, 0xb2, 0x90, 0x1b, 0x57,
	0x92, 0x14, 0x9c, 0x2b, 0x09, 0x81, 0x86, 0xdf, 0x08, 0x2c, 0x7e, 0x52, 0x70, 0xfa, 0x21, 0x80,
	0x7e, 0xbf, 0x92, 0x0d, 0x75, 0x79, 0x0c, 0xe2, 0x51, 0x04, 0x71, 0x98, 0x19, 0x7b, 0x6c, 0x0c,
	0xc2, 0xcb, 0x65, 0x67, 0x8f, 0xd5, 0x30, 0x0c, 0x78, 0x89, 0x4b, 0x7f, 0x2c, 0x0f, 0x50, 0x99,
	0x48, 0xa3, 0x40, 0x44, 0x9c, 0x65, 0xf4, 0xa6, 0xa5, 0xbe, 0x0a, 0xe9, 0xb0, 0x5b, 0xdd, 0x60,
	0x8c, 0x5c, 0x92, 0x73, 0x45, 0xa4, 0xec, 0xf7, 0xdd, 0xec, 0x41, 0x1a, 0x1c, 0x47, 0x0b, 0x08,
	0xa9, 0x67, 0xf1, 0x51, 0xcb, 0xa2, 0xe4, 0x74, 0xee, 0x9d, 0xce, 0x7c, 0xa3, 0x51, 0xf7, 0xa2,
	0x4c, 0x3c, 0xe6, 0x0b, 0x30, 0x35, 0xaa, 0xd4, 0x3c, 0x29, 0xba, 0x1a, 0xb5, 0x0a, 0xa1, 0xf7,
	0x1c, 0xa7, 0x55, 0x78, 0x1f, 0xf0, 0x27, 0xf0, 0x4a, 0x6d, 0x0b, 0xb7, 0x1c, 0xf5, 0x9a, 0xd2,
	0x69, 0xb7, 0x3b, 0xd2, 0x18, 0x3b, 0x25, 0x54, 0x33, 0x65, 0x97, 0x6c, 0x59, 0x4c, 0x0c, 0x9d,
	0xd2, 0xef, 0x82, 0x62, 0xd8, 0x82, 0x7c, 0x51, 0x0d, 0x3b, 0x80, 0xd7, 0x62, 0x2c, 0x96, 0x31,
	0xd0, 0xdb, 0x0e, 0x13, 0x49, 0x79, 0x0a, 0xd3, 0x99, 0x5e, 0x57, 0x1c, 0x73, 0xa3, 0xca, 0x24,
	0x1f, 0xce, 0x93, 0x38, 0x0a, 0xe4, 0x46, 0x7e, 0xc3, 0xe2, 0xa2, 0x09, 0xcb, 0x09, 0xd1, 0x4c,
	0x62, 0xd4, 0x9f, 0x6b, 0xe4, 0xab, 0xea, 0x1c, 0x07, 0x7e, 0x30, 0x9d, 0xa4, 0x7c, 0xce, 0xc2,
	0x21, 0x8f, 0x79, 0x4a, 0xef, 0x39, 0x86, 0xde, 0x60, 0x75, 0xfc, 0xfd, 0x77, 0xaa, 0xc1, 0x81,
	0x1c, 0x93, 0xb3, 0xd5, 0x71, 0x3c, 0x88, 0xa3, 0x09, 0xb3, 0x4e, 0x59, 0x3a, 0x29, 0x62, 0xe5,
	0x94, 0xab, 0x24, 0x26, 0x4d, 0xc8, 0xa7, 0xc5, 0x82, 0x94, 0x37, 0x5f, 0xfe, 0x31, 0x05, 0x95,
	0x4f, 0x47, 0xfd, 0xe5, 0x08, 0x6a, 0x91, 0x18, 0xf4, 0x3b, 0x4e, 0x09, 0x83, 0xf2, 0x1b, 0xea,
	0xac, 0xaf, 0xdf, 0xc7, 0x7e, 0x17, 0xd4, 0xde, 0xaa, 0x79, 0xde, 0xca, 0x56, 0xad, 0x67, 0x7a,
	0x5d, 0x71, 0xf3, 0x1c, 0xf3, 0xe5, 0xe1, 0x9c, 0x63, 0x7d, 0x69, 0xf4, 0xbb, 0xa0, 0x98, 0x95,
	0xe0, 0x31, 0xaa, 0x98, 0xdf, 0x31, 0x04, 0x53, 0x08, 0xad, 0x7b, 0x77, 0x3e, 0xdc, 0x1c, 0x5a,
	0xb9, 0x77, 0x37, 0xe0, 0xc6, 0xe1, 0x61, 0x9c, 0xc4, 0x91, 0x30, 0x1e, 0x1e, 0x94, 0xe2, 0x3c,
	0x3c, 0x14, 0x44, 0xc3, 0xf2, 0x31, 0xa4, 0x13, 0xf3, 0x79, 0x44, 0x29, 0x4e, 0xcb, 0x82, 0x68,
	0xbc, 0x85, 0x87, 0x3c, 0x59, 0x1a, 0xdf, 0xc2, 0x52, 0x70, 0xbe, 0x85, 0x11, 0x68, 0x0c, 0x71,
	0xdf, 0xcf, 0x84, 0x79, 0x88, 0x4a, 0x71, 0x0e, 0xb1, 0x20, 0xd0, 0xf2, 0x07, 0xf2, 0x61, 0x71,
	0x02, 0xa6, 0x3d, 0xf3, 0x59, 0x56, 0xdb, 0x5d, 0xb4, 0xea, 0x8d, 0x83, 0xe2, 0xf6, 0xeb, 0x84,
	0xa7, 0xc2, 0x78, 0x50, 0xcc, 0x25, 0xe7, 0x41, 0x51, 0x23, 0xed, 0x6d, 0x41, 0x7e, 0xf0, 0x3d,
	0xf1, 0x67, 0x60, 0xdd, 0x16, 0x24, 0xe0, 0x49, 0x62, 0xe5, 0xb6, 0x50, 0x25, 0xdb, 0x4b, 0x46,
	0x7d, 0xb7, 0xab, 0x24, 0x5b, 0x7d, 0xfe, 0x65, 0x5f, 0x8b, 0xea, 0x77, 0x41, 0x31, 0x6b, 0x86,
	0x6f, 0x92, 0x22, 0xeb, 0x30, 0x0a, 0xc5, 0x31, 0x75, 0x3b, 0x28, 0xc6, 0xf9, 0xa1, 0xd3, 0x66,
	0xdb, 0x53, 0x7b, 0x16, 0x85, 0xc0, 0x9d, 0x53, 0x53, 0x44, 0xb7, 0xa9, 0xd5, 0xd0, 0xf6, 0xd4,
	0x94, 0xec, 0x9e, 0x5a, 0xee, 0xd0, 0x6d, 0x6a, 0x75, 0xb6, 0xdd, 0x1e, 0xbb, 0x01, 0x67, 0xce,
	0xf6, 0x90, 0x40, 0xb7, 0xf6, 0xa8, 0x92, 0x18, 0xf4, 0xc7, 0x1a, 0x39, 0x5f, 0x24, 0xc9, 0xaf,
	0xf7, 0x03, 0x3f, 0x9d, 0xa8, 0xdf, 0x88, 0x82, 0xe9, 0x6e, 0x48, 0xbf, 0xb5, 0x18, 0x49, 0xd2,
	0xab, 0xa1, 0x3a, 0xfb, 0xde, 0xbb, 0x94, 0x34, 0x8e, 0x59, 0x03, 0xce, 0xa7, 0x33, 0x3f, 0x9d,
	0x3e, 0x02, 0x11, 0x1c, 0x1b, 0x9f, 0x64, 0x41, 0x78, 0x0a, 0x71, 0x3e, 0xc9, 0x16, 0x8a, 0x61,
	0xdf, 0x91, 0xf7, 0xf7, 0x23, 0x36, 0xa1, 0xe7, 0x6b, 0x35, 0xf2, 0x92, 0xb6, 0xdb, 0x34, 0x49,
	0xe5, 0x29, 0x77, 0x3f, 0xe5, 0x01, 0x64, 0xd9, 0xd0, 0x67, 0x01, 0xc4, 0x8d, 0x53, 0x2e, 0x6a,
	0x5e, 0x2e, 0x5a, 0x4e, 0xb9, 0x2d, 0x08, 0xbd, 0xef, 0x92, 0x75, 0xf9, 0xfa, 0x03, 0xb6, 0xad,
	0x7e, 0xf0, 0xa5, 0x1b, 0xba, 0x6a, 0x7b, 0x96, 0x88, 0xe5, 0x66, 0xe5, 0xff, 0x12, 0xb8, 0xbb,
	0x36, 0xb8, 0xf0, 0xcf, 0xdb, 0xde, 0xda, 0x9b, 0xb7, 0xbd, 0xb5, 0xff, 0xde, 0xf6, 0xd6, 0xfe,
	0x3e, 0xe9, 0x9d, 0x7a, 0x73, 0xd2, 0x3b, 0xf5, 0xef, 0x49, 0xef, 0xd4, 0xf3, 0xf7, 0xe2, 0xe8,
	0xe8, 0xe8, 0x03, 0xf5, 0x93, 0xf1, 0xfd, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x3d, 0x75, 0xe8,
	0x5e, 0x90, 0x16, 0x00, 0x00,
}

// This is a compile-time assertion to ensure that this generated file
// is compatible with the gomobile package it is being compiled against.

// ClientCommandsHandler is the handler API for ClientCommands service.
var clientCommandsHandler ClientCommandsHandler

type ClientCommandsHandler interface {
	WalletCreate(*pb.RpcWalletCreateRequest) *pb.RpcWalletCreateResponse
	WalletRecover(*pb.RpcWalletRecoverRequest) *pb.RpcWalletRecoverResponse
	AccountRecover(*pb.RpcAccountRecoverRequest) *pb.RpcAccountRecoverResponse
	AccountCreate(*pb.RpcAccountCreateRequest) *pb.RpcAccountCreateResponse
	AccountSelect(*pb.RpcAccountSelectRequest) *pb.RpcAccountSelectResponse
	AccountStop(*pb.RpcAccountStopRequest) *pb.RpcAccountStopResponse
	ImageGetBlob(*pb.RpcIpfsImageGetBlobRequest) *pb.RpcIpfsImageGetBlobResponse
	VersionGet(*pb.RpcVersionGetRequest) *pb.RpcVersionGetResponse
	LogSend(*pb.RpcLogSendRequest) *pb.RpcLogSendResponse
	ConfigGet(*pb.RpcConfigGetRequest) *pb.RpcConfigGetResponse
	ExternalDropFiles(*pb.RpcExternalDropFilesRequest) *pb.RpcExternalDropFilesResponse
	ExternalDropContent(*pb.RpcExternalDropContentRequest) *pb.RpcExternalDropContentResponse
	LinkPreview(*pb.RpcLinkPreviewRequest) *pb.RpcLinkPreviewResponse
	BlockUpload(*pb.RpcBlockUploadRequest) *pb.RpcBlockUploadResponse
	BlockReplace(*pb.RpcBlockReplaceRequest) *pb.RpcBlockReplaceResponse
	BlockOpen(*pb.RpcBlockOpenRequest) *pb.RpcBlockOpenResponse
	BlockOpenBreadcrumbs(*pb.RpcBlockOpenBreadcrumbsRequest) *pb.RpcBlockOpenBreadcrumbsResponse
	BlockCutBreadcrumbs(*pb.RpcBlockCutBreadcrumbsRequest) *pb.RpcBlockCutBreadcrumbsResponse
	BlockCreate(*pb.RpcBlockCreateRequest) *pb.RpcBlockCreateResponse
	BlockCreatePage(*pb.RpcBlockCreatePageRequest) *pb.RpcBlockCreatePageResponse
	BlockUnlink(*pb.RpcBlockUnlinkRequest) *pb.RpcBlockUnlinkResponse
	BlockClose(*pb.RpcBlockCloseRequest) *pb.RpcBlockCloseResponse
	BlockDownload(*pb.RpcBlockDownloadRequest) *pb.RpcBlockDownloadResponse
	BlockGetMarks(*pb.RpcBlockGetMarksRequest) *pb.RpcBlockGetMarksResponse
	BlockUndo(*pb.RpcBlockUndoRequest) *pb.RpcBlockUndoResponse
	BlockRedo(*pb.RpcBlockRedoRequest) *pb.RpcBlockRedoResponse
	BlockSetFields(*pb.RpcBlockSetFieldsRequest) *pb.RpcBlockSetFieldsResponse
	BlockSetRestrictions(*pb.RpcBlockSetRestrictionsRequest) *pb.RpcBlockSetRestrictionsResponse
	BlockSetPageIsArchived(*pb.RpcBlockSetPageIsArchivedRequest) *pb.RpcBlockSetPageIsArchivedResponse
	BlockListMove(*pb.RpcBlockListMoveRequest) *pb.RpcBlockListMoveResponse
	BlockListMoveToNewPage(*pb.RpcBlockListMoveToNewPageRequest) *pb.RpcBlockListMoveToNewPageResponse
	BlockListSetFields(*pb.RpcBlockListSetFieldsRequest) *pb.RpcBlockListSetFieldsResponse
	BlockListSetTextStyle(*pb.RpcBlockListSetTextStyleRequest) *pb.RpcBlockListSetTextStyleResponse
	BlockListDuplicate(*pb.RpcBlockListDuplicateRequest) *pb.RpcBlockListDuplicateResponse
	BlockListSetBackgroundColor(*pb.RpcBlockListSetBackgroundColorRequest) *pb.RpcBlockListSetBackgroundColorResponse
	BlockListSetAlign(*pb.RpcBlockListSetAlignRequest) *pb.RpcBlockListSetAlignResponse
	BlockSetTextText(*pb.RpcBlockSetTextTextRequest) *pb.RpcBlockSetTextTextResponse
	BlockSetTextColor(*pb.RpcBlockSetTextColorRequest) *pb.RpcBlockSetTextColorResponse
	BlockListSetTextColor(*pb.RpcBlockListSetTextColorRequest) *pb.RpcBlockListSetTextColorResponse
	BlockSetTextStyle(*pb.RpcBlockSetTextStyleRequest) *pb.RpcBlockSetTextStyleResponse
	BlockSetTextChecked(*pb.RpcBlockSetTextCheckedRequest) *pb.RpcBlockSetTextCheckedResponse
	BlockSplit(*pb.RpcBlockSplitRequest) *pb.RpcBlockSplitResponse
	BlockMerge(*pb.RpcBlockMergeRequest) *pb.RpcBlockMergeResponse
	BlockCopy(*pb.RpcBlockCopyRequest) *pb.RpcBlockCopyResponse
	BlockPaste(*pb.RpcBlockPasteRequest) *pb.RpcBlockPasteResponse
	BlockCut(*pb.RpcBlockCutRequest) *pb.RpcBlockCutResponse
	BlockExport(*pb.RpcBlockExportRequest) *pb.RpcBlockExportResponse
	BlockSetFileName(*pb.RpcBlockSetFileNameRequest) *pb.RpcBlockSetFileNameResponse
	BlockSetImageName(*pb.RpcBlockSetImageNameRequest) *pb.RpcBlockSetImageNameResponse
	BlockSetImageWidth(*pb.RpcBlockSetImageWidthRequest) *pb.RpcBlockSetImageWidthResponse
	BlockSetVideoName(*pb.RpcBlockSetVideoNameRequest) *pb.RpcBlockSetVideoNameResponse
	BlockSetVideoWidth(*pb.RpcBlockSetVideoWidthRequest) *pb.RpcBlockSetVideoWidthResponse
	BlockSetIconName(*pb.RpcBlockSetIconNameRequest) *pb.RpcBlockSetIconNameResponse
	BlockSetLinkTargetBlockId(*pb.RpcBlockSetLinkTargetBlockIdRequest) *pb.RpcBlockSetLinkTargetBlockIdResponse
	BlockBookmarkFetch(*pb.RpcBlockBookmarkFetchRequest) *pb.RpcBlockBookmarkFetchResponse
	Ping(*pb.RpcPingRequest) *pb.RpcPingResponse
	ProcessCancel(*pb.RpcProcessCancelRequest) *pb.RpcProcessCancelResponse
	// used only for lib-debug via grpc
	// Streams not supported ### ListenEvents(*pb.Empty)
}

func registerClientCommandsHandler(srv ClientCommandsHandler) {
	clientCommandsHandler = srv
}

func WalletCreate(b []byte) []byte {
	in := new(pb.RpcWalletCreateRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcWalletCreateResponse{Error: &pb.RpcWalletCreateResponseError{Code: pb.RpcWalletCreateResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.WalletCreate(in).Marshal()
	return resp
}

func WalletRecover(b []byte) []byte {
	in := new(pb.RpcWalletRecoverRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcWalletRecoverResponse{Error: &pb.RpcWalletRecoverResponseError{Code: pb.RpcWalletRecoverResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.WalletRecover(in).Marshal()
	return resp
}

func AccountRecover(b []byte) []byte {
	in := new(pb.RpcAccountRecoverRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcAccountRecoverResponse{Error: &pb.RpcAccountRecoverResponseError{Code: pb.RpcAccountRecoverResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.AccountRecover(in).Marshal()
	return resp
}

func AccountCreate(b []byte) []byte {
	in := new(pb.RpcAccountCreateRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcAccountCreateResponse{Error: &pb.RpcAccountCreateResponseError{Code: pb.RpcAccountCreateResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.AccountCreate(in).Marshal()
	return resp
}

func AccountSelect(b []byte) []byte {
	in := new(pb.RpcAccountSelectRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcAccountSelectResponse{Error: &pb.RpcAccountSelectResponseError{Code: pb.RpcAccountSelectResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.AccountSelect(in).Marshal()
	return resp
}

func AccountStop(b []byte) []byte {
	in := new(pb.RpcAccountStopRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcAccountStopResponse{Error: &pb.RpcAccountStopResponseError{Code: pb.RpcAccountStopResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.AccountStop(in).Marshal()
	return resp
}

func ImageGetBlob(b []byte) []byte {
	in := new(pb.RpcIpfsImageGetBlobRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcIpfsImageGetBlobResponse{Error: &pb.RpcIpfsImageGetBlobResponseError{Code: pb.RpcIpfsImageGetBlobResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.ImageGetBlob(in).Marshal()
	return resp
}

func VersionGet(b []byte) []byte {
	in := new(pb.RpcVersionGetRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcVersionGetResponse{Error: &pb.RpcVersionGetResponseError{Code: pb.RpcVersionGetResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.VersionGet(in).Marshal()
	return resp
}

func LogSend(b []byte) []byte {
	in := new(pb.RpcLogSendRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcLogSendResponse{Error: &pb.RpcLogSendResponseError{Code: pb.RpcLogSendResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.LogSend(in).Marshal()
	return resp
}

func ConfigGet(b []byte) []byte {
	in := new(pb.RpcConfigGetRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcConfigGetResponse{Error: &pb.RpcConfigGetResponseError{Code: pb.RpcConfigGetResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.ConfigGet(in).Marshal()
	return resp
}

func ExternalDropFiles(b []byte) []byte {
	in := new(pb.RpcExternalDropFilesRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcExternalDropFilesResponse{Error: &pb.RpcExternalDropFilesResponseError{Code: pb.RpcExternalDropFilesResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.ExternalDropFiles(in).Marshal()
	return resp
}

func ExternalDropContent(b []byte) []byte {
	in := new(pb.RpcExternalDropContentRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcExternalDropContentResponse{Error: &pb.RpcExternalDropContentResponseError{Code: pb.RpcExternalDropContentResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.ExternalDropContent(in).Marshal()
	return resp
}

func LinkPreview(b []byte) []byte {
	in := new(pb.RpcLinkPreviewRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcLinkPreviewResponse{Error: &pb.RpcLinkPreviewResponseError{Code: pb.RpcLinkPreviewResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.LinkPreview(in).Marshal()
	return resp
}

func BlockUpload(b []byte) []byte {
	in := new(pb.RpcBlockUploadRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockUploadResponse{Error: &pb.RpcBlockUploadResponseError{Code: pb.RpcBlockUploadResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockUpload(in).Marshal()
	return resp
}

func BlockReplace(b []byte) []byte {
	in := new(pb.RpcBlockReplaceRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockReplaceResponse{Error: &pb.RpcBlockReplaceResponseError{Code: pb.RpcBlockReplaceResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockReplace(in).Marshal()
	return resp
}

func BlockOpen(b []byte) []byte {
	in := new(pb.RpcBlockOpenRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockOpenResponse{Error: &pb.RpcBlockOpenResponseError{Code: pb.RpcBlockOpenResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockOpen(in).Marshal()
	return resp
}

func BlockOpenBreadcrumbs(b []byte) []byte {
	in := new(pb.RpcBlockOpenBreadcrumbsRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockOpenBreadcrumbsResponse{Error: &pb.RpcBlockOpenBreadcrumbsResponseError{Code: pb.RpcBlockOpenBreadcrumbsResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockOpenBreadcrumbs(in).Marshal()
	return resp
}

func BlockCutBreadcrumbs(b []byte) []byte {
	in := new(pb.RpcBlockCutBreadcrumbsRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockCutBreadcrumbsResponse{Error: &pb.RpcBlockCutBreadcrumbsResponseError{Code: pb.RpcBlockCutBreadcrumbsResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockCutBreadcrumbs(in).Marshal()
	return resp
}

func BlockCreate(b []byte) []byte {
	in := new(pb.RpcBlockCreateRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockCreateResponse{Error: &pb.RpcBlockCreateResponseError{Code: pb.RpcBlockCreateResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockCreate(in).Marshal()
	return resp
}

func BlockCreatePage(b []byte) []byte {
	in := new(pb.RpcBlockCreatePageRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockCreatePageResponse{Error: &pb.RpcBlockCreatePageResponseError{Code: pb.RpcBlockCreatePageResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockCreatePage(in).Marshal()
	return resp
}

func BlockUnlink(b []byte) []byte {
	in := new(pb.RpcBlockUnlinkRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockUnlinkResponse{Error: &pb.RpcBlockUnlinkResponseError{Code: pb.RpcBlockUnlinkResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockUnlink(in).Marshal()
	return resp
}

func BlockClose(b []byte) []byte {
	in := new(pb.RpcBlockCloseRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockCloseResponse{Error: &pb.RpcBlockCloseResponseError{Code: pb.RpcBlockCloseResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockClose(in).Marshal()
	return resp
}

func BlockDownload(b []byte) []byte {
	in := new(pb.RpcBlockDownloadRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockDownloadResponse{Error: &pb.RpcBlockDownloadResponseError{Code: pb.RpcBlockDownloadResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockDownload(in).Marshal()
	return resp
}

func BlockGetMarks(b []byte) []byte {
	in := new(pb.RpcBlockGetMarksRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockGetMarksResponse{Error: &pb.RpcBlockGetMarksResponseError{Code: pb.RpcBlockGetMarksResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockGetMarks(in).Marshal()
	return resp
}

func BlockUndo(b []byte) []byte {
	in := new(pb.RpcBlockUndoRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockUndoResponse{Error: &pb.RpcBlockUndoResponseError{Code: pb.RpcBlockUndoResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockUndo(in).Marshal()
	return resp
}

func BlockRedo(b []byte) []byte {
	in := new(pb.RpcBlockRedoRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockRedoResponse{Error: &pb.RpcBlockRedoResponseError{Code: pb.RpcBlockRedoResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockRedo(in).Marshal()
	return resp
}

func BlockSetFields(b []byte) []byte {
	in := new(pb.RpcBlockSetFieldsRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockSetFieldsResponse{Error: &pb.RpcBlockSetFieldsResponseError{Code: pb.RpcBlockSetFieldsResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockSetFields(in).Marshal()
	return resp
}

func BlockSetRestrictions(b []byte) []byte {
	in := new(pb.RpcBlockSetRestrictionsRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockSetRestrictionsResponse{Error: &pb.RpcBlockSetRestrictionsResponseError{Code: pb.RpcBlockSetRestrictionsResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockSetRestrictions(in).Marshal()
	return resp
}

func BlockSetPageIsArchived(b []byte) []byte {
	in := new(pb.RpcBlockSetPageIsArchivedRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockSetPageIsArchivedResponse{Error: &pb.RpcBlockSetPageIsArchivedResponseError{Code: pb.RpcBlockSetPageIsArchivedResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockSetPageIsArchived(in).Marshal()
	return resp
}

func BlockListMove(b []byte) []byte {
	in := new(pb.RpcBlockListMoveRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockListMoveResponse{Error: &pb.RpcBlockListMoveResponseError{Code: pb.RpcBlockListMoveResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockListMove(in).Marshal()
	return resp
}

func BlockListMoveToNewPage(b []byte) []byte {
	in := new(pb.RpcBlockListMoveToNewPageRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockListMoveToNewPageResponse{Error: &pb.RpcBlockListMoveToNewPageResponseError{Code: pb.RpcBlockListMoveToNewPageResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockListMoveToNewPage(in).Marshal()
	return resp
}

func BlockListSetFields(b []byte) []byte {
	in := new(pb.RpcBlockListSetFieldsRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockListSetFieldsResponse{Error: &pb.RpcBlockListSetFieldsResponseError{Code: pb.RpcBlockListSetFieldsResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockListSetFields(in).Marshal()
	return resp
}

func BlockListSetTextStyle(b []byte) []byte {
	in := new(pb.RpcBlockListSetTextStyleRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockListSetTextStyleResponse{Error: &pb.RpcBlockListSetTextStyleResponseError{Code: pb.RpcBlockListSetTextStyleResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockListSetTextStyle(in).Marshal()
	return resp
}

func BlockListDuplicate(b []byte) []byte {
	in := new(pb.RpcBlockListDuplicateRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockListDuplicateResponse{Error: &pb.RpcBlockListDuplicateResponseError{Code: pb.RpcBlockListDuplicateResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockListDuplicate(in).Marshal()
	return resp
}

func BlockListSetBackgroundColor(b []byte) []byte {
	in := new(pb.RpcBlockListSetBackgroundColorRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockListSetBackgroundColorResponse{Error: &pb.RpcBlockListSetBackgroundColorResponseError{Code: pb.RpcBlockListSetBackgroundColorResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockListSetBackgroundColor(in).Marshal()
	return resp
}

func BlockListSetAlign(b []byte) []byte {
	in := new(pb.RpcBlockListSetAlignRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockListSetAlignResponse{Error: &pb.RpcBlockListSetAlignResponseError{Code: pb.RpcBlockListSetAlignResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockListSetAlign(in).Marshal()
	return resp
}

func BlockSetTextText(b []byte) []byte {
	in := new(pb.RpcBlockSetTextTextRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockSetTextTextResponse{Error: &pb.RpcBlockSetTextTextResponseError{Code: pb.RpcBlockSetTextTextResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockSetTextText(in).Marshal()
	return resp
}

func BlockSetTextColor(b []byte) []byte {
	in := new(pb.RpcBlockSetTextColorRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockSetTextColorResponse{Error: &pb.RpcBlockSetTextColorResponseError{Code: pb.RpcBlockSetTextColorResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockSetTextColor(in).Marshal()
	return resp
}

func BlockListSetTextColor(b []byte) []byte {
	in := new(pb.RpcBlockListSetTextColorRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockListSetTextColorResponse{Error: &pb.RpcBlockListSetTextColorResponseError{Code: pb.RpcBlockListSetTextColorResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockListSetTextColor(in).Marshal()
	return resp
}

func BlockSetTextStyle(b []byte) []byte {
	in := new(pb.RpcBlockSetTextStyleRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockSetTextStyleResponse{Error: &pb.RpcBlockSetTextStyleResponseError{Code: pb.RpcBlockSetTextStyleResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockSetTextStyle(in).Marshal()
	return resp
}

func BlockSetTextChecked(b []byte) []byte {
	in := new(pb.RpcBlockSetTextCheckedRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockSetTextCheckedResponse{Error: &pb.RpcBlockSetTextCheckedResponseError{Code: pb.RpcBlockSetTextCheckedResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockSetTextChecked(in).Marshal()
	return resp
}

func BlockSplit(b []byte) []byte {
	in := new(pb.RpcBlockSplitRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockSplitResponse{Error: &pb.RpcBlockSplitResponseError{Code: pb.RpcBlockSplitResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockSplit(in).Marshal()
	return resp
}

func BlockMerge(b []byte) []byte {
	in := new(pb.RpcBlockMergeRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockMergeResponse{Error: &pb.RpcBlockMergeResponseError{Code: pb.RpcBlockMergeResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockMerge(in).Marshal()
	return resp
}

func BlockCopy(b []byte) []byte {
	in := new(pb.RpcBlockCopyRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockCopyResponse{Error: &pb.RpcBlockCopyResponseError{Code: pb.RpcBlockCopyResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockCopy(in).Marshal()
	return resp
}

func BlockPaste(b []byte) []byte {
	in := new(pb.RpcBlockPasteRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockPasteResponse{Error: &pb.RpcBlockPasteResponseError{Code: pb.RpcBlockPasteResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockPaste(in).Marshal()
	return resp
}

func BlockCut(b []byte) []byte {
	in := new(pb.RpcBlockCutRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockCutResponse{Error: &pb.RpcBlockCutResponseError{Code: pb.RpcBlockCutResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockCut(in).Marshal()
	return resp
}

func BlockExport(b []byte) []byte {
	in := new(pb.RpcBlockExportRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockExportResponse{Error: &pb.RpcBlockExportResponseError{Code: pb.RpcBlockExportResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockExport(in).Marshal()
	return resp
}

func BlockSetFileName(b []byte) []byte {
	in := new(pb.RpcBlockSetFileNameRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockSetFileNameResponse{Error: &pb.RpcBlockSetFileNameResponseError{Code: pb.RpcBlockSetFileNameResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockSetFileName(in).Marshal()
	return resp
}

func BlockSetImageName(b []byte) []byte {
	in := new(pb.RpcBlockSetImageNameRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockSetImageNameResponse{Error: &pb.RpcBlockSetImageNameResponseError{Code: pb.RpcBlockSetImageNameResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockSetImageName(in).Marshal()
	return resp
}

func BlockSetImageWidth(b []byte) []byte {
	in := new(pb.RpcBlockSetImageWidthRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockSetImageWidthResponse{Error: &pb.RpcBlockSetImageWidthResponseError{Code: pb.RpcBlockSetImageWidthResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockSetImageWidth(in).Marshal()
	return resp
}

func BlockSetVideoName(b []byte) []byte {
	in := new(pb.RpcBlockSetVideoNameRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockSetVideoNameResponse{Error: &pb.RpcBlockSetVideoNameResponseError{Code: pb.RpcBlockSetVideoNameResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockSetVideoName(in).Marshal()
	return resp
}

func BlockSetVideoWidth(b []byte) []byte {
	in := new(pb.RpcBlockSetVideoWidthRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockSetVideoWidthResponse{Error: &pb.RpcBlockSetVideoWidthResponseError{Code: pb.RpcBlockSetVideoWidthResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockSetVideoWidth(in).Marshal()
	return resp
}

func BlockSetIconName(b []byte) []byte {
	in := new(pb.RpcBlockSetIconNameRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockSetIconNameResponse{Error: &pb.RpcBlockSetIconNameResponseError{Code: pb.RpcBlockSetIconNameResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockSetIconName(in).Marshal()
	return resp
}

func BlockSetLinkTargetBlockId(b []byte) []byte {
	in := new(pb.RpcBlockSetLinkTargetBlockIdRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockSetLinkTargetBlockIdResponse{Error: &pb.RpcBlockSetLinkTargetBlockIdResponseError{Code: pb.RpcBlockSetLinkTargetBlockIdResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockSetLinkTargetBlockId(in).Marshal()
	return resp
}

func BlockBookmarkFetch(b []byte) []byte {
	in := new(pb.RpcBlockBookmarkFetchRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcBlockBookmarkFetchResponse{Error: &pb.RpcBlockBookmarkFetchResponseError{Code: pb.RpcBlockBookmarkFetchResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.BlockBookmarkFetch(in).Marshal()
	return resp
}

func Ping(b []byte) []byte {
	in := new(pb.RpcPingRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcPingResponse{Error: &pb.RpcPingResponseError{Code: pb.RpcPingResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.Ping(in).Marshal()
	return resp
}

func ProcessCancel(b []byte) []byte {
	in := new(pb.RpcProcessCancelRequest)
	if err := in.Unmarshal(b); err != nil {
		resp, _ := (&pb.RpcProcessCancelResponse{Error: &pb.RpcProcessCancelResponseError{Code: pb.RpcProcessCancelResponseError_BAD_INPUT, Description: err.Error()}}).Marshal()
		return resp
	}
	resp, _ := clientCommandsHandler.ProcessCancel(in).Marshal()
	return resp
}

func CommandAsync(cmd string, data []byte, callback func(data []byte)) {
	go func() {
		var cd []byte
		switch cmd {
		case "WalletCreate":
			cd = WalletCreate(data)
		case "WalletRecover":
			cd = WalletRecover(data)
		case "AccountRecover":
			cd = AccountRecover(data)
		case "AccountCreate":
			cd = AccountCreate(data)
		case "AccountSelect":
			cd = AccountSelect(data)
		case "AccountStop":
			cd = AccountStop(data)
		case "ImageGetBlob":
			cd = ImageGetBlob(data)
		case "VersionGet":
			cd = VersionGet(data)
		case "LogSend":
			cd = LogSend(data)
		case "ConfigGet":
			cd = ConfigGet(data)
		case "ExternalDropFiles":
			cd = ExternalDropFiles(data)
		case "ExternalDropContent":
			cd = ExternalDropContent(data)
		case "LinkPreview":
			cd = LinkPreview(data)
		case "BlockUpload":
			cd = BlockUpload(data)
		case "BlockReplace":
			cd = BlockReplace(data)
		case "BlockOpen":
			cd = BlockOpen(data)
		case "BlockOpenBreadcrumbs":
			cd = BlockOpenBreadcrumbs(data)
		case "BlockCutBreadcrumbs":
			cd = BlockCutBreadcrumbs(data)
		case "BlockCreate":
			cd = BlockCreate(data)
		case "BlockCreatePage":
			cd = BlockCreatePage(data)
		case "BlockUnlink":
			cd = BlockUnlink(data)
		case "BlockClose":
			cd = BlockClose(data)
		case "BlockDownload":
			cd = BlockDownload(data)
		case "BlockGetMarks":
			cd = BlockGetMarks(data)
		case "BlockUndo":
			cd = BlockUndo(data)
		case "BlockRedo":
			cd = BlockRedo(data)
		case "BlockSetFields":
			cd = BlockSetFields(data)
		case "BlockSetRestrictions":
			cd = BlockSetRestrictions(data)
		case "BlockSetPageIsArchived":
			cd = BlockSetPageIsArchived(data)
		case "BlockListMove":
			cd = BlockListMove(data)
		case "BlockListMoveToNewPage":
			cd = BlockListMoveToNewPage(data)
		case "BlockListSetFields":
			cd = BlockListSetFields(data)
		case "BlockListSetTextStyle":
			cd = BlockListSetTextStyle(data)
		case "BlockListDuplicate":
			cd = BlockListDuplicate(data)
		case "BlockListSetBackgroundColor":
			cd = BlockListSetBackgroundColor(data)
		case "BlockListSetAlign":
			cd = BlockListSetAlign(data)
		case "BlockSetTextText":
			cd = BlockSetTextText(data)
		case "BlockSetTextColor":
			cd = BlockSetTextColor(data)
		case "BlockListSetTextColor":
			cd = BlockListSetTextColor(data)
		case "BlockSetTextStyle":
			cd = BlockSetTextStyle(data)
		case "BlockSetTextChecked":
			cd = BlockSetTextChecked(data)
		case "BlockSplit":
			cd = BlockSplit(data)
		case "BlockMerge":
			cd = BlockMerge(data)
		case "BlockCopy":
			cd = BlockCopy(data)
		case "BlockPaste":
			cd = BlockPaste(data)
		case "BlockCut":
			cd = BlockCut(data)
		case "BlockExport":
			cd = BlockExport(data)
		case "BlockSetFileName":
			cd = BlockSetFileName(data)
		case "BlockSetImageName":
			cd = BlockSetImageName(data)
		case "BlockSetImageWidth":
			cd = BlockSetImageWidth(data)
		case "BlockSetVideoName":
			cd = BlockSetVideoName(data)
		case "BlockSetVideoWidth":
			cd = BlockSetVideoWidth(data)
		case "BlockSetIconName":
			cd = BlockSetIconName(data)
		case "BlockSetLinkTargetBlockId":
			cd = BlockSetLinkTargetBlockId(data)
		case "BlockBookmarkFetch":
			cd = BlockBookmarkFetch(data)
		case "Ping":
			cd = Ping(data)
		case "ProcessCancel":
			cd = ProcessCancel(data)
		default:
			log.Errorf("unknown command type: %s\n", cmd)
		}
		if callback != nil {
			callback(cd)
		}
	}()
}

type MessageHandler interface {
	Handle(b []byte)
}

func CommandMobile(cmd string, data []byte, callback MessageHandler) {
	CommandAsync(cmd, data, callback.Handle)
}
