// Code generated by go-swagger; DO NOT EDIT.

package search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/anyproto/anytype-heart/cmd/anyctl/models"
)

// PostSearchReader is a Reader for the PostSearch structure.
type PostSearchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostSearchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostSearchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPostSearchUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostSearchInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /search] PostSearch", response, response.Code())
	}
}

// NewPostSearchOK creates a PostSearchOK with default headers values
func NewPostSearchOK() *PostSearchOK {
	return &PostSearchOK{}
}

/*
PostSearchOK describes a response with status code 200, with default header values.

List of objects
*/
type PostSearchOK struct {
	Payload *models.PaginationPaginatedResponseObjectObject
}

// IsSuccess returns true when this post search o k response has a 2xx status code
func (o *PostSearchOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post search o k response has a 3xx status code
func (o *PostSearchOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post search o k response has a 4xx status code
func (o *PostSearchOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post search o k response has a 5xx status code
func (o *PostSearchOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post search o k response a status code equal to that given
func (o *PostSearchOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post search o k response
func (o *PostSearchOK) Code() int {
	return 200
}

func (o *PostSearchOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /search][%d] postSearchOK %s", 200, payload)
}

func (o *PostSearchOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /search][%d] postSearchOK %s", 200, payload)
}

func (o *PostSearchOK) GetPayload() *models.PaginationPaginatedResponseObjectObject {
	return o.Payload
}

func (o *PostSearchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PaginationPaginatedResponseObjectObject)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostSearchUnauthorized creates a PostSearchUnauthorized with default headers values
func NewPostSearchUnauthorized() *PostSearchUnauthorized {
	return &PostSearchUnauthorized{}
}

/*
PostSearchUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PostSearchUnauthorized struct {
	Payload *models.UtilUnauthorizedError
}

// IsSuccess returns true when this post search unauthorized response has a 2xx status code
func (o *PostSearchUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post search unauthorized response has a 3xx status code
func (o *PostSearchUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post search unauthorized response has a 4xx status code
func (o *PostSearchUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post search unauthorized response has a 5xx status code
func (o *PostSearchUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post search unauthorized response a status code equal to that given
func (o *PostSearchUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post search unauthorized response
func (o *PostSearchUnauthorized) Code() int {
	return 401
}

func (o *PostSearchUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /search][%d] postSearchUnauthorized %s", 401, payload)
}

func (o *PostSearchUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /search][%d] postSearchUnauthorized %s", 401, payload)
}

func (o *PostSearchUnauthorized) GetPayload() *models.UtilUnauthorizedError {
	return o.Payload
}

func (o *PostSearchUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UtilUnauthorizedError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostSearchInternalServerError creates a PostSearchInternalServerError with default headers values
func NewPostSearchInternalServerError() *PostSearchInternalServerError {
	return &PostSearchInternalServerError{}
}

/*
PostSearchInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type PostSearchInternalServerError struct {
	Payload *models.UtilServerError
}

// IsSuccess returns true when this post search internal server error response has a 2xx status code
func (o *PostSearchInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post search internal server error response has a 3xx status code
func (o *PostSearchInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post search internal server error response has a 4xx status code
func (o *PostSearchInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post search internal server error response has a 5xx status code
func (o *PostSearchInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post search internal server error response a status code equal to that given
func (o *PostSearchInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post search internal server error response
func (o *PostSearchInternalServerError) Code() int {
	return 500
}

func (o *PostSearchInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /search][%d] postSearchInternalServerError %s", 500, payload)
}

func (o *PostSearchInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /search][%d] postSearchInternalServerError %s", 500, payload)
}

func (o *PostSearchInternalServerError) GetPayload() *models.UtilServerError {
	return o.Payload
}

func (o *PostSearchInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UtilServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
