// Code generated by mockery. DO NOT EDIT.

package mock_core

import mock "github.com/stretchr/testify/mock"

// MockTempDirProvider is an autogenerated mock type for the TempDirProvider type
type MockTempDirProvider struct {
	mock.Mock
}

type MockTempDirProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTempDirProvider) EXPECT() *MockTempDirProvider_Expecter {
	return &MockTempDirProvider_Expecter{mock: &_m.Mock}
}

// TempDir provides a mock function with given fields:
func (_m *MockTempDirProvider) TempDir() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TempDir")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockTempDirProvider_TempDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TempDir'
type MockTempDirProvider_TempDir_Call struct {
	*mock.Call
}

// TempDir is a helper method to define mock.On call
func (_e *MockTempDirProvider_Expecter) TempDir() *MockTempDirProvider_TempDir_Call {
	return &MockTempDirProvider_TempDir_Call{Call: _e.mock.On("TempDir")}
}

func (_c *MockTempDirProvider_TempDir_Call) Run(run func()) *MockTempDirProvider_TempDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTempDirProvider_TempDir_Call) Return(_a0 string) *MockTempDirProvider_TempDir_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTempDirProvider_TempDir_Call) RunAndReturn(run func() string) *MockTempDirProvider_TempDir_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTempDirProvider creates a new instance of MockTempDirProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTempDirProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTempDirProvider {
	mock := &MockTempDirProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
