package chatobject

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"testing"

	"github.com/anyproto/any-sync/commonspace/object/tree/objecttree"
	"github.com/stretchr/testify/require"
)

// watermarkAcceptedDivergence: scenarios where the (OrderId,AddSeq) dominance
// model is *intended* to differ from the legacy DAG-ancestor engine — the
// accepted semantic (2026-05-16-chat-read-counter-design.md §5): a genuinely
// concurrent message that was already present and sorts before the seen head
// counts as read. All three are that same class; reviewed and signed off.
// The gate guards against drift (any other divergence = real bug).
var watermarkAcceptedDivergence = map[string]bool{
	"S-concurrent-merge-divergence":          true,
	"S-cat12-dag-ancestor-vs-orderid-prefix": true,
	"S-cat19-msg-mention-concurrent":         true,
}

// TestWatermark_SignOffGate runs the full catalog with the watermark engine vs
// the DAG baseline. Non-accepted scenarios MUST match (real-bug guard);
// accepted scenarios MUST diverge (semantic record). It regenerates
// testdata/watermark_signoff.md — the committed sign-off artifact.
func TestWatermark_SignOffGate(t *testing.T) {
	baseline := map[string][]checkResult{}
	for _, sc := range scenarioCatalog {
		baseline[sc.Name] = runScenario(t, sc)
	}

	prev := engineFactory
	engineFactory = func(t testing.TB, tree objecttree.ObjectTree, onRemove func([]string)) readCounterEngine {
		return newWatermarkEngine(t, tree, onRemove)
	}
	defer func() { engineFactory = prev }()

	var report strings.Builder
	report.WriteString("# Chat Read-Counter — Watermark Sign-off\n\n")
	report.WriteString("Watermark (OrderId+AddSeq dominance) vs legacy DAG-ancestor baseline, full catalog.\n")
	report.WriteString("DIVERGENCE rows are the **accepted** semantic (design §5), not bugs. Regenerated by TestWatermark_SignOffGate.\n\n")

	var diverged, unexpectedMatch []string
	for _, sc := range scenarioCatalog {
		w := runScenario(t, sc)
		base := baseline[sc.Name]
		require.Equalf(t, len(base), len(w), "scenario %s: checkpoint count differs under watermark", sc.Name)
		isDiff := false
		var rows []string
		for i := range base {
			status := "MATCH"
			if base[i].Got != w[i].Got {
				isDiff = true
				status = "DIVERGENCE"
			}
			rows = append(rows, fmt.Sprintf("- step %d · %s · %s · DAG=%d watermark=%d · **%s**",
				base[i].StepIdx, base[i].Device, base[i].Counter.DiffManagerName(), base[i].Got, w[i].Got, status))
		}
		tag := ""
		if isDiff {
			diverged = append(diverged, sc.Name)
			tag = " — ACCEPTED divergence (design §5)"
		} else if watermarkAcceptedDivergence[sc.Name] {
			unexpectedMatch = append(unexpectedMatch, sc.Name)
		}
		report.WriteString(fmt.Sprintf("## %s%s\n\n%s\n\n", sc.Name, tag, strings.Join(rows, "\n")))
	}
	sort.Strings(diverged)
	require.NoError(t, os.WriteFile("testdata/watermark_signoff.md", []byte(report.String()), 0o644))

	for _, name := range diverged {
		require.Truef(t, watermarkAcceptedDivergence[name],
			"scenario %s diverged but is NOT accepted. Diverged set: %v. Review: chat-correct semantic (accept) or bug (fix engine)?",
			name, diverged)
	}
	require.Emptyf(t, unexpectedMatch,
		"accepted scenarios no longer diverge (re-review model/scenario): %v", unexpectedMatch)
}
