// Code generated by mockery. DO NOT EDIT.

package mock_treesyncer

import (
	app "github.com/anyproto/any-sync/app"
	mock "github.com/stretchr/testify/mock"
)

// MockSyncDetailsUpdater is an autogenerated mock type for the SyncDetailsUpdater type
type MockSyncDetailsUpdater struct {
	mock.Mock
}

type MockSyncDetailsUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSyncDetailsUpdater) EXPECT() *MockSyncDetailsUpdater_Expecter {
	return &MockSyncDetailsUpdater_Expecter{mock: &_m.Mock}
}

// Init provides a mock function with given fields: a
func (_m *MockSyncDetailsUpdater) Init(a *app.App) error {
	ret := _m.Called(a)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*app.App) error); ok {
		r0 = rf(a)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSyncDetailsUpdater_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockSyncDetailsUpdater_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - a *app.App
func (_e *MockSyncDetailsUpdater_Expecter) Init(a interface{}) *MockSyncDetailsUpdater_Init_Call {
	return &MockSyncDetailsUpdater_Init_Call{Call: _e.mock.On("Init", a)}
}

func (_c *MockSyncDetailsUpdater_Init_Call) Run(run func(a *app.App)) *MockSyncDetailsUpdater_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*app.App))
	})
	return _c
}

func (_c *MockSyncDetailsUpdater_Init_Call) Return(err error) *MockSyncDetailsUpdater_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSyncDetailsUpdater_Init_Call) RunAndReturn(run func(*app.App) error) *MockSyncDetailsUpdater_Init_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with given fields:
func (_m *MockSyncDetailsUpdater) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockSyncDetailsUpdater_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockSyncDetailsUpdater_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockSyncDetailsUpdater_Expecter) Name() *MockSyncDetailsUpdater_Name_Call {
	return &MockSyncDetailsUpdater_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockSyncDetailsUpdater_Name_Call) Run(run func()) *MockSyncDetailsUpdater_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSyncDetailsUpdater_Name_Call) Return(name string) *MockSyncDetailsUpdater_Name_Call {
	_c.Call.Return(name)
	return _c
}

func (_c *MockSyncDetailsUpdater_Name_Call) RunAndReturn(run func() string) *MockSyncDetailsUpdater_Name_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSpaceDetails provides a mock function with given fields: existing, missing, spaceId
func (_m *MockSyncDetailsUpdater) UpdateSpaceDetails(existing []string, missing []string, spaceId string) {
	_m.Called(existing, missing, spaceId)
}

// MockSyncDetailsUpdater_UpdateSpaceDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSpaceDetails'
type MockSyncDetailsUpdater_UpdateSpaceDetails_Call struct {
	*mock.Call
}

// UpdateSpaceDetails is a helper method to define mock.On call
//   - existing []string
//   - missing []string
//   - spaceId string
func (_e *MockSyncDetailsUpdater_Expecter) UpdateSpaceDetails(existing interface{}, missing interface{}, spaceId interface{}) *MockSyncDetailsUpdater_UpdateSpaceDetails_Call {
	return &MockSyncDetailsUpdater_UpdateSpaceDetails_Call{Call: _e.mock.On("UpdateSpaceDetails", existing, missing, spaceId)}
}

func (_c *MockSyncDetailsUpdater_UpdateSpaceDetails_Call) Run(run func(existing []string, missing []string, spaceId string)) *MockSyncDetailsUpdater_UpdateSpaceDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string), args[1].([]string), args[2].(string))
	})
	return _c
}

func (_c *MockSyncDetailsUpdater_UpdateSpaceDetails_Call) Return() *MockSyncDetailsUpdater_UpdateSpaceDetails_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSyncDetailsUpdater_UpdateSpaceDetails_Call) RunAndReturn(run func([]string, []string, string)) *MockSyncDetailsUpdater_UpdateSpaceDetails_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSyncDetailsUpdater creates a new instance of MockSyncDetailsUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSyncDetailsUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSyncDetailsUpdater {
	mock := &MockSyncDetailsUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
