// Package udpprobe answers "is anything listening on this UDP port?" for
// loopback and local-network addresses, without waiting for a QUIC handshake
// timeout.
//
// The trick: a connected UDP socket (net.DialUDP) delivers the kernel's ICMP
// port-unreachable back to the application as ECONNREFUSED on the next
// read/write. On loopback the unreachable is generated by the local kernel, so
// a dead port is reported within milliseconds; on a LAN it arrives if the peer
// host emits ICMP (most do). The signal is asymmetric by nature: a refusal
// proves the port is dead, but silence proves nothing — a live QUIC server
// silently drops our garbage datagram, and a firewall may drop it too. Hence
// the only two results are Dead and Inconclusive; there is no Alive.
//
// The unconnected sockets any-sync uses for QUIC dials never see this error,
// which is why a dial to a dead local port otherwise burns the full handshake
// timeout (see GO-7411).
package udpprobe

import (
	"context"
	"net"
	"sync"
	"time"
)

type Result int

const (
	// Inconclusive means the probe learned nothing: the port may be alive
	// (listeners drop non-protocol datagrams silently) or the refusal signal
	// was lost. Callers must treat it as possibly alive and dial normally.
	Inconclusive Result = iota
	// Dead means the kernel reported the port unreachable (ECONNREFUSED /
	// WSAECONNRESET): provably nothing is listening.
	Dead
)

// defaultTimeout bounds one probe when the caller's context carries no
// deadline. A dead loopback port reports in single-digit milliseconds; the
// budget only matters in the inconclusive (silent-drop) case.
const defaultTimeout = 300 * time.Millisecond

// probePayload is a single zero byte: as a QUIC packet it parses as a short
// header with no matching connection, so a live listener drops it without any
// side effect.
var probePayload = []byte{0}

// Probeable reports whether addr ("ip:port") is one the probe's verdict can be
// trusted for: loopback, RFC1918 private, or link-local — paths where ICMP
// port-unreachable is not filtered by intermediaries. Hostnames and public IPs
// are not probeable.
func Probeable(addr string) bool {
	host, _, err := net.SplitHostPort(addr)
	if err != nil {
		return false
	}
	ip := net.ParseIP(host)
	if ip == nil {
		return false
	}
	return ip.IsLoopback() || ip.IsPrivate() || ip.IsLinkLocalUnicast()
}

// Probe checks a single "ip:port" address. The context deadline bounds the
// whole probe (defaultTimeout when absent). Any failure to even set the probe
// up degrades to Inconclusive — this function must never produce a false Dead.
func Probe(ctx context.Context, addr string) Result {
	if !Probeable(addr) {
		return Inconclusive
	}
	udpAddr, err := net.ResolveUDPAddr("udp", addr)
	if err != nil {
		return Inconclusive
	}
	conn, err := net.DialUDP("udp", nil, udpAddr)
	if err != nil {
		if isRefused(err) {
			return Dead
		}
		return Inconclusive
	}
	defer conn.Close()
	// On Windows the Go runtime disables SIO_UDP_CONNRESET on every UDP
	// socket, suppressing exactly the error this probe exists to observe;
	// re-enable it for this socket only (no-op elsewhere).
	if err = enableRefusedReports(conn); err != nil {
		return Inconclusive
	}
	deadline, ok := ctx.Deadline()
	if !ok {
		deadline = time.Now().Add(defaultTimeout)
	}
	if err = conn.SetDeadline(deadline); err != nil {
		return Inconclusive
	}
	if _, err = conn.Write(probePayload); err != nil {
		// macOS reports a dead loopback port synchronously on the send
		if isRefused(err) {
			return Dead
		}
		return Inconclusive
	}
	// A blocked read on a connected UDP socket is woken by the queued socket
	// error the moment the ICMP arrives, so a single read covers the whole
	// window until the deadline.
	buf := make([]byte, 64)
	if _, err = conn.Read(buf); err != nil && isRefused(err) {
		return Dead
	}
	return Inconclusive
}

// AllDead reports whether every address in addrs is provably dead. It is the
// "safe to skip the dial" predicate: false whenever any address is alive,
// inconclusive, or not probeable at all (an empty or unverifiable list proves
// nothing). Addresses are probed concurrently under one shared deadline.
func AllDead(ctx context.Context, addrs []string) bool {
	probeable := make([]string, 0, len(addrs))
	for _, addr := range addrs {
		if !Probeable(addr) {
			return false
		}
		probeable = append(probeable, addr)
	}
	if len(probeable) == 0 {
		return false
	}
	if _, ok := ctx.Deadline(); !ok {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, defaultTimeout)
		defer cancel()
	}
	results := make([]Result, len(probeable))
	var wg sync.WaitGroup
	for i, addr := range probeable {
		wg.Add(1)
		go func(i int, addr string) {
			defer wg.Done()
			results[i] = Probe(ctx, addr)
		}(i, addr)
	}
	wg.Wait()
	for _, r := range results {
		if r != Dead {
			return false
		}
	}
	return true
}
