{
 "title": "Badger",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "LSM Size",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "badger_size_bytes_lsm", "legendFormat": "{{ path }}" }
     ]
    },
    {
     "title": "Value Log Size",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "badger_size_bytes_vlog", "legendFormat": "{{ path }}" }
     ]
    }
   ]
  },
  {
   "title": "User",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Puts by user",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(badger_put_num_user[1m]))"
      },
      {}
     ]
    },
    {
     "title": "Gets by user",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(badger_get_num_user[1m]))"
      },
      {},
      {}
     ]
    },
    {
     "title": "Bytes writes by user",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(badger_write_bytes_user[1m]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Gets with result by user",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "irate(badger_get_with_result_num_user[1m])"
      },
      {},
      {}
     ]
    },
    {
     "title": "Iterators by user",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(badger_iterator_num_user[1m]))"
      },
      {},
      {}
     ]
    }
   ]
  },
  {
   "title": "VLog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "value log writes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "expr": "rate(badger_write_num_vlog[$__interval])"
      },
      {}
     ]
    },
    {
     "title": "bytes write vlog",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(badger_write_bytes_vlog[1m]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "VLog read bytes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(badger_read_bytes_vlog[1m]))",
       "legendFormat": "total"
      }
     ]
    }
   ]
  },
  {
   "title": "LSM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "LSM gets",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "rps" } },
     "targets": [
      {
       "expr": "rate(badger_get_num_lsm{job=\"mw\"}[$__interval])",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "Memtable gets",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(badger_get_num_memtable[1m]))"
      },
      {}
     ]
    },
    {
     "title": "LSM bytes read",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(badger_read_bytes_lsm[1m]))",
       "legendFormat": "total"
      },
      {}
     ]
    },
    {
     "title": "l0 bytes writes ",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(badger_write_bytes_l0[1m]))",
       "legendFormat": "total"
      },
      {},
      {},
      {}
     ]
    },
    {
     "title": "bloom hits",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(badger_hit_num_lsm_bloom_filter[1m])) by (result)",
       "legendFormat": "{{ result }}"
      }
     ]
    },
    {
     "title": "tables compacting",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "badger_compaction_current_num_lsm"
      }
     ]
    },
    {
     "title": "pending writes memtable",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "badger_write_pending_num_memtable",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "bytes write compaction",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(badger_write_bytes_compaction[1m]))",
       "legendFormat": "total"
      }
     ]
    }
   ]
  }
 ]
}