{
 "title": "Bleve",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Stat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total introduced segments batch",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bleve_totintroducedsegmentsbatch"
      }
     ]
    },
    {
     "title": "Total introduced items",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totintroduceditems" }
     ]
    },
    {
     "title": "Total updates",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totupdates" }
     ]
    },
    {
     "title": "Total analysis time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      { "expr": "bleve_totanalysistime" }
     ]
    },
    {
     "title": "Total deletes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totdeletes" }
     ]
    },
    {
     "title": "Total batches",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totbatches" }
     ]
    },
    {
     "title": "Current files ineligible for removal",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bleve_curfilesineligibleforremoval"
      }
     ]
    },
    {
     "title": "Total batches empty",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totbatchesempty" }
     ]
    },
    {
     "title": "Total introduced segments merge",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bleve_totintroducedsegmentsmerge"
      }
     ]
    },
    {
     "title": "Total on errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totonerrors" }
     ]
    }
   ]
  },
  { "title": "Search", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Total searches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bleve_totsearches" }
   ]
  },
  {
   "title": "Total bytes read at query time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "bleve_totbytesreadatquerytime" }
   ]
  },
  {
   "title": "Total searchtime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    { "expr": "bleve_totsearchtime" }
   ]
  },
  {
   "title": "Total term searchers finished",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bleve_tottermsearchersfinished" }
   ]
  },
  {
   "title": "Total term searchers started",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bleve_tottermsearchersstarted" }
   ]
  },
  {
   "title": "Indexation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total index time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      { "expr": "bleve_totindextime" }
     ]
    },
    {
     "title": "Total indexed plain text bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "bleve_totindexedplaintextbytes" }
     ]
    },
    {
     "title": "Total bytes written at index time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "bleve_totbyteswrittenatindextime"
      }
     ]
    }
   ]
  },
  {
   "title": "Persistence",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total introduce persist end",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totintroducepersistend" }
     ]
    },
    {
     "title": "Total introduce persist beg",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totintroducepersistbeg" }
     ]
    },
    {
     "title": "Total persisted segments",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totpersistedsegments" }
     ]
    },
    {
     "title": "Total items to persist",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totitemstopersist" }
     ]
    },
    {
     "title": "Total persister nap pause completed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bleve_totpersisternappausecompleted"
      }
     ]
    },
    {
     "title": "Total persisted items",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totpersisteditems" }
     ]
    },
    {
     "title": "Total persister slow merger resume",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bleve_totpersisterslowmergerresume"
      }
     ]
    },
    {
     "title": "Total persister merger nap break",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bleve_totpersistermergernapbreak"
      }
     ]
    },
    {
     "title": "Total persist loop end",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totpersistloopend" }
     ]
    },
    {
     "title": "Total persister slow merger pause",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bleve_totpersisterslowmergerpause"
      }
     ]
    },
    {
     "title": "Total persist loop progress",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totpersistloopprogress" }
     ]
    },
    {
     "title": "Total persist loop beg",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totpersistloopbeg" }
     ]
    },
    {
     "title": "Total persist loop wait notified",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bleve_totpersistloopwaitnotified"
      }
     ]
    },
    {
     "title": "Total persist loop err",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totpersistlooperr" }
     ]
    },
    {
     "title": "Total persist loop wait",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totpersistloopwait" }
     ]
    }
   ]
  },
  {
   "title": "File Merge",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total file merge force ops completed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bleve_totfilemergeforceopscompleted"
      }
     ]
    },
    {
     "title": "Total file merge force ops started",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bleve_totfilemergeforceopsstarted"
      }
     ]
    },
    {
     "title": "Total file merge introductions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bleve_totfilemergeintroductions"
      }
     ]
    },
    {
     "title": "Total file merge introductions done",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bleve_totfilemergeintroductionsdone"
      }
     ]
    },
    {
     "title": "Total file merge introductions obsoleted",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bleve_totfilemergeintroductionsobsoleted"
      }
     ]
    },
    {
     "title": "Total file merge introductions skipped",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bleve_totfilemergeintroductionsskipped"
      }
     ]
    },
    {
     "title": "Total file merge loop beg",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totfilemergeloopbeg" }
     ]
    },
    {
     "title": "Total file merge loop end",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totfilemergeloopend" }
     ]
    },
    {
     "title": "Total file merge loop err",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totfilemergelooperr" }
     ]
    },
    {
     "title": "Total file merge plan",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totfilemergeplan" }
     ]
    },
    {
     "title": "Total file merge plan ok",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totfilemergeplanok" }
     ]
    },
    {
     "title": "Total file merge plan err",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totfilemergeplanerr" }
     ]
    },
    {
     "title": "Total file merge plan tasks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totfilemergeplantasks" }
     ]
    },
    {
     "title": "Total file merge plan none",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totfilemergeplannone" }
     ]
    },
    {
     "title": "Total file merge plan tasks done",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bleve_totfilemergeplantasksdone"
      }
     ]
    },
    {
     "title": "Total file merge plan tasks err",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totfilemergeplantaskserr" }
     ]
    },
    {
     "title": "Total file merge plan tasks segments",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bleve_totfilemergeplantaskssegments"
      }
     ]
    },
    {
     "title": "Total file merge plan tasks segments empty",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bleve_totfilemergeplantaskssegmentsempty"
      }
     ]
    },
    {
     "title": "Total file merge segments",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totfilemergesegments" }
     ]
    },
    {
     "title": "Total file merge segments empty",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bleve_totfilemergesegmentsempty"
      }
     ]
    },
    {
     "title": "Total file merge written bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totfilemergewrittenbytes" }
     ]
    },
    {
     "title": "Total file merge zap beg",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totfilemergezapbeg" }
     ]
    },
    {
     "title": "Total file merge zap end",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totfilemergezapend" }
     ]
    },
    {
     "title": "Total file merge zap introduction time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bleve_totfilemergezapintroductiontime"
      }
     ]
    },
    {
     "title": "Total file merge zap time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totfilemergezaptime" }
     ]
    }
   ]
  },
  {
   "title": "Memory merge",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total mem merge beg",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totmemmergebeg" }
     ]
    },
    {
     "title": "Total mem merge done",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totmemmergedone" }
     ]
    },
    {
     "title": "Total mem merge err",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totmemmergeerr" }
     ]
    },
    {
     "title": "Total mem merge segments",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totmemmergesegments" }
     ]
    },
    {
     "title": "Total mem merge zap beg",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totmemmergezapbeg" }
     ]
    },
    {
     "title": "Total mem merge zap end",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totmemmergezapend" }
     ]
    },
    {
     "title": "Total mem merge zap time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bleve_totmemmergezaptime" }
     ]
    }
   ]
  },
  { "title": "others", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Total batch intro time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bleve_totbatchintrotime" }
   ]
  },
  {
   "title": "Total event trigger completed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bleve_toteventtriggercompleted" }
   ]
  },
  {
   "title": "Current root epoch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bleve_currootepoch" }
   ]
  },
  {
   "title": "Total event trigger started",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bleve_toteventtriggerstarted" }
   ]
  },
  {
   "title": "Total introduce loop",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bleve_totintroduceloop" }
   ]
  },
  {
   "title": "Total file segments at root",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bleve_totfilesegmentsatroot" }
   ]
  },
  {
   "title": "Total introduce merge end",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bleve_totintroducemergeend" }
   ]
  },
  {
   "title": "Total introduce merge beg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bleve_totintroducemergebeg" }
   ]
  },
  {
   "title": "Total introduce revert end",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bleve_totintroducerevertend" }
   ]
  },
  {
   "title": "Total introduce revert beg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bleve_totintroducerevertbeg" }
   ]
  },
  {
   "title": "Total introduce segment end",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bleve_totintroducesegmentend" }
   ]
  },
  {
   "title": "Total introduce segment beg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bleve_totintroducesegmentbeg" }
   ]
  },
  {
   "title": "Total snapshots removed from meta store",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bleve_totsnapshotsremovedfrommetastore"
    }
   ]
  },
  {
   "title": "Total memory segments at root",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bleve_totmemorysegmentsatroot" }
   ]
  }
 ]
}