{
 "title": "MW",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Served threads",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "anytype_mw_threads_total" }
   ]
  },
  {
   "title": "Served threads",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "anytype_mw_threads_total" }
   ]
  },
  {
   "title": "Changes received",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "anytype_mw_change_received" }
   ]
  },
  {
   "title": "External thread handling duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, anytype_mw_external_thread_handling_seconds_bucket)",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.75, anytype_mw_external_thread_handling_seconds_bucket)",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.95, anytype_mw_external_thread_handling_seconds_bucket)",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, anytype_mw_external_thread_handling_seconds_bucket)",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "Created thread addReplicator duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, anytype_mw_thread_add_replicator_seconds_bucket)",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.75, anytype_mw_thread_add_replicator_seconds_bucket)",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.95, anytype_mw_thread_add_replicator_seconds_bucket)",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, anytype_mw_thread_add_replicator_seconds_bucket)",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "External threads not proceed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "anytype_mw_external_thread_received - anytype_mw_external_thread_handling_seconds_count"
    }
   ]
  },
  {
   "title": "External thread handling attempts per thread",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "anytype_mw_external_thread_handling_attempts/ anytype_mw_external_thread_received"
    }
   ]
  },
  {
   "title": "External thread handling rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(anytype_mw_external_thread_handling_seconds_count[5m]))"
    }
   ]
  },
  {
   "title": "Details index updated",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "anytype_mw_details_index_updated"
    }
   ]
  },
  {
   "title": "Relations index updated",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "anytype_mw_relations_index_updated"
    }
   ]
  },
  {
   "title": "Fulltext index updated",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "anytype_mw_fulltext_index_updated"
    }
   ]
  }
 ]
}