package namegenerator

func getAdjectives() []string {
	return []string{
		// Colors
		"Red", "Blue", "Green", "Yellow", "Purple", "Orange", "Pink", "Brown", "Black", "White",
		"Gray", "Silver", "Gold", "Turquoise", "Magenta", "Cyan", "Lime", "Indigo", "Violet", "Crimson",
		"Scarlet", "Ruby", "Emerald", "Sapphire", "Amber", "Coral", "Ivory", "Jade", "Maroon", "Navy",
		"Olive", "Teal", "Beige", "Tan", "Bronze", "Copper", "Platinum", "Rose", "Peach", "Lavender",
		"Mint", "Aqua", "Salmon", "Khaki", "Plum", "Lilac", "Fuchsia", "Mauve", "Burgundy", "Cerulean",

		// Shapes & Sizes
		"Round", "Square", "Tiny", "Small", "Large", "Huge", "Giant", "Massive", "Miniature", "Compact",
		"Circular", "Triangular", "Oval", "Rectangular", "Curved", "Straight", "Narrow", "Wide", "Tall", "Short",
		"Thick", "Thin", "Broad", "Slim", "Flat", "Rounded", "Angular", "Smooth", "Sharp", "Pointed",

		// Positive Character Qualities
		"Brave", "Kind", "Gentle", "Wise", "Smart", "Clever", "Bright", "Cheerful", "Happy", "Joyful",
		"Peaceful", "Calm", "Serene", "Patient", "Loyal", "Honest", "Trustworthy", "Reliable", "Caring", "Loving",
		"Compassionate", "Generous", "Humble", "Gracious", "Polite", "Courteous", "Respectful", "Thoughtful", "Considerate", "Helpful",
		"Supportive", "Encouraging", "Inspiring", "Motivating", "Creative", "Artistic", "Talented", "Skilled", "Gifted", "Brilliant",
		"Innovative", "Inventive", "Resourceful", "Adaptable", "Flexible", "Resilient", "Strong", "Powerful", "Mighty", "Bold",
		"Courageous", "Fearless", "Confident", "Determined", "Persistent", "Ambitious", "Hardworking", "Dedicated", "Committed", "Focused",
		"Disciplined", "Organized", "Efficient", "Productive", "Successful", "Victorious", "Triumphant", "Winning", "Champion", "Elite",
		"Premium", "Superior", "Excellent", "Outstanding", "Remarkable", "Exceptional", "Extraordinary", "Magnificent", "Marvelous", "Wonderful",
		"Amazing", "Incredible", "Fantastic", "Fabulous", "Spectacular", "Stunning", "Breathtaking", "Dazzling", "Radiant", "Luminous",
		"Glowing", "Shining", "Sparkling", "Gleaming", "Brilliant", "Vivid", "Vibrant", "Lively", "Energetic", "Dynamic",
		"Active", "Spirited", "Enthusiastic", "Passionate", "Zealous", "Devoted", "Faithful", "Dedicated", "Sincere", "Genuine",
		"Authentic", "True", "Real", "Pure", "Clean", "Fresh", "New", "Modern", "Contemporary", "Stylish",
		"Fashionable", "Trendy", "Cool", "Hip", "Chic", "Elegant", "Graceful", "Refined", "Sophisticated", "Classy",
		"Noble", "Majestic", "Royal", "Regal", "Imperial", "Divine", "Sacred", "Holy", "Blessed", "Fortunate",
		"Lucky", "Charmed", "Magical", "Mystical", "Enchanted", "Bewitching", "Captivating", "Alluring", "Attractive", "Beautiful",
		"Pretty", "Lovely", "Gorgeous", "Stunning", "Handsome", "Adorable", "Cute", "Sweet", "Charming", "Delightful",
		"Pleasant", "Enjoyable", "Fun", "Playful", "Amusing", "Entertaining", "Witty", "Humorous", "Funny", "Comical",
		"Silly", "Quirky", "Unique", "Special", "Rare", "Precious", "Valuable", "Priceless", "Treasured", "Cherished",
		"Beloved", "Dear", "Darling", "Adorable", "Endearing", "Lovable", "Huggable", "Cuddly", "Snuggly", "Cozy",
		"Comfortable", "Relaxed", "Easygoing", "Laid-back", "Mellow", "Tranquil", "Peaceful", "Quiet", "Silent", "Still",
		"Stable", "Steady", "Consistent", "Constant", "Eternal", "Everlasting", "Timeless", "Ageless", "Immortal", "Infinite",
		"Boundless", "Limitless", "Endless", "Vast", "Immense", "Enormous", "Colossal", "Titanic", "Gigantic", "Monumental",
		"Epic", "Legendary", "Heroic", "Valiant", "Gallant", "Chivalrous", "Knightly", "Princely", "Kingly", "Queenly",
		"Majestic", "Stately", "Dignified", "Composed", "Poised", "Balanced", "Harmonious", "Symmetrical", "Perfect", "Flawless",
		"Immaculate", "Pristine", "Spotless", "Clean", "Neat", "Tidy", "Organized", "Structured", "Systematic", "Methodical",
		"Logical", "Rational", "Sensible", "Reasonable", "Practical", "Pragmatic", "Realistic", "Grounded", "Down-to-earth", "Humble",
		"Modest", "Unpretentious", "Simple", "Plain", "Natural", "Organic", "Wild", "Free", "Independent", "Self-reliant",
		"Autonomous", "Sovereign", "Liberated", "Emancipated", "Unbound", "Unrestricted", "Unlimited", "Unconfined", "Open", "Accessible",
		"Available", "Ready", "Prepared", "Equipped", "Armed", "Fortified", "Protected", "Secure", "Safe", "Guarded",
		"Shielded", "Defended", "Invincible", "Unbeatable", "Unstoppable", "Irresistible", "Compelling", "Convincing", "Persuasive", "Influential",
		"Impressive", "Imposing", "Commanding", "Authoritative", "Powerful", "Forceful", "Vigorous", "Robust", "Sturdy", "Solid",
		"Firm", "Hard", "Tough", "Durable", "Lasting", "Enduring", "Persistent", "Tenacious", "Determined", "Resolute",
		"Unwavering", "Steadfast", "Loyal", "Faithful", "Devoted", "Committed", "Dedicated", "Zealous", "Passionate", "Fervent",
		"Intense", "Deep", "Profound", "Meaningful", "Significant", "Important", "Essential", "Vital", "Critical", "Crucial",
		"Key", "Primary", "Main", "Chief", "Principal", "Leading", "Top", "Supreme", "Ultimate", "Final",
		"Complete", "Total", "Whole", "Full", "Entire", "Comprehensive", "Thorough", "Detailed", "Precise", "Exact",
		"Accurate", "Correct", "Right", "True", "Honest", "Truthful", "Sincere", "Genuine", "Authentic", "Real",
		"Actual", "Concrete", "Tangible", "Solid", "Substantial", "Material", "Physical", "Visible", "Apparent", "Obvious",
		"Clear", "Transparent", "Translucent", "Lucid", "Bright", "Luminous", "Radiant", "Glowing", "Shining", "Sparkling",
		"Glittering", "Twinkling", "Flickering", "Flashing", "Gleaming", "Glistening", "Dazzling", "Blazing", "Burning", "Fiery",
		"Hot", "Warm", "Heated", "Thermal", "Tropical", "Sunny", "Bright", "Light", "Illuminated", "Lit",
		"Enlightened", "Informed", "Educated", "Learned", "Scholarly", "Academic", "Intellectual", "Mental", "Cerebral", "Brainy",
		"Intelligent", "Smart", "Clever", "Shrewd", "Astute", "Sharp", "Quick", "Fast", "Rapid", "Swift",
		"Speedy", "Hasty", "Urgent", "Immediate", "Instant", "Instantaneous", "Sudden", "Abrupt", "Unexpected", "Surprising",
		"Astonishing", "Startling", "Shocking", "Amazing", "Incredible", "Unbelievable", "Extraordinary", "Phenomenal", "Miraculous", "Wondrous",
		"Marvelous", "Fantastic", "Fabulous", "Magnificent", "Splendid", "Glorious", "Sublime", "Superb", "Excellent", "Outstanding",
		"Exceptional", "Remarkable", "Notable", "Noteworthy", "Memorable", "Unforgettable", "Everlasting", "Eternal", "Immortal", "Legendary",
		"Mythical", "Fabled", "Storied", "Historic", "Ancient", "Old", "Aged", "Mature", "Seasoned", "Experienced",
		"Veteran", "Expert", "Professional", "Skilled", "Talented", "Gifted", "Capable", "Able", "Competent", "Qualified",
		"Certified", "Licensed", "Authorized", "Approved", "Endorsed", "Recommended", "Suggested", "Advised", "Counseled", "Guided",
		"Directed", "Led", "Headed", "Managed", "Supervised", "Overseen", "Monitored", "Watched", "Observed", "Noticed",
		"Seen", "Viewed", "Looked", "Gazed", "Stared", "Focused", "Concentrated", "Centered", "Balanced", "Stable",
		"Steady", "Constant", "Regular", "Normal", "Standard", "Typical", "Usual", "Common", "Ordinary", "Average",
		"Medium", "Middle", "Central", "Core", "Inner", "Interior", "Internal", "Private", "Personal", "Individual",
		"Unique", "Distinctive", "Special", "Particular", "Specific", "Exact", "Precise", "Definite", "Certain", "Sure",
		"Confident", "Assured", "Guaranteed", "Promised", "Pledged", "Sworn", "Vowed", "Committed", "Bound", "Obligated",
		"Responsible", "Accountable", "Liable", "Answerable", "Dependable", "Reliable", "Trustworthy", "Credible", "Believable", "Plausible",
		"Reasonable", "Logical", "Sensible", "Practical", "Useful", "Helpful", "Beneficial", "Advantageous", "Favorable", "Positive",
		"Good", "Great", "Fine", "Nice", "Pleasant", "Agreeable", "Acceptable", "Satisfactory", "Adequate", "Sufficient",
		"Enough", "Plenty", "Abundant", "Plentiful", "Rich", "Wealthy", "Prosperous", "Successful", "Thriving", "Flourishing",
		"Blooming", "Blossoming", "Growing", "Developing", "Expanding", "Increasing", "Rising", "Ascending", "Climbing", "Soaring",
		"Flying", "Floating", "Drifting", "Flowing", "Streaming", "Running", "Moving", "Traveling", "Journeying", "Wandering",
		"Roaming", "Exploring", "Discovering", "Finding", "Locating", "Spotting", "Detecting", "Identifying", "Recognizing", "Knowing",
		"Understanding", "Comprehending", "Grasping", "Realizing", "Appreciating", "Valuing", "Treasuring", "Prizing", "Honoring", "Respecting",
		"Admiring", "Adoring", "Loving", "Caring", "Nurturing", "Protecting", "Guarding", "Defending", "Supporting", "Helping",
		"Assisting", "Aiding", "Serving", "Contributing", "Participating", "Joining", "Connecting", "Linking", "Bonding", "Uniting",
		"Combining", "Merging", "Blending", "Mixing", "Stirring", "Shaking", "Vibrating", "Trembling", "Quivering", "Shivering",
		"Chilling", "Cooling", "Freezing", "Icy", "Frosty", "Snowy", "Wintry", "Cold", "Crisp", "Fresh",
		"Clean", "Pure", "Clear", "Transparent", "Honest", "Open", "Frank", "Direct", "Straightforward", "Upfront",
		"Candid", "Sincere", "Genuine", "Authentic", "Real", "True", "Actual", "Factual", "Accurate", "Correct",
		"Right", "Proper", "Appropriate", "Suitable", "Fitting", "Perfect", "Ideal", "Model", "Exemplary", "Outstanding",
		"Excellent", "Superior", "Premium", "Elite", "Select", "Choice", "Preferred", "Favorite", "Beloved", "Cherished",
		"Treasured", "Precious", "Valuable", "Priceless", "Invaluable", "Worthwhile", "Meaningful", "Significant", "Important", "Essential",
		"Vital", "Critical", "Crucial", "Key", "Primary", "Main", "Chief", "Principal", "Leading", "Top",
		"Supreme", "Ultimate", "Final", "Last", "Ending", "Concluding", "Finishing", "Completing", "Fulfilling", "Satisfying",
		"Rewarding", "Gratifying", "Pleasing", "Delightful", "Enjoyable", "Fun", "Entertaining", "Amusing", "Funny", "Humorous",
		"Witty", "Clever", "Smart", "Intelligent", "Wise", "Sage", "Learned", "Educated", "Informed", "Knowledgeable",
		"Experienced", "Skilled", "Talented", "Gifted", "Capable", "Able", "Competent", "Qualified", "Expert", "Professional",
		"Masterful", "Skilled", "Adept", "Proficient", "Accomplished", "Achieved", "Successful", "Victorious", "Triumphant", "Winning",
		"Champion", "Hero", "Heroic", "Brave", "Courageous", "Fearless", "Bold", "Daring", "Adventurous", "Exciting",
		"Thrilling", "Exhilarating", "Stimulating", "Inspiring", "Motivating", "Encouraging", "Uplifting", "Elevating", "Enlightening", "Illuminating",
		"Brightening", "Lightening", "Clearing", "Opening", "Expanding", "Broadening", "Widening", "Stretching", "Extending", "Reaching",
		"Touching", "Feeling", "Sensing", "Perceiving", "Noticing", "Observing", "Watching", "Seeing", "Viewing", "Looking",
		"Gazing", "Staring", "Focusing", "Concentrating", "Centering", "Balancing", "Stabilizing", "Steadying", "Calming", "Soothing",
		"Relaxing", "Resting", "Sleeping", "Dreaming", "Hoping", "Wishing", "Wanting", "Desiring", "Longing", "Yearning",
		"Craving", "Seeking", "Searching", "Hunting", "Pursuing", "Chasing", "Following", "Tracking", "Tracing", "Trailing",
		"Leading", "Guiding", "Directing", "Steering", "Navigating", "Piloting", "Driving", "Operating", "Running", "Managing",
		"Controlling", "Commanding", "Ruling", "Governing", "Administering", "Supervising", "Overseeing", "Monitoring", "Watching", "Guarding",
		"Protecting", "Defending", "Shielding", "Covering", "Hiding", "Concealing", "Masking", "Veiling", "Screening", "Filtering",
		"Purifying", "Cleaning", "Washing", "Bathing", "Refreshing", "Renewing", "Reviving", "Restoring", "Repairing", "Fixing",
		"Mending", "Healing", "Curing", "Treating", "Caring", "Nurturing", "Fostering", "Raising", "Growing", "Developing",
		"Building", "Constructing", "Creating", "Making", "Producing", "Manufacturing", "Crafting", "Forming", "Shaping", "Molding",
		"Designing", "Planning", "Organizing", "Arranging", "Ordering", "Sorting", "Classifying", "Categorizing", "Grouping", "Collecting",
		"Gathering", "Assembling", "Combining", "Joining", "Connecting", "Linking", "Bonding", "Uniting", "Merging", "Blending",
		"Mixing", "Stirring", "Shaking", "Moving", "Shifting", "Changing", "Transforming", "Converting", "Turning", "Rotating",
		"Spinning", "Twisting", "Curving", "Bending", "Folding", "Wrapping", "Covering", "Enclosing", "Surrounding", "Embracing",
		"Hugging", "Holding", "Grasping", "Gripping", "Clutching", "Squeezing", "Pressing", "Pushing", "Pulling", "Dragging",
		"Lifting", "Raising", "Elevating", "Boosting", "Promoting", "Advancing", "Progressing", "Improving", "Enhancing", "Upgrading",
		"Bettering", "Perfecting", "Polishing", "Refining", "Smoothing", "Softening", "Gentling", "Calming", "Quieting", "Silencing",
		"Muting", "Dampening", "Dulling", "Dimming", "Fading", "Vanishing", "Disappearing", "Evaporating", "Dissolving", "Melting",
		"Thawing", "Warming", "Heating", "Burning", "Blazing", "Flaming", "Glowing", "Shining", "Sparkling", "Glittering",
		"Twinkling", "Flickering", "Flashing", "Blinking", "Winking", "Signaling", "Indicating", "Showing", "Displaying", "Exhibiting",
		"Presenting", "Offering", "Giving", "Providing", "Supplying", "Delivering", "Serving", "Feeding", "Nourishing", "Sustaining",
		"Supporting", "Backing", "Endorsing", "Approving", "Accepting", "Welcoming", "Greeting", "Meeting", "Encountering", "Discovering",
		"Finding", "Locating", "Spotting", "Detecting", "Identifying", "Recognizing", "Remembering", "Recalling", "Reminiscing", "Reflecting",
		"Thinking", "Considering", "Pondering", "Contemplating", "Meditating", "Praying", "Hoping", "Believing", "Trusting", "Relying",
		"Depending", "Counting", "Calculating", "Computing", "Measuring", "Weighing", "Balancing", "Comparing", "Contrasting", "Differentiating",
		"Distinguishing", "Separating", "Dividing", "Splitting", "Breaking", "Cracking", "Snapping", "Popping", "Bursting", "Exploding",
		"Erupting", "Emerging", "Appearing", "Manifesting", "Materializing", "Forming", "Developing", "Growing", "Expanding", "Increasing",
		"Multiplying", "Doubling", "Tripling", "Quadrupling", "Magnifying", "Amplifying", "Strengthening", "Reinforcing", "Fortifying", "Securing",
		"Protecting", "Safeguarding", "Preserving", "Maintaining", "Sustaining", "Continuing", "Persisting", "Enduring", "Lasting", "Remaining",
		"Staying", "Dwelling", "Residing", "Living", "Existing", "Being", "Becoming", "Transforming", "Changing", "Evolving",
	}
}

func getNouns() []string {
	return []string{
		// Cute Animals
		"Kitten", "Puppy", "Bunny", "Hamster", "Squirrel", "Chipmunk", "Hedgehog", "Ferret", "Guinea", "Chinchilla",
		"Otter", "Seal", "Dolphin", "Whale", "Panda", "Koala", "Sloth", "Lemur", "Monkey", "Raccoon",
		"Fox", "Wolf", "Bear", "Tiger", "Lion", "Cheetah", "Leopard", "Jaguar", "Lynx", "Bobcat",
		"Deer", "Elk", "Moose", "Caribou", "Antelope", "Gazelle", "Zebra", "Giraffe", "Elephant", "Hippo",
		"Rhino", "Buffalo", "Bison", "Yak", "Llama", "Alpaca", "Camel", "Horse", "Pony", "Donkey",
		"Mule", "Goat", "Sheep", "Lamb", "Pig", "Cow", "Bull", "Calf", "Chicken", "Rooster",
		"Hen", "Chick", "Duck", "Goose", "Swan", "Crane", "Heron", "Stork", "Flamingo", "Pelican",
		"Penguin", "Parrot", "Toucan", "Peacock", "Owl", "Eagle", "Hawk", "Falcon", "Robin", "Sparrow",
		"Canary", "Finch", "Cardinal", "Bluebird", "Hummingbird", "Woodpecker", "Crow", "Raven", "Magpie", "Jay",
		"Turtle", "Tortoise", "Lizard", "Gecko", "Iguana", "Chameleon", "Snake", "Python", "Cobra", "Viper",
		"Frog", "Toad", "Salamander", "Newt", "Fish", "Goldfish", "Shark", "Ray", "Octopus", "Squid",
		"Crab", "Lobster", "Shrimp", "Starfish", "Seahorse", "Jellyfish", "Coral", "Anemone", "Clam", "Oyster",

		// Trees
		"Oak", "Maple", "Pine", "Birch", "Willow", "Cedar", "Elm", "Ash", "Poplar", "Spruce",
		"Fir", "Redwood", "Sequoia", "Cypress", "Juniper", "Yew", "Holly", "Magnolia", "Dogwood", "Cherry",
		"Apple", "Pear", "Peach", "Plum", "Orange", "Lemon", "Lime", "Grapefruit", "Walnut", "Chestnut",
		"Hickory", "Pecan", "Almond", "Hazel", "Beech", "Sycamore", "Cottonwood", "Aspen", "Basswood", "Mulberry",
		"Locust", "Catalpa", "Tulip", "Sweetgum", "Liquidambar", "Eucalyptus", "Acacia", "Mimosa", "Jacaranda", "Baobab",
		"Banyan", "Mahogany", "Teak", "Rosewood", "Ebony", "Sandalwood", "Bamboo", "Palm", "Coconut", "Date",

		// Objects of Nature
		"Mountain", "Hill", "Valley", "Canyon", "Cliff", "Mesa", "Plateau", "Ridge", "Peak", "Summit",
		"Volcano", "Geyser", "Spring", "Stream", "River", "Lake", "Pond", "Waterfall", "Rapids", "Delta",
		"Ocean", "Sea", "Bay", "Gulf", "Strait", "Channel", "Lagoon", "Reef", "Island", "Peninsula",
		"Beach", "Shore", "Coast", "Dune", "Desert", "Oasis", "Prairie", "Meadow", "Field", "Forest",
		"Grove", "Jungle", "Swamp", "Marsh", "Bog", "Tundra", "Glacier", "Iceberg", "Cave", "Cavern",
		"Rock", "Stone", "Boulder", "Pebble", "Sand", "Soil", "Clay", "Mud", "Dust", "Ash",
		"Crystal", "Diamond", "Emerald", "Ruby", "Sapphire", "Amethyst", "Quartz", "Jade", "Opal", "Pearl",
		"Coral", "Amber", "Fossil", "Mineral", "Ore", "Metal", "Gold", "Silver", "Copper", "Iron",
		"Cloud", "Mist", "Fog", "Rain", "Snow", "Hail", "Sleet", "Thunder", "Lightning", "Rainbow",
		"Sun", "Moon", "Star", "Planet", "Comet", "Meteor", "Galaxy", "Nebula", "Aurora", "Eclipse",
		"Wind", "Breeze", "Gale", "Storm", "Hurricane", "Tornado", "Cyclone", "Typhoon", "Blizzard", "Drought",
		"Flower", "Rose", "Lily", "Daisy", "Tulip", "Sunflower", "Daffodil", "Orchid", "Iris", "Peony",
		"Jasmine", "Lavender", "Violet", "Poppy", "Carnation", "Chrysanthemum", "Hibiscus", "Azalea", "Rhododendron", "Camellia",
		"Leaf", "Branch", "Twig", "Root", "Bark", "Seed", "Fruit", "Berry", "Nut", "Acorn",
		"Pinecone", "Mushroom", "Fungus", "Moss", "Lichen", "Algae", "Seaweed", "Kelp", "Plankton", "Bacteria",

		// Tools
		"Hammer", "Screwdriver", "Wrench", "Pliers", "Saw", "Drill", "Chisel", "File", "Plane", "Level",
		"Ruler", "Tape", "Compass", "Square", "Protractor", "Caliper", "Gauge", "Meter", "Scale", "Balance",
		"Knife", "Blade", "Scissor", "Shear", "Cutter", "Slicer", "Peeler", "Grater", "Whisk", "Spatula",
		"Ladle", "Spoon", "Fork", "Chopstick", "Tong", "Strainer", "Colander", "Sieve", "Funnel", "Pitcher",
		"Brush", "Broom", "Mop", "Vacuum", "Duster", "Cloth", "Towel", "Sponge", "Bucket", "Basin",
		"Shovel", "Spade", "Rake", "Hoe", "Pickaxe", "Axe", "Hatchet", "Chainsaw", "Lawnmower", "Trimmer",
		"Wheelbarrow", "Cart", "Wagon", "Trolley", "Dolly", "Crane", "Hoist", "Pulley", "Winch", "Jack",
		"Clamp", "Vise", "Anchor", "Hook", "Nail", "Screw", "Bolt", "Nut", "Washer", "Gasket",
		"Spring", "Gear", "Wheel", "Axle", "Belt", "Chain", "Rope", "Cable", "Wire", "Cord",
		"Thread", "Yarn", "String", "Ribbon", "Tape", "Glue", "Adhesive", "Cement", "Mortar", "Concrete",

		// Machines
		"Engine", "Motor", "Generator", "Turbine", "Pump", "Compressor", "Fan", "Blower", "Ventilator", "Conditioner",
		"Heater", "Cooler", "Refrigerator", "Freezer", "Oven", "Stove", "Microwave", "Toaster", "Blender", "Mixer",
		"Processor", "Grinder", "Crusher", "Shredder", "Slicer", "Dicer", "Juicer", "Extractor", "Separator", "Filter",
		"Washer", "Dryer", "Cleaner", "Polisher", "Buffer", "Sander", "Grinder", "Welder", "Cutter", "Printer",
		"Scanner", "Copier", "Fax", "Phone", "Radio", "Television", "Computer", "Laptop", "Tablet", "Smartphone",
		"Camera", "Camcorder", "Projector", "Screen", "Monitor", "Speaker", "Microphone", "Headphone", "Earphone", "Amplifier",
		"Receiver", "Transmitter", "Antenna", "Satellite", "Router", "Modem", "Switch", "Hub", "Server", "Database",
		"Calculator", "Typewriter", "Keyboard", "Mouse", "Joystick", "Controller", "Remote", "Sensor", "Detector", "Alarm",
		"Timer", "Clock", "Watch", "Compass", "Telescope", "Microscope", "Binocular", "Magnifier", "Lens", "Mirror",
		"Prism", "Filter", "Screen", "Shade", "Blind", "Curtain", "Drape", "Awning", "Canopy", "Umbrella",

		// Musical Instruments
		"Piano", "Guitar", "Violin", "Cello", "Bass", "Harp", "Flute", "Clarinet", "Saxophone", "Trumpet",
		"Trombone", "Horn", "Tuba", "Drum", "Cymbal", "Triangle", "Bell", "Chime", "Xylophone", "Marimba",
		"Organ", "Accordion", "Harmonica", "Recorder", "Piccolo", "Oboe", "Bassoon", "Cornet", "Bugle", "Bagpipe",

		// Household Items
		"Chair", "Table", "Desk", "Bed", "Sofa", "Couch", "Bench", "Stool", "Shelf", "Cabinet",
		"Drawer", "Closet", "Wardrobe", "Dresser", "Mirror", "Lamp", "Light", "Candle", "Lantern", "Torch",
		"Pillow", "Cushion", "Blanket", "Sheet", "Quilt", "Comforter", "Mattress", "Frame", "Headboard", "Footboard",
		"Curtain", "Drape", "Blind", "Shade", "Screen", "Door", "Window", "Wall", "Floor", "Ceiling",
		"Roof", "Chimney", "Fireplace", "Hearth", "Mantle", "Stair", "Banister", "Railing", "Balcony", "Porch",
		"Deck", "Patio", "Garden", "Yard", "Fence", "Gate", "Path", "Walkway", "Driveway", "Garage",

		// Food Items
		"Bread", "Cake", "Cookie", "Pie", "Pastry", "Muffin", "Bagel", "Donut", "Croissant", "Pretzel",
		"Cheese", "Butter", "Milk", "Cream", "Yogurt", "Ice", "Soup", "Salad", "Sandwich", "Pizza",
		"Pasta", "Noodle", "Rice", "Grain", "Cereal", "Oat", "Wheat", "Corn", "Barley", "Quinoa",
		"Bean", "Pea", "Lentil", "Chickpea", "Soy", "Tofu", "Tempeh", "Seitan", "Protein", "Vitamin",
		"Mineral", "Fiber", "Carb", "Fat", "Oil", "Vinegar", "Salt", "Pepper", "Spice", "Herb",
		"Basil", "Oregano", "Thyme", "Rosemary", "Sage", "Mint", "Parsley", "Cilantro", "Dill", "Chive",
		"Onion", "Garlic", "Ginger", "Turmeric", "Cinnamon", "Vanilla", "Chocolate", "Cocoa", "Coffee", "Tea",
		"Honey", "Sugar", "Syrup", "Jam", "Jelly", "Preserve", "Sauce", "Ketchup", "Mustard", "Mayo",

		// Clothing
		"Shirt", "Blouse", "Dress", "Skirt", "Pants", "Jeans", "Short", "Jacket", "Coat", "Sweater",
		"Cardigan", "Hoodie", "Vest", "Blazer", "Suit", "Tie", "Scarf", "Shawl", "Glove", "Mitten",
		"Hat", "Cap", "Beanie", "Beret", "Helmet", "Crown", "Headband", "Bandana", "Sock", "Stocking",
		"Shoe", "Boot", "Sandal", "Slipper", "Sneaker", "Heel", "Flat", "Loafer", "Moccasin", "Clog",
		"Belt", "Buckle", "Button", "Zipper", "Snap", "Velcro", "Lace", "Ribbon", "Bow", "Pocket",

		// Sports Equipment
		"Ball", "Bat", "Racket", "Paddle", "Stick", "Club", "Glove", "Mitt", "Helmet", "Pad",
		"Goal", "Net", "Hoop", "Basket", "Target", "Arrow", "Bow", "Dart", "Disc", "Frisbee",
		"Skate", "Ski", "Snowboard", "Surfboard", "Skateboard", "Scooter", "Bike", "Bicycle", "Tricycle", "Unicycle",
		"Wheel", "Tire", "Pedal", "Brake", "Gear", "Chain", "Handle", "Grip", "Seat", "Saddle",

		// Vehicles
		"Car", "Truck", "Van", "Bus", "Train", "Plane", "Helicopter", "Boat", "Ship", "Yacht",
		"Canoe", "Kayak", "Raft", "Sailboat", "Motorboat", "Submarine", "Rocket", "Spaceship", "Shuttle", "Satellite",
		"Motorcycle", "Scooter", "Moped", "ATV", "Jeep", "SUV", "Sedan", "Coupe", "Convertible", "Wagon",
		"Pickup", "Trailer", "Camper", "RV", "Ambulance", "Firetruck", "Police", "Taxi", "Limo", "Hearse",

		// Toys and Games
		"Doll", "Bear", "Robot", "Puzzle", "Block", "Lego", "Toy", "Game", "Card", "Dice",
		"Marble", "Spinner", "Top", "Kite", "Balloon", "Bubble", "Slinky", "Yoyo", "Frisbee", "Boomerang",
		"Chess", "Checker", "Domino", "Backgammon", "Scrabble", "Monopoly", "Risk", "Clue", "Trivia", "Bingo",
		"Crossword", "Sudoku", "Riddle", "Joke", "Story", "Book", "Magazine", "Comic", "Novel", "Poetry",

		// Art Supplies
		"Paint", "Brush", "Canvas", "Easel", "Palette", "Pencil", "Pen", "Marker", "Crayon", "Chalk",
		"Charcoal", "Pastel", "Ink", "Paper", "Sketchpad", "Notebook", "Journal", "Diary", "Album", "Frame",
		"Sculpture", "Clay", "Pottery", "Ceramic", "Glass", "Crystal", "Prism", "Lens", "Film", "Photo",
		"Picture", "Image", "Drawing", "Sketch", "Painting", "Portrait", "Landscape", "Still", "Abstract", "Modern",

		// Gems and Minerals
		"Diamond", "Ruby", "Emerald", "Sapphire", "Amethyst", "Topaz", "Garnet", "Peridot", "Aquamarine", "Tourmaline",
		"Opal", "Turquoise", "Jade", "Onyx", "Agate", "Jasper", "Quartz", "Citrine", "Moonstone", "Sunstone",
		"Labradorite", "Malachite", "Lapis", "Hematite", "Obsidian", "Flint", "Marble", "Granite", "Slate", "Shale",
		"Sandstone", "Limestone", "Basalt", "Pumice", "Volcanic", "Sedimentary", "Igneous", "Metamorphic", "Fossil", "Amber",

		// Weather Phenomena
		"Storm", "Hurricane", "Tornado", "Cyclone", "Typhoon", "Blizzard", "Avalanche", "Earthquake", "Tsunami", "Flood",
		"Drought", "Heatwave", "Coldfront", "Warmfront", "Pressure", "Temperature", "Humidity", "Precipitation", "Evaporation", "Condensation",
		"Dewpoint", "Frostpoint", "Windchill", "Heatindex", "Barometer", "Thermometer", "Hygrometer", "Anemometer", "Vane", "Gauge",

		// Celestial Bodies
		"Sun", "Moon", "Star", "Planet", "Comet", "Meteor", "Asteroid", "Galaxy", "Nebula", "Constellation",
		"Universe", "Cosmos", "Space", "Void", "Orbit", "Satellite", "Rocket", "Shuttle", "Station", "Telescope",
		"Observatory", "Planetarium", "Astronomer", "Cosmologist", "Physicist", "Scientist", "Researcher", "Explorer", "Pioneer", "Discoverer",

		// Mythical Creatures
		"Dragon", "Phoenix", "Unicorn", "Pegasus", "Griffin", "Sphinx", "Centaur", "Minotaur", "Hydra", "Chimera",
		"Kraken", "Leviathan", "Basilisk", "Gargoyle", "Golem", "Djinn", "Genie", "Fairy", "Pixie", "Sprite",
		"Elf", "Dwarf", "Gnome", "Troll", "Ogre", "Giant", "Cyclops", "Titan", "God", "Goddess",
		"Angel", "Demon", "Spirit", "Ghost", "Phantom", "Specter", "Wraith", "Banshee", "Poltergeist", "Apparition",

		// Professions
		"Teacher", "Doctor", "Nurse", "Engineer", "Architect", "Designer", "Artist", "Musician", "Writer", "Poet",
		"Actor", "Dancer", "Singer", "Comedian", "Chef", "Baker", "Farmer", "Gardener", "Carpenter", "Plumber",
		"Electrician", "Mechanic", "Pilot", "Captain", "Sailor", "Soldier", "Officer", "Detective", "Judge", "Lawyer",
		"Scientist", "Researcher", "Professor", "Student", "Librarian", "Journalist", "Reporter", "Editor", "Publisher", "Photographer",
		"Filmmaker", "Director", "Producer", "Screenwriter", "Animator", "Illustrator", "Sculptor", "Painter", "Craftsman", "Artisan",

		// Buildings and Structures
		"House", "Home", "Mansion", "Cottage", "Cabin", "Castle", "Palace", "Tower", "Skyscraper", "Building",
		"Apartment", "Condo", "Loft", "Studio", "Penthouse", "Duplex", "Triplex", "Townhouse", "Villa", "Estate",
		"School", "College", "University", "Library", "Museum", "Gallery", "Theater", "Cinema", "Stadium", "Arena",
		"Church", "Temple", "Mosque", "Synagogue", "Cathedral", "Chapel", "Monastery", "Convent", "Shrine", "Altar",
		"Hospital", "Clinic", "Pharmacy", "Laboratory", "Factory", "Workshop", "Studio", "Office", "Store", "Shop",
		"Market", "Mall", "Plaza", "Square", "Park", "Garden", "Zoo", "Aquarium", "Botanical", "Conservatory",
		"Bridge", "Tunnel", "Road", "Street", "Avenue", "Boulevard", "Highway", "Freeway", "Path", "Trail",
		"Sidewalk", "Crosswalk", "Intersection", "Roundabout", "Overpass", "Underpass", "Viaduct", "Aqueduct", "Dam", "Levee",
		"Pier", "Dock", "Wharf", "Harbor", "Port", "Marina", "Lighthouse", "Beacon", "Buoy", "Anchor",
		"Mast", "Sail", "Rudder", "Propeller", "Engine", "Turbine", "Generator", "Transformer", "Conductor", "Insulator",
	}
}
