// Code generated by mockery. DO NOT EDIT.

package mock_space

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	spaceinfo "github.com/anyproto/anytype-heart/space/spaceinfo"
)

// MocklocalDeleter is an autogenerated mock type for the localDeleter type
type MocklocalDeleter struct {
	mock.Mock
}

type MocklocalDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *MocklocalDeleter) EXPECT() *MocklocalDeleter_Expecter {
	return &MocklocalDeleter_Expecter{mock: &_m.Mock}
}

// allIDs provides a mock function with given fields:
func (_m *MocklocalDeleter) allIDs() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for allIDs")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MocklocalDeleter_allIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'allIDs'
type MocklocalDeleter_allIDs_Call struct {
	*mock.Call
}

// allIDs is a helper method to define mock.On call
func (_e *MocklocalDeleter_Expecter) allIDs() *MocklocalDeleter_allIDs_Call {
	return &MocklocalDeleter_allIDs_Call{Call: _e.mock.On("allIDs")}
}

func (_c *MocklocalDeleter_allIDs_Call) Run(run func()) *MocklocalDeleter_allIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MocklocalDeleter_allIDs_Call) Return(ids []string) *MocklocalDeleter_allIDs_Call {
	_c.Call.Return(ids)
	return _c
}

func (_c *MocklocalDeleter_allIDs_Call) RunAndReturn(run func() []string) *MocklocalDeleter_allIDs_Call {
	_c.Call.Return(run)
	return _c
}

// updateRemoteStatus provides a mock function with given fields: ctx, spaceId, status
func (_m *MocklocalDeleter) updateRemoteStatus(ctx context.Context, spaceId string, status spaceinfo.RemoteStatus) error {
	ret := _m.Called(ctx, spaceId, status)

	if len(ret) == 0 {
		panic("no return value specified for updateRemoteStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, spaceinfo.RemoteStatus) error); ok {
		r0 = rf(ctx, spaceId, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MocklocalDeleter_updateRemoteStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'updateRemoteStatus'
type MocklocalDeleter_updateRemoteStatus_Call struct {
	*mock.Call
}

// updateRemoteStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - spaceId string
//   - status spaceinfo.RemoteStatus
func (_e *MocklocalDeleter_Expecter) updateRemoteStatus(ctx interface{}, spaceId interface{}, status interface{}) *MocklocalDeleter_updateRemoteStatus_Call {
	return &MocklocalDeleter_updateRemoteStatus_Call{Call: _e.mock.On("updateRemoteStatus", ctx, spaceId, status)}
}

func (_c *MocklocalDeleter_updateRemoteStatus_Call) Run(run func(ctx context.Context, spaceId string, status spaceinfo.RemoteStatus)) *MocklocalDeleter_updateRemoteStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(spaceinfo.RemoteStatus))
	})
	return _c
}

func (_c *MocklocalDeleter_updateRemoteStatus_Call) Return(_a0 error) *MocklocalDeleter_updateRemoteStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MocklocalDeleter_updateRemoteStatus_Call) RunAndReturn(run func(context.Context, string, spaceinfo.RemoteStatus) error) *MocklocalDeleter_updateRemoteStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMocklocalDeleter creates a new instance of MocklocalDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocklocalDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MocklocalDeleter {
	mock := &MocklocalDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
