// Code generated by go-swagger; DO NOT EDIT.

package spaces

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/anyproto/anytype-heart/cmd/anyctl/models"
)

// GetSpacesSpaceIDMembersReader is a Reader for the GetSpacesSpaceIDMembers structure.
type GetSpacesSpaceIDMembersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSpacesSpaceIDMembersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSpacesSpaceIDMembersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetSpacesSpaceIDMembersUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetSpacesSpaceIDMembersInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /spaces/{space_id}/members] GetSpacesSpaceIDMembers", response, response.Code())
	}
}

// NewGetSpacesSpaceIDMembersOK creates a GetSpacesSpaceIDMembersOK with default headers values
func NewGetSpacesSpaceIDMembersOK() *GetSpacesSpaceIDMembersOK {
	return &GetSpacesSpaceIDMembersOK{}
}

/*
GetSpacesSpaceIDMembersOK describes a response with status code 200, with default header values.

List of members
*/
type GetSpacesSpaceIDMembersOK struct {
	Payload *models.PaginationPaginatedResponseSpaceMember
}

// IsSuccess returns true when this get spaces space Id members o k response has a 2xx status code
func (o *GetSpacesSpaceIDMembersOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get spaces space Id members o k response has a 3xx status code
func (o *GetSpacesSpaceIDMembersOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get spaces space Id members o k response has a 4xx status code
func (o *GetSpacesSpaceIDMembersOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get spaces space Id members o k response has a 5xx status code
func (o *GetSpacesSpaceIDMembersOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get spaces space Id members o k response a status code equal to that given
func (o *GetSpacesSpaceIDMembersOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get spaces space Id members o k response
func (o *GetSpacesSpaceIDMembersOK) Code() int {
	return 200
}

func (o *GetSpacesSpaceIDMembersOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /spaces/{space_id}/members][%d] getSpacesSpaceIdMembersOK %s", 200, payload)
}

func (o *GetSpacesSpaceIDMembersOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /spaces/{space_id}/members][%d] getSpacesSpaceIdMembersOK %s", 200, payload)
}

func (o *GetSpacesSpaceIDMembersOK) GetPayload() *models.PaginationPaginatedResponseSpaceMember {
	return o.Payload
}

func (o *GetSpacesSpaceIDMembersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PaginationPaginatedResponseSpaceMember)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSpacesSpaceIDMembersUnauthorized creates a GetSpacesSpaceIDMembersUnauthorized with default headers values
func NewGetSpacesSpaceIDMembersUnauthorized() *GetSpacesSpaceIDMembersUnauthorized {
	return &GetSpacesSpaceIDMembersUnauthorized{}
}

/*
GetSpacesSpaceIDMembersUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetSpacesSpaceIDMembersUnauthorized struct {
	Payload *models.UtilUnauthorizedError
}

// IsSuccess returns true when this get spaces space Id members unauthorized response has a 2xx status code
func (o *GetSpacesSpaceIDMembersUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get spaces space Id members unauthorized response has a 3xx status code
func (o *GetSpacesSpaceIDMembersUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get spaces space Id members unauthorized response has a 4xx status code
func (o *GetSpacesSpaceIDMembersUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get spaces space Id members unauthorized response has a 5xx status code
func (o *GetSpacesSpaceIDMembersUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get spaces space Id members unauthorized response a status code equal to that given
func (o *GetSpacesSpaceIDMembersUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get spaces space Id members unauthorized response
func (o *GetSpacesSpaceIDMembersUnauthorized) Code() int {
	return 401
}

func (o *GetSpacesSpaceIDMembersUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /spaces/{space_id}/members][%d] getSpacesSpaceIdMembersUnauthorized %s", 401, payload)
}

func (o *GetSpacesSpaceIDMembersUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /spaces/{space_id}/members][%d] getSpacesSpaceIdMembersUnauthorized %s", 401, payload)
}

func (o *GetSpacesSpaceIDMembersUnauthorized) GetPayload() *models.UtilUnauthorizedError {
	return o.Payload
}

func (o *GetSpacesSpaceIDMembersUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UtilUnauthorizedError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSpacesSpaceIDMembersInternalServerError creates a GetSpacesSpaceIDMembersInternalServerError with default headers values
func NewGetSpacesSpaceIDMembersInternalServerError() *GetSpacesSpaceIDMembersInternalServerError {
	return &GetSpacesSpaceIDMembersInternalServerError{}
}

/*
GetSpacesSpaceIDMembersInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetSpacesSpaceIDMembersInternalServerError struct {
	Payload *models.UtilServerError
}

// IsSuccess returns true when this get spaces space Id members internal server error response has a 2xx status code
func (o *GetSpacesSpaceIDMembersInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get spaces space Id members internal server error response has a 3xx status code
func (o *GetSpacesSpaceIDMembersInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get spaces space Id members internal server error response has a 4xx status code
func (o *GetSpacesSpaceIDMembersInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get spaces space Id members internal server error response has a 5xx status code
func (o *GetSpacesSpaceIDMembersInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get spaces space Id members internal server error response a status code equal to that given
func (o *GetSpacesSpaceIDMembersInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get spaces space Id members internal server error response
func (o *GetSpacesSpaceIDMembersInternalServerError) Code() int {
	return 500
}

func (o *GetSpacesSpaceIDMembersInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /spaces/{space_id}/members][%d] getSpacesSpaceIdMembersInternalServerError %s", 500, payload)
}

func (o *GetSpacesSpaceIDMembersInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /spaces/{space_id}/members][%d] getSpacesSpaceIdMembersInternalServerError %s", 500, payload)
}

func (o *GetSpacesSpaceIDMembersInternalServerError) GetPayload() *models.UtilServerError {
	return o.Payload
}

func (o *GetSpacesSpaceIDMembersInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UtilServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
