// Code generated by protoc-gen-go. DO NOT EDIT.
// source: events.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccountAdd_Error_Code int32

const (
	AccountAdd_Error_NULL                            AccountAdd_Error_Code = 0
	AccountAdd_Error_UNKNOWN_ERROR                   AccountAdd_Error_Code = 1
	AccountAdd_Error_BAD_INPUT                       AccountAdd_Error_Code = 2
	AccountAdd_Error_FAILED_TO_CREATE_LOCAL_REPO     AccountAdd_Error_Code = 101
	AccountAdd_Error_LOCAL_REPO_EXISTS_BUT_CORRUPTED AccountAdd_Error_Code = 102
	AccountAdd_Error_FAILED_TO_RUN_NODE              AccountAdd_Error_Code = 103
	AccountAdd_Error_FAILED_TO_FIND_ACCOUNT_INFO     AccountAdd_Error_Code = 104
)

var AccountAdd_Error_Code_name = map[int32]string{
	0:   "NULL",
	1:   "UNKNOWN_ERROR",
	2:   "BAD_INPUT",
	101: "FAILED_TO_CREATE_LOCAL_REPO",
	102: "LOCAL_REPO_EXISTS_BUT_CORRUPTED",
	103: "FAILED_TO_RUN_NODE",
	104: "FAILED_TO_FIND_ACCOUNT_INFO",
}

var AccountAdd_Error_Code_value = map[string]int32{
	"NULL":                            0,
	"UNKNOWN_ERROR":                   1,
	"BAD_INPUT":                       2,
	"FAILED_TO_CREATE_LOCAL_REPO":     101,
	"LOCAL_REPO_EXISTS_BUT_CORRUPTED": 102,
	"FAILED_TO_RUN_NODE":              103,
	"FAILED_TO_FIND_ACCOUNT_INFO":     104,
}

func (x AccountAdd_Error_Code) String() string {
	return proto.EnumName(AccountAdd_Error_Code_name, int32(x))
}

func (AccountAdd_Error_Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{1, 0, 0}
}

// -------- Middle
type Event struct {
	// Types that are valid to be assigned to Message:
	//	*Event_AccountAdd
	//	*Event_BlockCreate
	//	*Event_BlockUpdate
	//	*Event_BlockRemove
	Message              isEvent_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

type isEvent_Message interface {
	isEvent_Message()
}

type Event_AccountAdd struct {
	AccountAdd *AccountAdd `protobuf:"bytes,1,opt,name=accountAdd,proto3,oneof"`
}

type Event_BlockCreate struct {
	BlockCreate *BlockCreate `protobuf:"bytes,102,opt,name=blockCreate,proto3,oneof"`
}

type Event_BlockUpdate struct {
	BlockUpdate *BlockUpdate `protobuf:"bytes,103,opt,name=blockUpdate,proto3,oneof"`
}

type Event_BlockRemove struct {
	BlockRemove *BlockRemove `protobuf:"bytes,104,opt,name=blockRemove,proto3,oneof"`
}

func (*Event_AccountAdd) isEvent_Message() {}

func (*Event_BlockCreate) isEvent_Message() {}

func (*Event_BlockUpdate) isEvent_Message() {}

func (*Event_BlockRemove) isEvent_Message() {}

func (m *Event) GetMessage() isEvent_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Event) GetAccountAdd() *AccountAdd {
	if x, ok := m.GetMessage().(*Event_AccountAdd); ok {
		return x.AccountAdd
	}
	return nil
}

func (m *Event) GetBlockCreate() *BlockCreate {
	if x, ok := m.GetMessage().(*Event_BlockCreate); ok {
		return x.BlockCreate
	}
	return nil
}

func (m *Event) GetBlockUpdate() *BlockUpdate {
	if x, ok := m.GetMessage().(*Event_BlockUpdate); ok {
		return x.BlockUpdate
	}
	return nil
}

func (m *Event) GetBlockRemove() *BlockRemove {
	if x, ok := m.GetMessage().(*Event_BlockRemove); ok {
		return x.BlockRemove
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Event) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Event_AccountAdd)(nil),
		(*Event_BlockCreate)(nil),
		(*Event_BlockUpdate)(nil),
		(*Event_BlockRemove)(nil),
	}
}

type AccountAdd struct {
	Error                *AccountAdd_Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Index                int64             `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Account              *Account          `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AccountAdd) Reset()         { *m = AccountAdd{} }
func (m *AccountAdd) String() string { return proto.CompactTextString(m) }
func (*AccountAdd) ProtoMessage()    {}
func (*AccountAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{1}
}

func (m *AccountAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountAdd.Unmarshal(m, b)
}
func (m *AccountAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountAdd.Marshal(b, m, deterministic)
}
func (m *AccountAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountAdd.Merge(m, src)
}
func (m *AccountAdd) XXX_Size() int {
	return xxx_messageInfo_AccountAdd.Size(m)
}
func (m *AccountAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountAdd.DiscardUnknown(m)
}

var xxx_messageInfo_AccountAdd proto.InternalMessageInfo

func (m *AccountAdd) GetError() *AccountAdd_Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *AccountAdd) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *AccountAdd) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type AccountAdd_Error struct {
	Code                 AccountAdd_Error_Code `protobuf:"varint,1,opt,name=code,proto3,enum=anytype.AccountAdd_Error_Code" json:"code,omitempty"`
	Desc                 string                `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *AccountAdd_Error) Reset()         { *m = AccountAdd_Error{} }
func (m *AccountAdd_Error) String() string { return proto.CompactTextString(m) }
func (*AccountAdd_Error) ProtoMessage()    {}
func (*AccountAdd_Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{1, 0}
}

func (m *AccountAdd_Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountAdd_Error.Unmarshal(m, b)
}
func (m *AccountAdd_Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountAdd_Error.Marshal(b, m, deterministic)
}
func (m *AccountAdd_Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountAdd_Error.Merge(m, src)
}
func (m *AccountAdd_Error) XXX_Size() int {
	return xxx_messageInfo_AccountAdd_Error.Size(m)
}
func (m *AccountAdd_Error) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountAdd_Error.DiscardUnknown(m)
}

var xxx_messageInfo_AccountAdd_Error proto.InternalMessageInfo

func (m *AccountAdd_Error) GetCode() AccountAdd_Error_Code {
	if m != nil {
		return m.Code
	}
	return AccountAdd_Error_NULL
}

func (m *AccountAdd_Error) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type BlockCreate struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DocId                string   `protobuf:"bytes,2,opt,name=docId,proto3" json:"docId,omitempty"`
	Pos                  uint32   `protobuf:"varint,3,opt,name=pos,proto3" json:"pos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockCreate) Reset()         { *m = BlockCreate{} }
func (m *BlockCreate) String() string { return proto.CompactTextString(m) }
func (*BlockCreate) ProtoMessage()    {}
func (*BlockCreate) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{2}
}

func (m *BlockCreate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockCreate.Unmarshal(m, b)
}
func (m *BlockCreate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockCreate.Marshal(b, m, deterministic)
}
func (m *BlockCreate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockCreate.Merge(m, src)
}
func (m *BlockCreate) XXX_Size() int {
	return xxx_messageInfo_BlockCreate.Size(m)
}
func (m *BlockCreate) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockCreate.DiscardUnknown(m)
}

var xxx_messageInfo_BlockCreate proto.InternalMessageInfo

func (m *BlockCreate) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BlockCreate) GetDocId() string {
	if m != nil {
		return m.DocId
	}
	return ""
}

func (m *BlockCreate) GetPos() uint32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

type BlockUpdate struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DocId                string   `protobuf:"bytes,2,opt,name=docId,proto3" json:"docId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockUpdate) Reset()         { *m = BlockUpdate{} }
func (m *BlockUpdate) String() string { return proto.CompactTextString(m) }
func (*BlockUpdate) ProtoMessage()    {}
func (*BlockUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{3}
}

func (m *BlockUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockUpdate.Unmarshal(m, b)
}
func (m *BlockUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockUpdate.Marshal(b, m, deterministic)
}
func (m *BlockUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockUpdate.Merge(m, src)
}
func (m *BlockUpdate) XXX_Size() int {
	return xxx_messageInfo_BlockUpdate.Size(m)
}
func (m *BlockUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_BlockUpdate proto.InternalMessageInfo

func (m *BlockUpdate) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BlockUpdate) GetDocId() string {
	if m != nil {
		return m.DocId
	}
	return ""
}

type BlockRemove struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DocId                string   `protobuf:"bytes,2,opt,name=docId,proto3" json:"docId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockRemove) Reset()         { *m = BlockRemove{} }
func (m *BlockRemove) String() string { return proto.CompactTextString(m) }
func (*BlockRemove) ProtoMessage()    {}
func (*BlockRemove) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{4}
}

func (m *BlockRemove) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRemove.Unmarshal(m, b)
}
func (m *BlockRemove) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRemove.Marshal(b, m, deterministic)
}
func (m *BlockRemove) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRemove.Merge(m, src)
}
func (m *BlockRemove) XXX_Size() int {
	return xxx_messageInfo_BlockRemove.Size(m)
}
func (m *BlockRemove) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRemove.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRemove proto.InternalMessageInfo

func (m *BlockRemove) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BlockRemove) GetDocId() string {
	if m != nil {
		return m.DocId
	}
	return ""
}

func init() {
	proto.RegisterEnum("anytype.AccountAdd_Error_Code", AccountAdd_Error_Code_name, AccountAdd_Error_Code_value)
	proto.RegisterType((*Event)(nil), "anytype.Event")
	proto.RegisterType((*AccountAdd)(nil), "anytype.AccountAdd")
	proto.RegisterType((*AccountAdd_Error)(nil), "anytype.AccountAdd.Error")
	proto.RegisterType((*BlockCreate)(nil), "anytype.BlockCreate")
	proto.RegisterType((*BlockUpdate)(nil), "anytype.BlockUpdate")
	proto.RegisterType((*BlockRemove)(nil), "anytype.BlockRemove")
}

func init() { proto.RegisterFile("events.proto", fileDescriptor_8f22242cb04491f9) }

var fileDescriptor_8f22242cb04491f9 = []byte{
	// 469 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x4f, 0x6b, 0xdb, 0x4c,
	0x10, 0xc6, 0x2d, 0x59, 0x7e, 0xfd, 0x7a, 0x1c, 0x07, 0x75, 0x1b, 0x8a, 0x9a, 0x42, 0x13, 0xd4,
	0x4b, 0xe8, 0x41, 0x05, 0x87, 0x42, 0xaf, 0xfa, 0xb3, 0x26, 0xa2, 0x62, 0x65, 0x36, 0x12, 0x2d,
	0xbd, 0x2c, 0xb6, 0x76, 0xe3, 0x98, 0xc6, 0x5e, 0x21, 0xa9, 0xa1, 0x39, 0x97, 0x7e, 0xa0, 0x7e,
	0xba, 0x5e, 0x8b, 0xb4, 0xaa, 0xec, 0x16, 0x17, 0x72, 0xdb, 0x47, 0xf3, 0xfc, 0x9e, 0x61, 0x86,
	0x11, 0x1c, 0x89, 0x7b, 0xb1, 0xad, 0x4a, 0x27, 0x2f, 0x64, 0x25, 0xd1, 0x70, 0xb1, 0x7d, 0xa8,
	0x1e, 0x72, 0x71, 0x7a, 0xb4, 0x91, 0x5c, 0xdc, 0xb5, 0x9f, 0xed, 0x9f, 0x1a, 0x0c, 0x70, 0xed,
	0x43, 0x6f, 0x01, 0x16, 0x59, 0x26, 0xbf, 0x6c, 0x2b, 0x97, 0x73, 0x4b, 0x3b, 0xd7, 0x2e, 0xc6,
	0xd3, 0xa7, 0x4e, 0x4b, 0x39, 0x6e, 0x57, 0xba, 0xea, 0xd1, 0x3d, 0x23, 0x7a, 0x07, 0xe3, 0xe5,
	0x9d, 0xcc, 0x3e, 0xfb, 0x85, 0x58, 0x54, 0xc2, 0xba, 0x69, 0xb8, 0x93, 0x8e, 0xf3, 0x76, 0xb5,
	0xab, 0x1e, 0xdd, 0xb7, 0x76, 0x64, 0x9a, 0xf3, 0x9a, 0x5c, 0x1d, 0x22, 0x55, 0xad, 0x23, 0x95,
	0xec, 0x48, 0x2a, 0x36, 0xf2, 0x5e, 0x58, 0xb7, 0x87, 0x48, 0x55, 0xeb, 0x48, 0x25, 0xbd, 0x11,
	0x0c, 0x37, 0xa2, 0x2c, 0x17, 0x2b, 0x61, 0x7f, 0xef, 0x03, 0xec, 0xa6, 0x42, 0x6f, 0x60, 0x20,
	0x8a, 0x42, 0x16, 0xed, 0xe4, 0xcf, 0x0f, 0x4c, 0xee, 0xe0, 0xda, 0x40, 0x95, 0x0f, 0x9d, 0xc0,
	0x60, 0xbd, 0xe5, 0xe2, 0xab, 0xa5, 0x9f, 0x6b, 0x17, 0x7d, 0xaa, 0x04, 0x7a, 0x0d, 0xc3, 0x76,
	0x39, 0x56, 0xbf, 0x09, 0x32, 0xff, 0x0e, 0xa2, 0xbf, 0x0d, 0xa7, 0xdf, 0x74, 0x18, 0x34, 0x91,
	0x68, 0x0a, 0x46, 0x26, 0xb9, 0x68, 0x7a, 0x1f, 0x4f, 0x5f, 0xfe, 0xb3, 0xb7, 0xe3, 0x4b, 0x2e,
	0x68, 0xe3, 0x45, 0x08, 0x0c, 0x2e, 0xca, 0xac, 0x69, 0x3f, 0xa2, 0xcd, 0xdb, 0xfe, 0xa1, 0x81,
	0x51, 0x5b, 0xd0, 0xff, 0x60, 0x90, 0x34, 0x8a, 0xcc, 0x1e, 0x7a, 0x02, 0x93, 0x94, 0xbc, 0x27,
	0xf1, 0x07, 0xc2, 0x30, 0xa5, 0x31, 0x35, 0x35, 0x34, 0x81, 0x91, 0xe7, 0x06, 0x2c, 0x24, 0xf3,
	0x34, 0x31, 0x75, 0x74, 0x06, 0x2f, 0x66, 0x6e, 0x18, 0xe1, 0x80, 0x25, 0x31, 0xf3, 0x29, 0x76,
	0x13, 0xcc, 0xa2, 0xd8, 0x77, 0x23, 0x46, 0xf1, 0x3c, 0x36, 0x05, 0x7a, 0x05, 0x67, 0x3b, 0xcd,
	0xf0, 0xc7, 0xf0, 0x3a, 0xb9, 0x66, 0x5e, 0x9a, 0x30, 0x3f, 0xa6, 0x34, 0x9d, 0x27, 0x38, 0x30,
	0x6f, 0xd0, 0x33, 0x40, 0xbb, 0x14, 0x9a, 0x12, 0x46, 0xe2, 0x00, 0x9b, 0xab, 0x3f, 0xd3, 0x67,
	0x21, 0x09, 0x98, 0xeb, 0xfb, 0x71, 0x4a, 0x12, 0x16, 0x92, 0x59, 0x6c, 0xde, 0xda, 0x18, 0xc6,
	0x7b, 0x47, 0x82, 0x8e, 0x41, 0x5f, 0xab, 0xf3, 0x1b, 0x51, 0x7d, 0xcd, 0xeb, 0x35, 0x73, 0x99,
	0x85, 0xbc, 0x9d, 0x53, 0x09, 0x64, 0x42, 0x3f, 0x97, 0x65, 0xb3, 0xe2, 0x09, 0xad, 0x9f, 0xf6,
	0x65, 0x1b, 0xd3, 0x9e, 0xc8, 0xa3, 0x62, 0x3a, 0x48, 0x5d, 0xc7, 0xe3, 0x20, 0xcf, 0xf8, 0xa4,
	0xe7, 0xcb, 0xe5, 0x7f, 0xcd, 0xff, 0x73, 0xf9, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xe4, 0x90, 0xd3,
	0x1a, 0x66, 0x03, 0x00, 0x00,
}
