name: golangci-lint
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24
          cache: false
        env:
          GOPRIVATE: "github.com/anyproto"
      - name: git config
        run: git config --global url.https://${{ secrets.ANYTYPE_PAT }}@github.com/.insteadOf https://github.com/
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set GOEXPERIMENT flags
        run: |
          GO_MINOR=$(go version | sed -E 's/.*go1\.([0-9]+).*/\1/')
          if [ "$GO_MINOR" -lt 26 ]; then
            echo "GOEXPERIMENT=rangefunc" >> $GITHUB_ENV
          fi
      - name: Go get
        run: go get ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          skip-cache: true
          version: latest
          only-new-issues: true
          args: --timeout 25m --verbose
